import React from 'react';
import { Lang } from '../dictionary';
import { Leaf } from 'lucide-react';
import { motion } from 'framer-motion';

export function EnvironmentSEO({ lang }: { lang: Lang }) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="mt-16 text-left max-w-4xl mx-auto px-6 py-8 bg-emerald-50 dark:bg-emerald-900/10 rounded-3xl border border-emerald-100 dark:border-emerald-800/30"
    >
      <div className="flex items-center gap-4 mb-6">
        <div className="p-3 bg-emerald-500 rounded-xl text-white shadow-lg shadow-emerald-500/30">
          <Leaf className="w-8 h-8" />
        </div>
        <h2 className="text-2xl md:text-3xl font-black text-gray-900 dark:text-white">
          {lang === "TH" ? "เครื่องมือคำนวณด้านสิ่งแวดล้อม (Environment)" : "Environmental Calculators"}
        </h2>
      </div>
      
      <div className="prose prose-emerald dark:prose-invert max-w-none">
        <p className="text-gray-600 dark:text-gray-300 leading-relaxed text-lg mb-6">
          {lang === "TH" 
            ? "การเปลี่ยนแปลงสภาพภูมิอากาศ (Climate Change) และภาวะโลกร้อน (Global Warming) เป็นวิกฤตเร่งด่วนที่ส่งผลกระทบต่อเราทุกคน เครื่องมือคำนวณด้านสิ่งแวดล้อมของเราถูกออกแบบมาเพื่อช่วยให้บุคคลทั่วไปและองค์กรสามารถประเมินผลกระทบที่ตนเองมีต่อโลกใบนี้ได้อย่างเป็นรูปธรรม ไม่ว่าจะเป็นการคำนวณ คาร์บอนฟุตพรินต์ (Carbon Footprint) ขยะพลาสติก หรือการประหยัดทรัพยากรน้ำและพลังงานลม"
            : "Climate change and global warming are urgent crises affecting us all. Our environmental calculators are designed to help individuals and organizations concretely assess their impact on the planet, from calculating Carbon Footprints and plastic waste to water savings and wind energy potential."
          }
        </p>

        <h3 className="text-xl font-bold text-gray-800 dark:text-gray-200 mt-8 mb-4">
          {lang === "TH" ? "คาร์บอนฟุตพรินต์ (Carbon Footprint) คืออะไร?" : "What is a Carbon Footprint?"}
        </h3>
        <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
          {lang === "TH"
            ? "Carbon Footprint คือปริมาณก๊าซเรือนกระจกทั้งหมด (โดยเฉพาะคาร์บอนไดออกไซด์ CO2) ที่เกิดจากกิจกรรมต่างๆ ของมนุษย์ ทั้งทางตรงและทางอ้อม เช่น การขับรถ การใช้ไฟฟ้าในบ้าน การเดินทางด้วยเครื่องบิน หรือแม้แต่การบริโภคอาหาร การทราบค่าคาร์บอนฟุตพรินต์ส่วนบุคคลจะช่วยให้เราสามารถตั้งเป้าหมายลดการปล่อยก๊าซเรือนกระจก (Net Zero) และชดเชยคาร์บอน (Carbon Offset) ได้อย่างตรงจุด"
            : "A Carbon Footprint is the total amount of greenhouse gases (especially CO2) generated by our actions, both directly and indirectly. This includes driving, household electricity use, flights, and even our diet. Knowing your personal footprint helps set precise reduction goals towards Net Zero and carbon offsetting."
          }
        </p>
      </div>
    </motion.div>
  );
}
