"use client";

import { Lang } from "./dictionary";
import { BMICalculator, SleepCalculator, TDEECalculator, WaterCalculator as HealthWaterCalculator, FoodRandomizer } from "./calcs/HealthCalcs";
import { ExerciseCaloriesCalculator, ProteinCalculator, BodyFatCalculator, WHRCalculator, HeartRateZoneCalculator, MacroCalculator, BloodSugarConverter, IBWCalculator, StepsCalculator, OneRepMaxCalculator, PaceCalculator } from "./calcs/HealthCalcs2";
import { ChildHeightCalculator } from "./calcs/FamilyCalcs";
import { PregnancyDueCalculator, OvulationCalculator, BloodTypePredictor, ZodiacCalculator, PetAgeCalculator, FetalWeightCalculator, ChildCostCalculator, ChildMilestoneCalculator } from "./calcs/FamilyCalcs2";
import { TimeZoneConverter, TravelBudgetCalculator, FlightTimeCalculator, PackingListGenerator, RoadTripCostCalculator, BaggageWeightChecker } from "./calcs/TravelCalcs";
import { DiscountCalculator, CarLoanCalculator, MortgageCalculator, CompoundInterest, BillSplitter, CurrencyConverter } from "./calcs/FinanceCalcs";
import { SavingsGoalCalculator, InflationCalculator, SalaryToHourlyCalculator, NetWorthCalculator, DebtPayoffCalculator, RetirementCalculator, StockProfitCalculator, ROICalculator } from "./calcs/FinanceCalcs2";
import { DCACalculator, StockFeeCalculator, NetSalaryCalculator, ExpenseTrackerCalculator } from "./calcs/FinanceCalcs3";
import { PersonalTaxCalculator } from "./calcs/PersonalTaxCalculator";
import { GoldPriceCalculator } from "./calcs/GoldCalcs";
import { VO2MaxCalculator, SwimPaceCalculator, CyclingPowerZones } from "./calcs/ExerciseCalcs";
import { RacePredictor, LiftingPyramid, RowingSplit, CarbEnduranceCalc } from "./calcs/ExerciseCalcs2";
import { FiberCalculator, VitaminDCalculator, BMIKidsCalculator } from "./calcs/HealthCalcs3";
import { WeddingBudget, NewbornCost, PetCost, FoodExpiration, RentVsBuyCalc } from "./calcs/FamilyCalcs4";
import { EOQCalculator, ChurnRetentionCalc, ShrinkageCalc, ImportMarkupCalc, FreelanceRate } from "./calcs/BusinessCalcs4";
import { EnglishTestConverter, PomodoroTimer, FlashCardTimer } from "./calcs/EducationCalcs";
import { VatCalculator, MarginCalculator } from "./calcs/BusinessCalcs";
import { BreakEvenCalculator, MarkupCalculator, DepreciationCalculator, PayrollCalculator, COGSCalculator, LTVCalculator, CACCalculator, ConversionRateCalculator, InventoryTurnoverCalculator } from "./calcs/BusinessCalcs2";
import { FinancialRatioCalculator, MarketplaceFeeCalculator, SafetyStockCalculator, ShippingCostCalculator, ReturnRateCalculator } from "./calcs/BusinessCalcs3";
import { BTUCalculator, ElectricCalculator, WaterCalculator as UtilityWaterCalculator, BaseNCalculator, GPACalculator, FuelCostCalculator } from "./calcs/UtilityCalcs";
import { GradeConverter, TargetGPACalculator, PercentileCalculator, ReadingTimeCalculator } from "./calcs/UtilityCalcs2";
import { WordCounter, AgeCalculator } from "./calcs/GeneralCalcs";
import { CookingUnitConverter, TileAreaCalculator } from "./calcs/ConversionCalcs";
import { DigitalUnitConverter, AngleConverter, ColorConverter, TemperatureConverter, SpeedConverter, AreaUnitConverter, WeightUnitConverter, RomanNumeralConverter, AreaShapeCalculator, VolumeShapeCalculator, WorkingDaysCalculator } from "./calcs/ConversionCalcs2";
import { PantoneConverter } from "./calcs/ConversionCalcs3";
import { FoodEnergyCalculator, FertilizerCalculator, IrrigationCalculator, YieldCalculator } from "./calcs/AgricultureCalcs";
import { HousePaintCalculator, CementCalculator, WallpaperCalculator, RoofAreaCalculator, WaterTankCalculator, PoolVolumeCalculator, InsulationCalculator, RenovationCostCalculator } from "./calcs/ConstructionCalcs";
import { BandwidthCalculator, ServerCostCalculator, ImageSizeCalculator, IPSubnetCalculator, VideoBitrateCalculator, BatteryLifeCalculator, HashRateCalculator } from "./calcs/TechnologyCalcs";
import { RaidCalculator, PpiCalculator, ApiCostCalculator, UpsRuntimeCalculator, MorseCodeConverter, AsciiConverter, CacheHitRateCalculator } from "./calcs/TechnologyCalcs2";
import { DurianCalculator } from "./calcs/AgricultureCalcs2";
import { SoilPhCalculator, LivestockProfitCalculator, SprayVolumeCalculator, FisheryIncomeCalculator, YieldGapCalculator } from "./calcs/AgricultureCalcs3";
import { JetLagCalculator, RoamingCostCalculator } from "./calcs/TravelCalcs2";
import { SolarPanelCalculator, InteriorCostCalculator, AchVentilationCalculator, ConcreteVolumeCalculator, RebarWeightCalculator, AacBlocksCalculator, LaborCostCalculator, PlumbingPipeCalculator, SlopeGradeCalculator } from "./calcs/ConstructionCalcs2";
import { CarbonFootprintCalculator, WindEnergyCalculator, WaterSavingsCalculator, PlasticFootprintCalculator } from "./calcs/EnvironmentCalcs";
import { QuadraticCalculator, PHCalculator } from "./calcs/ScienceCalcs";

import { HoroscopeCalculator } from "./calcs/FamilyCalcs3";
import { TarotReadingCalculator } from "./calcs/TarotCalcs";
import DIOCalculator from "./calcs/calcs_batch_3_dio";
import DSOCalculator from "./calcs/calcs_batch_3_dso";
import EmployeeBonusCalculator from "./calcs/calcs_batch_3_employee-bonus";
import ExpenseRatioCalculator from "./calcs/calcs_batch_3_expense-ratio";
import GMVCalculator from "./calcs/calcs_batch_3_gmv-vs-net-revenue";
import HeadcountToSalesCalculator from "./calcs/calcs_batch_3_headcount-to-sales";
import InventoryCostingCalculator from "./calcs/calcs_batch_3_inventory-costing";
import LandedCostCalculator from "./calcs/calcs_batch_3_landed-cost";
import OfficeVsWfhCalculator from "./calcs/calcs_batch_3_office-vs-wfh";
import PackagingCostCalculator from "./calcs/calcs_batch_3_packaging-cost";
import BreakEvenChannelCalculator from "./calcs/calcs_batch_6_break-even-by-channel";
import CarbonCreditCostCalculator from "./calcs/calcs_batch_6_carbon-credit-cost";
import EventCostCalculator from "./calcs/calcs_batch_6_event-cost-per-attendee";
import IsoCertificationCostCalculator from "./calcs/calcs_batch_6_iso-certification-cost";
import NpvIrrCalculator from "./calcs/calcs_batch_6_npv-irr";
import PatentCostCalculator from "./calcs/calcs_batch_6_patent-cost";
import ProjectPaybackPeriodCalculator from "./calcs/calcs_batch_6_project-payback-period";
import RoyaltyIncomeCalculator from "./calcs/calcs_batch_6_royalty-income";
import SensitivityAnalysisCalculator from "./calcs/calcs_batch_6_sensitivity-analysis";
import SpaceRentalDepositCalculator from "./calcs/calcs_batch_6_space-rental-deposit";
import BreakEvenTime from "./calcs/calcs_batch_1_break-even-time";
import CapacityUtilizationRate from "./calcs/calcs_batch_1_capacity-utilization-rate";
import CashFlowProjection from "./calcs/calcs_batch_1_cash-flow-projection";
import CostPerUnit from "./calcs/calcs_batch_1_cost-per-unit";
import DoubleDecliningDepreciation from "./calcs/calcs_batch_1_double-declining-depreciation";
import FreelanceVsFulltimeCost from "./calcs/calcs_batch_1_freelance-vs-fulltime-cost";
import RetailSpaceRentRoi from "./calcs/calcs_batch_1_retail-space-rent-roi";
import SimplifiedPL from "./calcs/calcs_batch_1_simplified-p-and-l";
import WholesaleVsRetailMargin from "./calcs/calcs_batch_1_wholesale-vs-retail-margin";
import WorkingCapital from "./calcs/calcs_batch_1_working-capital";
import CompanyRegistrationCost from "./calcs/calcs_batch_2_company-registration-cost";
import CorporateTaxCalculator from "./calcs/calcs_batch_2_corporate-tax";
import CreditCardMdrFee from "./calcs/calcs_batch_2_credit-card-mdr-fee";
import DeRatio from "./calcs/calcs_batch_2_de-ratio";
import LegalReserveCalculator from "./calcs/calcs_batch_2_legal-reserve";
import MarkupImportedMaterials from "./calcs/calcs_batch_2_markup-imported-materials";
import PosSystemComparison from "./calcs/calcs_batch_2_pos-system-comparison";
import QuickCurrentRatio from "./calcs/calcs_batch_2_quick-current-ratio";
import RoeRoaRoic from "./calcs/calcs_batch_2_roe-roa-roic";
import SalesCommissionStructure from "./calcs/calcs_batch_2_sales-commission-structure";
import AdvertisingBudgetAllocation from "./calcs/calcs_batch_4_advertising-budget-allocation";
import CacPaybackPeriod from "./calcs/calcs_batch_4_cac-payback-period";
import EbitdaCalculator from "./calcs/calcs_batch_4_ebitda-calculator";
import EmployeeOtCalculation from "./calcs/calcs_batch_4_employee-ot-calculation";
import EmployerSocialSecurity from "./calcs/calcs_batch_4_employer-social-security";
import FxForwardRateRisk from "./calcs/calcs_batch_4_fx-forward-rate-risk";
import InternationalShippingCost from "./calcs/calcs_batch_4_international-shipping-cost";
import MinimumWageProvince from "./calcs/calcs_batch_4_minimum-wage-province";
import SeverancePayCalculation from "./calcs/calcs_batch_4_severance-pay-calculation";
import WarehouseRentVsBuy from "./calcs/calcs_batch_4_warehouse-rent-vs-buy";
import AcceptableCPCCalculator from "./calcs/calcs_batch_5_acceptable-cpc";
import CAGRCalculator from "./calcs/calcs_batch_5_cagr";
import FactoryElectricityCalculator from "./calcs/calcs_batch_5_factory-electricity";
import FranchiseCostCalculator from "./calcs/calcs_batch_5_franchise-cost";
import GrossMarginSkuCalculator from "./calcs/calcs_batch_5_gross-margin-sku";
import NPSCalculator from "./calcs/calcs_batch_5_nps";
import RealEstateBrokerFeeCalculator from "./calcs/calcs_batch_5_real-estate-broker-fee";
import ReturnRateImpactCalculator from "./calcs/calcs_batch_5_return-rate-impact";
import ROASCalculator from "./calcs/calcs_batch_5_roas";
import SaasMrrArrCalculator from "./calcs/calcs_batch_5_saas-mrr-arr";
import { LenormandCalculator, OracleCalculator, PlayingCardCalculator, KipperCalculator } from "./calcs/CardReadingCalcs";
import EWasteWaterFootprint from "./calcs/calcs_batch_10_e-waste-water-footprint";
import EVChargerInstallationCost from "./calcs/calcs_batch_10_ev-charger-installation-cost";
import EVChargingCost from "./calcs/calcs_batch_10_ev-charging-cost";
import GreenBuildingScore from "./calcs/calcs_batch_10_green-building-score";
import LEDSavingsCalculator from "./calcs/calcs_batch_10_led-savings";
import LivestockMethaneEmissions from "./calcs/calcs_batch_10_livestock-methane-emissions";
import PersonalEcologicalFootprint from "./calcs/calcs_batch_10_personal-ecological-footprint";
import RenewableVsGridElectricity from "./calcs/calcs_batch_10_renewable-vs-grid-electricity";
import SolarPaybackPeriodCalculator from "./calcs/calcs_batch_10_solar-payback-period";
import TreeCO2OffsetCalculator from "./calcs/calcs_batch_10_tree-co2-offset";
import AppDevCostCalculator from "./calcs/calcs_batch_11_app-dev-cost";
import AppStoreRevenueCalculator from "./calcs/calcs_batch_11_app-store-revenue";
import CdnCostCalculator from "./calcs/calcs_batch_11_cdn-cost-calculator";
import CloudStorageCostCalculator from "./calcs/calcs_batch_11_cloud-storage-cost";
import DatabaseCostCalculator from "./calcs/calcs_batch_11_database-cost";
import FacebookAdsRoiCalculator from "./calcs/calcs_batch_11_facebook-ads-roi-cpa";
import GoogleAdsRoiCalculator from "./calcs/calcs_batch_11_google-ads-roi-roas";
import LtvCacRatioCalculator from "./calcs/calcs_batch_11_ltv-to-cac-ratio";
import SmsEmailCostCalculator from "./calcs/calcs_batch_11_sms-email-marketing-cost";
import VpsDedicatedCostCalculator from "./calcs/calcs_batch_11_vps-dedicated-cost";
import CroRevenueImpactCalculator from "./calcs/calcs_batch_12_cro-revenue-impact-calculator";
import DomainHostingCostCalculator from "./calcs/calcs_batch_12_domain-hosting-cost-calculator";
import EmailDeliverabilityScoreCalculator from "./calcs/calcs_batch_12_email-deliverability-score-calculator";
import EmailRevenueCalculator from "./calcs/calcs_batch_12_email-revenue-calculator";
import PwaVsNativeAppCostCalculator from "./calcs/calcs_batch_12_pwa-vs-native-app-cost-calculator";
import SaasStackTotalCostCalculator from "./calcs/calcs_batch_12_saas-stack-total-cost-calculator";
import SeoValueCalculator from "./calcs/calcs_batch_12_seo-value-calculator";
import SmeCybersecurityCostCalculator from "./calcs/calcs_batch_12_sme-cybersecurity-cost-calculator";
import SslCertificateCostCalculator from "./calcs/calcs_batch_12_ssl-certificate-cost-calculator";
import TechnicalDebtCostCalculator from "./calcs/calcs_batch_12_technical-debt-cost-calculator";
import ACElectricityCost from "./calcs/calcs_batch_13_ac-electricity-cost";
import BuiltInKitchenCost from "./calcs/calcs_batch_13_built-in-kitchen-cost";
import CondoMaintenanceFeeTotal from "./calcs/calcs_batch_13_condo-maintenance-fee-total";
import CondoPurchaseCost from "./calcs/calcs_batch_13_condo-purchase-cost";
import CondoRentVsBuyToLetROI from "./calcs/calcs_batch_13_condo-rent-vs-buy-to-let-roi";
import FullHouseFurnitureCost from "./calcs/calcs_batch_13_full-house-furniture-cost";
import MovingHouseCost from "./calcs/calcs_batch_13_moving-house-cost";
import NewHousePurchaseCost from "./calcs/calcs_batch_13_new-house-purchase-cost";
import PropertyTaxCalculator from "./calcs/calcs_batch_13_property-tax-calculator";
import RentalYieldCalculator from "./calcs/calcs_batch_13_rental-yield-calculator";
import AcBtuSizeCalculator from "./calcs/calcs_batch_14_ac-btu-size-calculator";
import ApplianceElectricityCost from "./calcs/calcs_batch_14_appliance-electricity-cost";
import GardenMaintenanceCost from "./calcs/calcs_batch_14_garden-maintenance-cost";
import HomeInternetCost from "./calcs/calcs_batch_14_home-internet-cost";
import HomeSecurityCost from "./calcs/calcs_batch_14_home-security-cost";
import HomeSolarInstallationCost from "./calcs/calcs_batch_14_home-solar-installation-cost";
import HousePaintingCost from "./calcs/calcs_batch_14_house-painting-cost";
import HouseholdWaterUsageCost from "./calcs/calcs_batch_14_household-water-usage-cost";
import PoolMaintenanceCost from "./calcs/calcs_batch_14_pool-maintenance-cost";
import RoofReplacementCost from "./calcs/calcs_batch_14_roof-replacement-cost";
import CarComparisonCalculator from "./calcs/calcs_batch_15_car-comparison";
import CarDepreciationCalculator from "./calcs/calcs_batch_15_car-depreciation";
import CarInsuranceCalculator from "./calcs/calcs_batch_15_car-insurance";
import CarMaintenanceCalculator from "./calcs/calcs_batch_15_car-maintenance";
import CarTcoCalculator from "./calcs/calcs_batch_15_car-tco";
import EvCostPerKmCalculator from "./calcs/calcs_batch_15_ev-cost-per-km";
import EvIceBreakevenCalculator from "./calcs/calcs_batch_15_ev-ice-breakeven";
import MotorcycleLoanCalculator from "./calcs/calcs_batch_15_motorcycle-loan";
import RiderRoiCalculator from "./calcs/calcs_batch_15_rider-roi";
import TruckCostCalculator from "./calcs/calcs_batch_15_truck-cost";
import AnnualCommuteCalculator from "./calcs/calcs_batch_16_annual-commute-cost-calculator";
import CarPoolCalculator from "./calcs/calcs_batch_16_car-pool-savings-calculator";
import MonthlyParkingCalculator from "./calcs/calcs_batch_16_monthly-parking-cost-calculator";
import TollFeeCalculator from "./calcs/calcs_batch_16_monthly-toll-fee-calculator";
import RideHailingVsOwnCarCalculator from "./calcs/calcs_batch_16_ride-hailing-vs-own-car-cost-calculator";
import BreakEvenTime1 from "./calcs/calcs_batch_1_break-even-time";
import CapacityUtilizationRate1 from "./calcs/calcs_batch_1_capacity-utilization-rate";
import CashFlowProjection1 from "./calcs/calcs_batch_1_cash-flow-projection";
import CostPerUnit1 from "./calcs/calcs_batch_1_cost-per-unit";
import DoubleDecliningDepreciation1 from "./calcs/calcs_batch_1_double-declining-depreciation";
import WorkingCapital1 from "./calcs/calcs_batch_1_working-capital";
import WholesaleVsRetailMargin1 from "./calcs/calcs_batch_1_wholesale-vs-retail-margin";
import RetailSpaceRentRoi1 from "./calcs/calcs_batch_1_retail-space-rent-roi";
import SimplifiedPL1 from "./calcs/calcs_batch_1_simplified-p-and-l";
import FreelanceVsFulltimeCost1 from "./calcs/calcs_batch_1_freelance-vs-fulltime-cost";
import CompanyRegistrationCost1 from "./calcs/calcs_batch_2_company-registration-cost";
import CorporateTaxCalculator1 from "./calcs/calcs_batch_2_corporate-tax";
import CreditCardMdrFee1 from "./calcs/calcs_batch_2_credit-card-mdr-fee";
import DeRatio1 from "./calcs/calcs_batch_2_de-ratio";
import LegalReserveCalculator1 from "./calcs/calcs_batch_2_legal-reserve";
import MarkupImportedMaterials1 from "./calcs/calcs_batch_2_markup-imported-materials";
import PosSystemComparison1 from "./calcs/calcs_batch_2_pos-system-comparison";
import QuickCurrentRatio1 from "./calcs/calcs_batch_2_quick-current-ratio";
import RoeRoaRoic1 from "./calcs/calcs_batch_2_roe-roa-roic";
import SalesCommissionStructure1 from "./calcs/calcs_batch_2_sales-commission-structure";
import AdvertisingBudgetAllocation1 from "./calcs/calcs_batch_4_advertising-budget-allocation";
import CacPaybackPeriod1 from "./calcs/calcs_batch_4_cac-payback-period";
import EbitdaCalculator1 from "./calcs/calcs_batch_4_ebitda-calculator";
import EmployeeOtCalculation1 from "./calcs/calcs_batch_4_employee-ot-calculation";
import EmployerSocialSecurity1 from "./calcs/calcs_batch_4_employer-social-security";
import FxForwardRateRisk1 from "./calcs/calcs_batch_4_fx-forward-rate-risk";
import InternationalShippingCost1 from "./calcs/calcs_batch_4_international-shipping-cost";
import MinimumWageProvince1 from "./calcs/calcs_batch_4_minimum-wage-province";
import SeverancePayCalculation1 from "./calcs/calcs_batch_4_severance-pay-calculation";
import WarehouseRentVsBuy1 from "./calcs/calcs_batch_4_warehouse-rent-vs-buy";
import AcceptableCPCCalculator1 from "./calcs/calcs_batch_5_acceptable-cpc";
import CAGRCalculator1 from "./calcs/calcs_batch_5_cagr";
import FactoryElectricityCalculator1 from "./calcs/calcs_batch_5_factory-electricity";
import FranchiseCostCalculator1 from "./calcs/calcs_batch_5_franchise-cost";
import GrossMarginSkuCalculator1 from "./calcs/calcs_batch_5_gross-margin-sku";
import NPSCalculator1 from "./calcs/calcs_batch_5_nps";
import RealEstateBrokerFeeCalculator1 from "./calcs/calcs_batch_5_real-estate-broker-fee";
import ReturnRateImpactCalculator1 from "./calcs/calcs_batch_5_return-rate-impact";
import ROASCalculator1 from "./calcs/calcs_batch_5_roas";
import SaasMrrArrCalculator1 from "./calcs/calcs_batch_5_saas-mrr-arr";
import BananaFarmingCalculator from "./calcs/calcs_batch_7_banana-farming-calculator";
import BroilerChickenFarmCalculator from "./calcs/calcs_batch_7_broiler-chicken-farm-calculator";
import CassavaFarmingCalculator from "./calcs/calcs_batch_7_cassava-farming-calculator";
import CoconutFarmingCalculator from "./calcs/calcs_batch_7_coconut-farming-calculator";
import CornFarmingCalculator from "./calcs/calcs_batch_7_corn-farming-calculator";
import MangoFarmingCalculator from "./calcs/calcs_batch_7_mango-farming-calculator";
import OilPalmFarmingCalculator from "./calcs/calcs_batch_7_oil-palm-farming-calculator";
import RubberTreeFarmingCalculator from "./calcs/calcs_batch_7_rubber-tree-farming-calculator";
import SugarcaneFarmingCalculator from "./calcs/calcs_batch_7_sugarcane-farming-calculator";
import WhiteShrimpFarmCalculator from "./calcs/calcs_batch_7_white-shrimp-farm-calculator";
import AgriChemicalMixRatio from "./calcs/calcs_batch_8_agri-chemical-mix-ratio";
import BeefCattleFarmProfitCost from "./calcs/calcs_batch_8_beef-cattle-farm-profit-cost";
import DripIrrigationCost from "./calcs/calcs_batch_8_drip-irrigation-cost";
import FarmAreaFromGps from "./calcs/calcs_batch_8_farm-area-from-gps";
import FarmBreakEvenYield from "./calcs/calcs_batch_8_farm-break-even-yield";
import FarmLaborCostPerRai from "./calcs/calcs_batch_8_farm-labor-cost-per-rai";
import LayerChickenFarmProfitCost from "./calcs/calcs_batch_8_layer-chicken-farm-profit-cost";
import PigFarmProfitCost from "./calcs/calcs_batch_8_pig-farm-profit-cost";
import SeedsPerRaiCalculator from "./calcs/calcs_batch_8_seeds-per-rai-calculator";
import TractorRentVsBuy from "./calcs/calcs_batch_8_tractor-rent-vs-buy";
import FarmLandRentRoi from "./calcs/calcs_batch_9_farm-land-rent-roi";
import FoodCarbonFootprint from "./calcs/calcs_batch_9_food-carbon-footprint";
import FreshToDryWeight from "./calcs/calcs_batch_9_fresh-to-dry-weight";
import GerminationRate from "./calcs/calcs_batch_9_germination-rate";
import HarvestTime from "./calcs/calcs_batch_9_harvest-time";
import MillStorageElectricity from "./calcs/calcs_batch_9_mill-storage-electricity";
import ProductWaterFootprint from "./calcs/calcs_batch_9_product-water-footprint";
import RecycledWasteImpact from "./calcs/calcs_batch_9_recycled-waste-impact";
import TravelCarbonFootprint from "./calcs/calcs_batch_9_travel-carbon-footprint";
import WaterSavingImpact from "./calcs/calcs_batch_9_water-saving-impact";
import EWasteWaterFootprintBatch10 from "./calcs/calcs_batch_10_e-waste-water-footprint";
import EVChargerInstallationCostBatch10 from "./calcs/calcs_batch_10_ev-charger-installation-cost";
import EVChargingCostBatch10 from "./calcs/calcs_batch_10_ev-charging-cost";
import GreenBuildingScoreBatch10 from "./calcs/calcs_batch_10_green-building-score";
import LEDSavingsCalculatorBatch10 from "./calcs/calcs_batch_10_led-savings";
import LivestockMethaneEmissionsBatch10 from "./calcs/calcs_batch_10_livestock-methane-emissions";
import PersonalEcologicalFootprintBatch10 from "./calcs/calcs_batch_10_personal-ecological-footprint";
import RenewableVsGridElectricityBatch10 from "./calcs/calcs_batch_10_renewable-vs-grid-electricity";
import SolarPaybackPeriodCalculatorBatch10 from "./calcs/calcs_batch_10_solar-payback-period";
import TreeCO2OffsetCalculatorBatch10 from "./calcs/calcs_batch_10_tree-co2-offset";
import AppDevCostCalculatorBatch11 from "./calcs/calcs_batch_11_app-dev-cost";
import AppStoreRevenueCalculatorBatch11 from "./calcs/calcs_batch_11_app-store-revenue";
import CdnCostCalculatorBatch11 from "./calcs/calcs_batch_11_cdn-cost-calculator";
import CloudStorageCostCalculatorBatch11 from "./calcs/calcs_batch_11_cloud-storage-cost";
import DatabaseCostCalculatorBatch11 from "./calcs/calcs_batch_11_database-cost";
import FacebookAdsRoiCalculatorBatch11 from "./calcs/calcs_batch_11_facebook-ads-roi-cpa";
import GoogleAdsRoiCalculatorBatch11 from "./calcs/calcs_batch_11_google-ads-roi-roas";
import LtvCacRatioCalculatorBatch11 from "./calcs/calcs_batch_11_ltv-to-cac-ratio";
import SmsEmailCostCalculatorBatch11 from "./calcs/calcs_batch_11_sms-email-marketing-cost";
import VpsDedicatedCostCalculatorBatch11 from "./calcs/calcs_batch_11_vps-dedicated-cost";
import CroRevenueImpactCalculatorBatch12 from "./calcs/calcs_batch_12_cro-revenue-impact-calculator";
import DomainHostingCostCalculatorBatch12 from "./calcs/calcs_batch_12_domain-hosting-cost-calculator";
import EmailDeliverabilityScoreCalculatorBatch12 from "./calcs/calcs_batch_12_email-deliverability-score-calculator";
import EmailRevenueCalculatorBatch12 from "./calcs/calcs_batch_12_email-revenue-calculator";
import PwaVsNativeAppCostCalculatorBatch12 from "./calcs/calcs_batch_12_pwa-vs-native-app-cost-calculator";
import SaasStackTotalCostCalculatorBatch12 from "./calcs/calcs_batch_12_saas-stack-total-cost-calculator";
import SeoValueCalculatorBatch12 from "./calcs/calcs_batch_12_seo-value-calculator";
import SmeCybersecurityCostCalculatorBatch12 from "./calcs/calcs_batch_12_sme-cybersecurity-cost-calculator";
import SslCertificateCostCalculatorBatch12 from "./calcs/calcs_batch_12_ssl-certificate-cost-calculator";
import TechnicalDebtCostCalculatorBatch12 from "./calcs/calcs_batch_12_technical-debt-cost-calculator";
import ACElectricityCostBatch13 from "./calcs/calcs_batch_13_ac-electricity-cost";
import BuiltInKitchenCostBatch13 from "./calcs/calcs_batch_13_built-in-kitchen-cost";
import CondoMaintenanceFeeTotalBatch13 from "./calcs/calcs_batch_13_condo-maintenance-fee-total";
import CondoPurchaseCostBatch13 from "./calcs/calcs_batch_13_condo-purchase-cost";
import CondoRentVsBuyToLetROIBatch13 from "./calcs/calcs_batch_13_condo-rent-vs-buy-to-let-roi";
import FullHouseFurnitureCostBatch13 from "./calcs/calcs_batch_13_full-house-furniture-cost";
import MovingHouseCostBatch13 from "./calcs/calcs_batch_13_moving-house-cost";
import NewHousePurchaseCostBatch13 from "./calcs/calcs_batch_13_new-house-purchase-cost";
import PropertyTaxCalculatorBatch13 from "./calcs/calcs_batch_13_property-tax-calculator";
import RentalYieldCalculatorBatch13 from "./calcs/calcs_batch_13_rental-yield-calculator";
import AcBtuSizeCalculatorBatch14 from "./calcs/calcs_batch_14_ac-btu-size-calculator";
import ApplianceElectricityCostBatch14 from "./calcs/calcs_batch_14_appliance-electricity-cost";
import GardenMaintenanceCostBatch14 from "./calcs/calcs_batch_14_garden-maintenance-cost";
import HomeInternetCostBatch14 from "./calcs/calcs_batch_14_home-internet-cost";
import HomeSecurityCostBatch14 from "./calcs/calcs_batch_14_home-security-cost";
import HomeSolarInstallationCostBatch14 from "./calcs/calcs_batch_14_home-solar-installation-cost";
import HousePaintingCostBatch14 from "./calcs/calcs_batch_14_house-painting-cost";
import HouseholdWaterUsageCostBatch14 from "./calcs/calcs_batch_14_household-water-usage-cost";
import PoolMaintenanceCostBatch14 from "./calcs/calcs_batch_14_pool-maintenance-cost";
import RoofReplacementCostBatch14 from "./calcs/calcs_batch_14_roof-replacement-cost";
import CarComparisonCalculatorBatch15 from "./calcs/calcs_batch_15_car-comparison";
import CarDepreciationCalculatorBatch15 from "./calcs/calcs_batch_15_car-depreciation";
import CarInsuranceCalculatorBatch15 from "./calcs/calcs_batch_15_car-insurance";
import CarMaintenanceCalculatorBatch15 from "./calcs/calcs_batch_15_car-maintenance";
import CarTcoCalculatorBatch15 from "./calcs/calcs_batch_15_car-tco";
import EvCostPerKmCalculatorBatch15 from "./calcs/calcs_batch_15_ev-cost-per-km";
import EvIceBreakevenCalculatorBatch15 from "./calcs/calcs_batch_15_ev-ice-breakeven";
import MotorcycleLoanCalculatorBatch15 from "./calcs/calcs_batch_15_motorcycle-loan";
import RiderRoiCalculatorBatch15 from "./calcs/calcs_batch_15_rider-roi";
import TruckCostCalculatorBatch15 from "./calcs/calcs_batch_15_truck-cost";
import AnnualCommuteCalculatorBatch16 from "./calcs/calcs_batch_16_annual-commute-cost-calculator";
import CarPoolCalculatorBatch16 from "./calcs/calcs_batch_16_car-pool-savings-calculator";
import MonthlyParkingCalculatorBatch16 from "./calcs/calcs_batch_16_monthly-parking-cost-calculator";
import TollFeeCalculatorBatch16 from "./calcs/calcs_batch_16_monthly-toll-fee-calculator";
import RideHailingVsOwnCarCalculatorBatch16 from "./calcs/calcs_batch_16_ride-hailing-vs-own-car-cost-calculator";
import AnniversaryCountdown from "./calcs/calcs_batch_17_anniversary-countdown";
import EventCountdown from "./calcs/calcs_batch_17_event-countdown";
import ExactAgeCalculator from "./calcs/calcs_batch_17_exact-age-calculator";
import RetirementCountdown from "./calcs/calcs_batch_17_retirement-countdown";
import SunriseSunsetCalculator from "./calcs/calcs_batch_17_sunrise-sunset-calculator";
import ThaiLunarPhase from "./calcs/calcs_batch_17_thai-lunar-phase";
import FontSizeReadingDistance from "./calcs/calcs_batch_18_font-size-reading-distance";
import RemainingAnnualLeave from "./calcs/calcs_batch_18_remaining-annual-leave";
import ShiftWorkStaffing from "./calcs/calcs_batch_18_shift-work-staffing";
import SocialMediaImageSize from "./calcs/calcs_batch_18_social-media-image-size";
import CustomsBrokerFeeCalculator from "./calcs/calcs_batch_19_customs-broker-fee";
import HsCodeImportTaxCalculator from "./calcs/calcs_batch_19_hs-code-import-tax";
import ImportCustomsDutyCalculator from "./calcs/calcs_batch_19_import-customs-duty";
import SolarBatterySizing from "./calcs/calcs_batch_20_solar-battery-sizing";
import SolarInverterSizing from "./calcs/calcs_batch_20_solar-inverter-sizing";
import TouElectricityCost from "./calcs/calcs_batch_20_tou-electricity-cost";
import CostOfLivingComparison from "./calcs/calcs_batch_21_cost-of-living-comparison";
import QalyCalculator from "./calcs/calcs_batch_21_qaly-calculator";
import MetcalfeNetworkValue from "./calcs/calcs_batch_22_metcalfe-network-value";
import OnlineCourseRoi from "./calcs/calcs_batch_22_online-course-roi";
import ViralCoefficient from "./calcs/calcs_batch_22_viral-coefficient";
import AutomationROI from "./calcs/calcs_batch_23_automation-roi";
import BrooksLawTeamSize from "./calcs/calcs_batch_23_brooks-law-team-size";
import NoiseLevelDb from "./calcs/calcs_batch_24_noise-level-db";
import SoundInsulation from "./calcs/calcs_batch_24_sound-insulation";
import FlowStateFrequency from "./calcs/calcs_batch_25_flow-state-frequency";
import BananaFarmingCalculatorBatch7 from "./calcs/calcs_batch_7_banana-farming-calculator";
import BroilerChickenFarmCalculatorBatch7 from "./calcs/calcs_batch_7_broiler-chicken-farm-calculator";
import CassavaFarmingCalculatorBatch7 from "./calcs/calcs_batch_7_cassava-farming-calculator";
import CoconutFarmingCalculatorBatch7 from "./calcs/calcs_batch_7_coconut-farming-calculator";
import CornFarmingCalculatorBatch7 from "./calcs/calcs_batch_7_corn-farming-calculator";
import MangoFarmingCalculatorBatch7 from "./calcs/calcs_batch_7_mango-farming-calculator";
import OilPalmFarmingCalculatorBatch7 from "./calcs/calcs_batch_7_oil-palm-farming-calculator";
import RubberTreeFarmingCalculatorBatch7 from "./calcs/calcs_batch_7_rubber-tree-farming-calculator";
import SugarcaneFarmingCalculatorBatch7 from "./calcs/calcs_batch_7_sugarcane-farming-calculator";
import WhiteShrimpFarmCalculatorBatch7 from "./calcs/calcs_batch_7_white-shrimp-farm-calculator";
import AgriChemicalMixRatioBatch8 from "./calcs/calcs_batch_8_agri-chemical-mix-ratio";
import BeefCattleFarmProfitCostBatch8 from "./calcs/calcs_batch_8_beef-cattle-farm-profit-cost";
import DripIrrigationCostBatch8 from "./calcs/calcs_batch_8_drip-irrigation-cost";
import FarmAreaFromGpsBatch8 from "./calcs/calcs_batch_8_farm-area-from-gps";
import FarmBreakEvenYieldBatch8 from "./calcs/calcs_batch_8_farm-break-even-yield";
import FarmLaborCostPerRaiBatch8 from "./calcs/calcs_batch_8_farm-labor-cost-per-rai";
import LayerChickenFarmProfitCostBatch8 from "./calcs/calcs_batch_8_layer-chicken-farm-profit-cost";
import PigFarmProfitCostBatch8 from "./calcs/calcs_batch_8_pig-farm-profit-cost";
import SeedsPerRaiCalculatorBatch8 from "./calcs/calcs_batch_8_seeds-per-rai-calculator";
import TractorRentVsBuyBatch8 from "./calcs/calcs_batch_8_tractor-rent-vs-buy";
import FarmLandRentRoiBatch9 from "./calcs/calcs_batch_9_farm-land-rent-roi";
import FoodCarbonFootprintBatch9 from "./calcs/calcs_batch_9_food-carbon-footprint";
import FreshToDryWeightBatch9 from "./calcs/calcs_batch_9_fresh-to-dry-weight";
import GerminationRateBatch9 from "./calcs/calcs_batch_9_germination-rate";
import HarvestTimeBatch9 from "./calcs/calcs_batch_9_harvest-time";
import MillStorageElectricityBatch9 from "./calcs/calcs_batch_9_mill-storage-electricity";
import ProductWaterFootprintBatch9 from "./calcs/calcs_batch_9_product-water-footprint";
import RecycledWasteImpactBatch9 from "./calcs/calcs_batch_9_recycled-waste-impact";
import TravelCarbonFootprintBatch9 from "./calcs/calcs_batch_9_travel-carbon-footprint";
import WaterSavingImpactBatch9 from "./calcs/calcs_batch_9_water-saving-impact";

export function Calculators({ activeCalc, lang, setCalc }: { activeCalc: string, lang: Lang, setCalc: (id: string) => void }) {
  if (activeCalc === "dio") return <DIOCalculator lang={lang} />;
  if (activeCalc === "dso") return <DSOCalculator lang={lang} />;
  if (activeCalc === "employee-bonus") return <EmployeeBonusCalculator lang={lang} />;
  if (activeCalc === "expense-ratio") return <ExpenseRatioCalculator lang={lang} />;
  if (activeCalc === "gmv-vs-net-revenue") return <GMVCalculator lang={lang} />;
  if (activeCalc === "headcount-to-sales") return <HeadcountToSalesCalculator lang={lang} />;
  if (activeCalc === "inventory-costing") return <InventoryCostingCalculator lang={lang} />;
  if (activeCalc === "landed-cost") return <LandedCostCalculator lang={lang} />;
  if (activeCalc === "office-vs-wfh") return <OfficeVsWfhCalculator lang={lang} />;
  if (activeCalc === "packaging-cost") return <PackagingCostCalculator lang={lang} />;
  if (activeCalc === "break-even-by-channel") return <BreakEvenChannelCalculator lang={lang} />;
  if (activeCalc === "carbon-credit-cost") return <CarbonCreditCostCalculator lang={lang} />;
  if (activeCalc === "event-cost-per-attendee") return <EventCostCalculator lang={lang} />;
  if (activeCalc === "iso-certification-cost") return <IsoCertificationCostCalculator lang={lang} />;
  if (activeCalc === "npv-irr") return <NpvIrrCalculator lang={lang} />;
  if (activeCalc === "patent-cost") return <PatentCostCalculator lang={lang} />;
  if (activeCalc === "project-payback-period") return <ProjectPaybackPeriodCalculator lang={lang} />;
  if (activeCalc === "royalty-income") return <RoyaltyIncomeCalculator lang={lang} />;
  if (activeCalc === "sensitivity-analysis") return <SensitivityAnalysisCalculator lang={lang} />;
  if (activeCalc === "space-rental-deposit") return <SpaceRentalDepositCalculator lang={lang} />;
  if (activeCalc === "break-even-time") return <BreakEvenTime lang={lang} />;
  if (activeCalc === "capacity-utilization-rate") return <CapacityUtilizationRate lang={lang} />;
  if (activeCalc === "cash-flow-projection") return <CashFlowProjection lang={lang} />;
  if (activeCalc === "cost-per-unit") return <CostPerUnit lang={lang} />;
  if (activeCalc === "double-declining-depreciation") return <DoubleDecliningDepreciation lang={lang} />;
  if (activeCalc === "freelance-vs-fulltime-cost") return <FreelanceVsFulltimeCost lang={lang} />;
  if (activeCalc === "retail-space-rent-roi") return <RetailSpaceRentRoi lang={lang} />;
  if (activeCalc === "simplified-p-and-l") return <SimplifiedPL lang={lang} />;
  if (activeCalc === "wholesale-vs-retail-margin") return <WholesaleVsRetailMargin lang={lang} />;
  if (activeCalc === "working-capital") return <WorkingCapital lang={lang} />;
  if (activeCalc === "company-registration-cost") return <CompanyRegistrationCost lang={lang} />;
  if (activeCalc === "corporate-tax") return <CorporateTaxCalculator lang={lang} />;
  if (activeCalc === "credit-card-mdr-fee") return <CreditCardMdrFee lang={lang} />;
  if (activeCalc === "de-ratio") return <DeRatio lang={lang} />;
  if (activeCalc === "legal-reserve") return <LegalReserveCalculator lang={lang} />;
  if (activeCalc === "markup-imported-materials") return <MarkupImportedMaterials lang={lang} />;
  if (activeCalc === "pos-system-comparison") return <PosSystemComparison lang={lang} />;
  if (activeCalc === "quick-current-ratio") return <QuickCurrentRatio lang={lang} />;
  if (activeCalc === "roe-roa-roic") return <RoeRoaRoic lang={lang} />;
  if (activeCalc === "sales-commission-structure") return <SalesCommissionStructure lang={lang} />;
  if (activeCalc === "advertising-budget-allocation") return <AdvertisingBudgetAllocation lang={lang} />;
  if (activeCalc === "cac-payback-period") return <CacPaybackPeriod lang={lang} />;
  if (activeCalc === "ebitda-calculator") return <EbitdaCalculator lang={lang} />;
  if (activeCalc === "employee-ot-calculation") return <EmployeeOtCalculation lang={lang} />;
  if (activeCalc === "employer-social-security") return <EmployerSocialSecurity lang={lang} />;
  if (activeCalc === "fx-forward-rate-risk") return <FxForwardRateRisk lang={lang} />;
  if (activeCalc === "international-shipping-cost") return <InternationalShippingCost lang={lang} />;
  if (activeCalc === "minimum-wage-province") return <MinimumWageProvince lang={lang} />;
  if (activeCalc === "severance-pay-calculation") return <SeverancePayCalculation lang={lang} />;
  if (activeCalc === "warehouse-rent-vs-buy") return <WarehouseRentVsBuy lang={lang} />;
  if (activeCalc === "acceptable-cpc") return <AcceptableCPCCalculator lang={lang} />;
  if (activeCalc === "cagr") return <CAGRCalculator lang={lang} />;
  if (activeCalc === "factory-electricity") return <FactoryElectricityCalculator lang={lang} />;
  if (activeCalc === "franchise-cost") return <FranchiseCostCalculator lang={lang} />;
  if (activeCalc === "gross-margin-sku") return <GrossMarginSkuCalculator lang={lang} />;
  if (activeCalc === "nps") return <NPSCalculator lang={lang} />;
  if (activeCalc === "real-estate-broker-fee") return <RealEstateBrokerFeeCalculator lang={lang} />;
  if (activeCalc === "return-rate-impact") return <ReturnRateImpactCalculator lang={lang} />;
  if (activeCalc === "roas") return <ROASCalculator lang={lang} />;
  if (activeCalc === "saas-mrr-arr") return <SaasMrrArrCalculator lang={lang} />;
  // Health & Diet
  if (activeCalc === "bmi") return <BMICalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "sleep") return <SleepCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "tdee") return <TDEECalculator lang={lang} />;
  if (activeCalc === "water-intake") return <HealthWaterCalculator lang={lang} />;
  if (activeCalc === "food-random") return <FoodRandomizer lang={lang} />;
  if (activeCalc === "exercise-calories") return <ExerciseCaloriesCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "protein-daily") return <ProteinCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "body-fat") return <BodyFatCalculator lang={lang} />;
  if (activeCalc === "whr") return <WHRCalculator lang={lang} />;
  if (activeCalc === "heart-rate-zone") return <HeartRateZoneCalculator lang={lang} />;
  if (activeCalc === "macro") return <MacroCalculator lang={lang} />;
  if (activeCalc === "blood-sugar") return <BloodSugarConverter lang={lang} />;
  if (activeCalc === "ibw") return <IBWCalculator lang={lang} />;
  if (activeCalc === "steps-converter") return <StepsCalculator lang={lang} />;
  if (activeCalc === "1rm") return <OneRepMaxCalculator lang={lang} />;
  if (activeCalc === "pace") return <PaceCalculator lang={lang} />;
  if (activeCalc === "vo2-max") return <VO2MaxCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "swim-pace") return <SwimPaceCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "cycling-power") return <CyclingPowerZones lang={lang} setCalc={setCalc} />;
  if (activeCalc === "race-predictor") return <RacePredictor lang={lang} setCalc={setCalc} />;
  if (activeCalc === "lifting-pyramid") return <LiftingPyramid lang={lang} setCalc={setCalc} />;
  if (activeCalc === "rowing-split") return <RowingSplit lang={lang} setCalc={setCalc} />;
  if (activeCalc === "carb-endurance") return <CarbEnduranceCalc lang={lang} setCalc={setCalc} />;
  if (activeCalc === "fiber-intake") return <FiberCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "vitamin-d") return <VitaminDCalculator lang={lang} setCalc={setCalc} />;

  if (activeCalc === "bmi-kids") return <BMIKidsCalculator lang={lang} setCalc={setCalc} />;

  // Family
  if (activeCalc === "child-height") return <ChildHeightCalculator lang={lang} />;
  if (activeCalc === "pregnancy-due") return <PregnancyDueCalculator lang={lang} />;
  if (activeCalc === "ovulation") return <OvulationCalculator lang={lang} />;
  if (activeCalc === "blood-type") return <BloodTypePredictor lang={lang} />;
  if (activeCalc === "zodiac") return <ZodiacCalculator lang={lang} />;
  if (activeCalc === "pet-age") return <PetAgeCalculator lang={lang} />;
  if (activeCalc === "fetal-weight") return <FetalWeightCalculator lang={lang} />;
  if (activeCalc === "child-cost") return <ChildCostCalculator lang={lang} />;
  if (activeCalc === "child-milestone") return <ChildMilestoneCalculator lang={lang} />;
  if (activeCalc === "horoscope") return <HoroscopeCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "tarot") return <TarotReadingCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "lenormand") return <LenormandCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "oracle") return <OracleCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "playing-card") return <PlayingCardCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "kipper") return <KipperCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "gold-price") return <GoldPriceCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "wedding-budget") return <WeddingBudget lang={lang} setCalc={setCalc} />;
  if (activeCalc === "newborn-cost") return <NewbornCost lang={lang} setCalc={setCalc} />;
  if (activeCalc === "pet-cost") return <PetCost lang={lang} setCalc={setCalc} />;
  if (activeCalc === "food-expiration") return <FoodExpiration lang={lang} setCalc={setCalc} />;
  if (activeCalc === "rent-vs-buy") return <RentVsBuyCalc lang={lang} setCalc={setCalc} />;
  
  // Travel
  if (activeCalc === "time-zone") return <TimeZoneConverter lang={lang} />;
  if (activeCalc === "travel-budget") return <TravelBudgetCalculator lang={lang} />;
  if (activeCalc === "flight-time") return <FlightTimeCalculator lang={lang} />;
  if (activeCalc === "packing-list") return <PackingListGenerator lang={lang} />;
  if (activeCalc === "road-trip") return <RoadTripCostCalculator lang={lang} />;
  if (activeCalc === "baggage-weight") return <BaggageWeightChecker lang={lang} />;

  // Finance
  if (activeCalc === "discount") return <DiscountCalculator lang={lang} />;
  if (activeCalc === "car-loan") return <CarLoanCalculator lang={lang} />;
  if (activeCalc === "mortgage") return <MortgageCalculator lang={lang} />;
  if (activeCalc === "compound-interest") return <CompoundInterest lang={lang} />;
  if (activeCalc === "bill-splitter") return <BillSplitter lang={lang} />;
  if (activeCalc === "currency-converter") return <CurrencyConverter lang={lang} />;
  if (activeCalc === "savings-goal") return <SavingsGoalCalculator lang={lang} />;
  if (activeCalc === "inflation") return <InflationCalculator lang={lang} />;
  if (activeCalc === "salary-hourly") return <SalaryToHourlyCalculator lang={lang} />;
  if (activeCalc === "net-worth") return <NetWorthCalculator lang={lang} />;
  if (activeCalc === "debt-payoff") return <DebtPayoffCalculator lang={lang} />;
  if (activeCalc === "retirement") return <RetirementCalculator lang={lang} />;
  if (activeCalc === "stock-profit") return <StockProfitCalculator lang={lang} />;
  if (activeCalc === "roi") return <ROICalculator lang={lang} />;
  if (activeCalc === "dca") return <DCACalculator lang={lang} />;
  if (activeCalc === "stock-fee") return <StockFeeCalculator lang={lang} />;
  if (activeCalc === "net-salary") return <NetSalaryCalculator lang={lang} />;
  if (activeCalc === "personal-tax") return <PersonalTaxCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "expense-tracker") return <ExpenseTrackerCalculator lang={lang} />;

  // Business
  if (activeCalc === "vat") return <VatCalculator lang={lang} />;
  if (activeCalc === "margin") return <MarginCalculator lang={lang} />;
  if (activeCalc === "break-even") return <BreakEvenCalculator lang={lang} />;
  if (activeCalc === "markup") return <MarkupCalculator lang={lang} />;
  if (activeCalc === "depreciation") return <DepreciationCalculator lang={lang} />;
  if (activeCalc === "payroll") return <PayrollCalculator lang={lang} />;
  if (activeCalc === "cogs") return <COGSCalculator lang={lang} />;
  if (activeCalc === "ltv") return <LTVCalculator lang={lang} />;
  if (activeCalc === "cac") return <CACCalculator lang={lang} />;
  if (activeCalc === "conversion-rate") return <ConversionRateCalculator lang={lang} />;
  if (activeCalc === "inventory-turnover") return <InventoryTurnoverCalculator lang={lang} />;
  if (activeCalc === "financial-ratio") return <FinancialRatioCalculator lang={lang} />;
  if (activeCalc === "marketplace-fee") return <MarketplaceFeeCalculator lang={lang} />;
  if (activeCalc === "safety-stock") return <SafetyStockCalculator lang={lang} />;
  if (activeCalc === "shipping-cost") return <ShippingCostCalculator lang={lang} />;
  if (activeCalc === "return-rate") return <ReturnRateCalculator lang={lang} />;
  if (activeCalc === "eoq") return <EOQCalculator lang={lang} setCalc={setCalc} />;
  if (activeCalc === "churn-retention") return <ChurnRetentionCalc lang={lang} setCalc={setCalc} />;
  if (activeCalc === "shrinkage") return <ShrinkageCalc lang={lang} setCalc={setCalc} />;
  if (activeCalc === "import-markup") return <ImportMarkupCalc lang={lang} setCalc={setCalc} />;
  if (activeCalc === "freelance-rate") return <FreelanceRate lang={lang} setCalc={setCalc} />;

  // Utility
  if (activeCalc === "btu") return <BTUCalculator lang={lang} />;
  if (activeCalc === "electric") return <ElectricCalculator lang={lang} />;
  if (activeCalc === "water-bill") return <UtilityWaterCalculator lang={lang} />;
  if (activeCalc === "basen") return <BaseNCalculator lang={lang} />;
  if (activeCalc === "gpa") return <GPACalculator lang={lang} />;
  if (activeCalc === "fuel-cost") return <FuelCostCalculator lang={lang} />;
  if (activeCalc === "grade-converter") return <GradeConverter lang={lang} />;
  if (activeCalc === "target-gpa") return <TargetGPACalculator lang={lang} />;
  if (activeCalc === "percentile") return <PercentileCalculator lang={lang} />;
  if (activeCalc === "reading-time") return <ReadingTimeCalculator lang={lang} />;

  if (activeCalc === "english-test") return <EnglishTestConverter lang={lang} setCalc={setCalc} />;
  if (activeCalc === "pomodoro") return <PomodoroTimer lang={lang} />;
  if (activeCalc === "flashcard-timer") return <FlashCardTimer lang={lang} />;

  // Conversion
  if (activeCalc === "cooking-unit") return <CookingUnitConverter lang={lang} />;
  if (activeCalc === "tile-area") return <TileAreaCalculator lang={lang} />;
  if (activeCalc === "digital-unit") return <DigitalUnitConverter lang={lang} />;
  if (activeCalc === "angle") return <AngleConverter lang={lang} />;
  if (activeCalc === "color") return <ColorConverter lang={lang} />;
  if (activeCalc === "temperature") return <TemperatureConverter lang={lang} />;
  if (activeCalc === "speed") return <SpeedConverter lang={lang} />;
  if (activeCalc === "area-unit") return <AreaUnitConverter lang={lang} />;
  if (activeCalc === "weight-unit") return <WeightUnitConverter lang={lang} />;
  if (activeCalc === "roman") return <RomanNumeralConverter lang={lang} />;
  if (activeCalc === "area-shape") return <AreaShapeCalculator lang={lang} />;
  if (activeCalc === "volume-shape") return <VolumeShapeCalculator lang={lang} />;
  if (activeCalc === "working-days") return <WorkingDaysCalculator lang={lang} />;
  if (activeCalc === "pantone") return <PantoneConverter lang={lang} />;

  // Agriculture

  if (activeCalc === "food-energy") return <FoodEnergyCalculator lang={lang} />;
  if (activeCalc === "fertilizer") return <FertilizerCalculator lang={lang} />;
  if (activeCalc === "irrigation") return <IrrigationCalculator lang={lang} />;
  if (activeCalc === "yield") return <YieldCalculator lang={lang} />;
  if (activeCalc === "durian") return <DurianCalculator lang={lang} setCalc={setCalc} />;

  // Construction
  if (activeCalc === "house-paint") return <HousePaintCalculator lang={lang} />;
  if (activeCalc === "cement") return <CementCalculator lang={lang} />;
  if (activeCalc === "wallpaper") return <WallpaperCalculator lang={lang} />;
  if (activeCalc === "roof-area") return <RoofAreaCalculator lang={lang} />;
  if (activeCalc === "water-tank") return <WaterTankCalculator lang={lang} />;
  if (activeCalc === "pool-vol") return <PoolVolumeCalculator lang={lang} />;
  if (activeCalc === "insulation") return <InsulationCalculator lang={lang} />;
  if (activeCalc === "reno-cost") return <RenovationCostCalculator lang={lang} />;

  // General

  if (activeCalc === "word-counter") return <WordCounter lang={lang} />;
  if (activeCalc === "age") return <AgeCalculator lang={lang} />;
  
  // Technology
  if (activeCalc === "bandwidth") return <BandwidthCalculator lang={lang} />;
  if (activeCalc === "server-cost") return <ServerCostCalculator lang={lang} />;
  if (activeCalc === "image-size") return <ImageSizeCalculator lang={lang} />;
  if (activeCalc === "ip-subnet") return <IPSubnetCalculator lang={lang} />;
  if (activeCalc === "video-bitrate") return <VideoBitrateCalculator lang={lang} />;
  if (activeCalc === "battery-life") return <BatteryLifeCalculator lang={lang} />;
  if (activeCalc === "hash-rate") return <HashRateCalculator lang={lang} />;
  if (activeCalc === "raid-calc") return <RaidCalculator lang={lang} />;
  if (activeCalc === "ppi-calc") return <PpiCalculator lang={lang} />;
  if (activeCalc === "api-cost") return <ApiCostCalculator lang={lang} />;
  if (activeCalc === "ups-runtime") return <UpsRuntimeCalculator lang={lang} />;
  if (activeCalc === "morse-code") return <MorseCodeConverter lang={lang} />;
  if (activeCalc === "ascii-converter") return <AsciiConverter lang={lang} />;
  if (activeCalc === "cache-hit-rate") return <CacheHitRateCalculator lang={lang} />;

  // Agriculture 3
  if (activeCalc === "soil-ph") return <SoilPhCalculator lang={lang} />;
  if (activeCalc === "livestock-profit") return <LivestockProfitCalculator lang={lang} />;
  if (activeCalc === "spray-volume") return <SprayVolumeCalculator lang={lang} />;
  if (activeCalc === "fishery-income") return <FisheryIncomeCalculator lang={lang} />;
  if (activeCalc === "yield-gap") return <YieldGapCalculator lang={lang} />;

  // Travel 2
  if (activeCalc === "jet-lag") return <JetLagCalculator lang={lang} />;
  if (activeCalc === "roaming-cost") return <RoamingCostCalculator lang={lang} />;

  // Construction 2
  if (activeCalc === "solar-panel") return <SolarPanelCalculator lang={lang} />;
  if (activeCalc === "interior-cost") return <InteriorCostCalculator lang={lang} />;
  if (activeCalc === "ach-calc") return <AchVentilationCalculator lang={lang} />;
  if (activeCalc === "concrete-vol") return <ConcreteVolumeCalculator lang={lang} />;
  if (activeCalc === "rebar-weight") return <RebarWeightCalculator lang={lang} />;
  if (activeCalc === "aac-blocks") return <AacBlocksCalculator lang={lang} />;
  if (activeCalc === "labor-cost-sqm") return <LaborCostCalculator lang={lang} />;
  if (activeCalc === "plumbing-pipe") return <PlumbingPipeCalculator lang={lang} />;
  if (activeCalc === "slope-grade") return <SlopeGradeCalculator lang={lang} />;

  // Environment
  if (activeCalc === "carbon-footprint") return <CarbonFootprintCalculator lang={lang} />;
  if (activeCalc === "wind-energy") return <WindEnergyCalculator lang={lang} />;
  if (activeCalc === "water-savings") return <WaterSavingsCalculator lang={lang} />;
  if (activeCalc === "plastic-footprint") return <PlasticFootprintCalculator lang={lang} />;

  // Science
  if (activeCalc === "quadratic-eq") return <QuadraticCalculator lang={lang} />;
  if (activeCalc === "ph-poh") return <PHCalculator lang={lang} />;

    if (activeCalc === "e-waste-water-footprint") return <EWasteWaterFootprintBatch10 lang={lang} />;
  if (activeCalc === "ev-charger-installation-cost") return <EVChargerInstallationCostBatch10 lang={lang} />;
  if (activeCalc === "ev-charging-cost") return <EVChargingCostBatch10 lang={lang} />;
  if (activeCalc === "green-building-score") return <GreenBuildingScoreBatch10 lang={lang} />;
  if (activeCalc === "led-savings") return <LEDSavingsCalculatorBatch10 lang={lang} />;
  if (activeCalc === "livestock-methane-emissions") return <LivestockMethaneEmissionsBatch10 lang={lang} />;
  if (activeCalc === "personal-ecological-footprint") return <PersonalEcologicalFootprintBatch10 lang={lang} />;
  if (activeCalc === "renewable-vs-grid-electricity") return <RenewableVsGridElectricityBatch10 lang={lang} />;
  if (activeCalc === "solar-payback-period") return <SolarPaybackPeriodCalculatorBatch10 lang={lang} />;
  if (activeCalc === "tree-co2-offset") return <TreeCO2OffsetCalculatorBatch10 lang={lang} />;
  if (activeCalc === "app-dev-cost") return <AppDevCostCalculatorBatch11 lang={lang} />;
  if (activeCalc === "app-store-revenue") return <AppStoreRevenueCalculatorBatch11 lang={lang} />;
  if (activeCalc === "cdn-cost-calculator") return <CdnCostCalculatorBatch11 lang={lang} />;
  if (activeCalc === "cloud-storage-cost") return <CloudStorageCostCalculatorBatch11 lang={lang} />;
  if (activeCalc === "database-cost") return <DatabaseCostCalculatorBatch11 lang={lang} />;
  if (activeCalc === "facebook-ads-roi-cpa") return <FacebookAdsRoiCalculatorBatch11 lang={lang} />;
  if (activeCalc === "google-ads-roi-roas") return <GoogleAdsRoiCalculatorBatch11 lang={lang} />;
  if (activeCalc === "ltv-to-cac-ratio") return <LtvCacRatioCalculatorBatch11 lang={lang} />;
  if (activeCalc === "sms-email-marketing-cost") return <SmsEmailCostCalculatorBatch11 lang={lang} />;
  if (activeCalc === "vps-dedicated-cost") return <VpsDedicatedCostCalculatorBatch11 lang={lang} />;
  if (activeCalc === "cro-revenue-impact-calculator") return <CroRevenueImpactCalculatorBatch12 lang={lang} />;
  if (activeCalc === "domain-hosting-cost-calculator") return <DomainHostingCostCalculatorBatch12 lang={lang} />;
  if (activeCalc === "email-deliverability-score-calculator") return <EmailDeliverabilityScoreCalculatorBatch12 lang={lang} />;
  if (activeCalc === "email-revenue-calculator") return <EmailRevenueCalculatorBatch12 lang={lang} />;
  if (activeCalc === "pwa-vs-native-app-cost-calculator") return <PwaVsNativeAppCostCalculatorBatch12 lang={lang} />;
  if (activeCalc === "saas-stack-total-cost-calculator") return <SaasStackTotalCostCalculatorBatch12 lang={lang} />;
  if (activeCalc === "seo-value-calculator") return <SeoValueCalculatorBatch12 lang={lang} />;
  if (activeCalc === "sme-cybersecurity-cost-calculator") return <SmeCybersecurityCostCalculatorBatch12 lang={lang} />;
  if (activeCalc === "ssl-certificate-cost-calculator") return <SslCertificateCostCalculatorBatch12 lang={lang} />;
  if (activeCalc === "technical-debt-cost-calculator") return <TechnicalDebtCostCalculatorBatch12 lang={lang} />;
  if (activeCalc === "ac-electricity-cost") return <ACElectricityCostBatch13 lang={lang} />;
  if (activeCalc === "built-in-kitchen-cost") return <BuiltInKitchenCostBatch13 lang={lang} />;
  if (activeCalc === "condo-maintenance-fee-total") return <CondoMaintenanceFeeTotalBatch13 lang={lang} />;
  if (activeCalc === "condo-purchase-cost") return <CondoPurchaseCostBatch13 lang={lang} />;
  if (activeCalc === "condo-rent-vs-buy-to-let-roi") return <CondoRentVsBuyToLetROIBatch13 lang={lang} />;
  if (activeCalc === "full-house-furniture-cost") return <FullHouseFurnitureCostBatch13 lang={lang} />;
  if (activeCalc === "moving-house-cost") return <MovingHouseCostBatch13 lang={lang} />;
  if (activeCalc === "new-house-purchase-cost") return <NewHousePurchaseCostBatch13 lang={lang} />;
  if (activeCalc === "property-tax-calculator") return <PropertyTaxCalculatorBatch13 lang={lang} />;
  if (activeCalc === "rental-yield-calculator") return <RentalYieldCalculatorBatch13 lang={lang} />;
  if (activeCalc === "ac-btu-size-calculator") return <AcBtuSizeCalculatorBatch14 lang={lang} />;
  if (activeCalc === "appliance-electricity-cost") return <ApplianceElectricityCostBatch14 lang={lang} />;
  if (activeCalc === "garden-maintenance-cost") return <GardenMaintenanceCostBatch14 lang={lang} />;
  if (activeCalc === "home-internet-cost") return <HomeInternetCostBatch14 lang={lang} />;
  if (activeCalc === "home-security-cost") return <HomeSecurityCostBatch14 lang={lang} />;
  if (activeCalc === "home-solar-installation-cost") return <HomeSolarInstallationCostBatch14 lang={lang} />;
  if (activeCalc === "house-painting-cost") return <HousePaintingCostBatch14 lang={lang} />;
  if (activeCalc === "household-water-usage-cost") return <HouseholdWaterUsageCostBatch14 lang={lang} />;
  if (activeCalc === "pool-maintenance-cost") return <PoolMaintenanceCostBatch14 lang={lang} />;
  if (activeCalc === "roof-replacement-cost") return <RoofReplacementCostBatch14 lang={lang} />;
  if (activeCalc === "car-comparison") return <CarComparisonCalculatorBatch15 lang={lang} />;
  if (activeCalc === "car-depreciation") return <CarDepreciationCalculatorBatch15 lang={lang} />;
  if (activeCalc === "car-insurance") return <CarInsuranceCalculatorBatch15 lang={lang} />;
  if (activeCalc === "car-maintenance") return <CarMaintenanceCalculatorBatch15 lang={lang} />;
  if (activeCalc === "car-tco") return <CarTcoCalculatorBatch15 lang={lang} />;
  if (activeCalc === "ev-cost-per-km") return <EvCostPerKmCalculatorBatch15 lang={lang} />;
  if (activeCalc === "ev-ice-breakeven") return <EvIceBreakevenCalculatorBatch15 lang={lang} />;
  if (activeCalc === "motorcycle-loan") return <MotorcycleLoanCalculatorBatch15 lang={lang} />;
  if (activeCalc === "rider-roi") return <RiderRoiCalculatorBatch15 lang={lang} />;
  if (activeCalc === "truck-cost") return <TruckCostCalculatorBatch15 lang={lang} />;
  if (activeCalc === "annual-commute-cost-calculator") return <AnnualCommuteCalculatorBatch16 lang={lang} />;
  if (activeCalc === "car-pool-savings-calculator") return <CarPoolCalculatorBatch16 lang={lang} />;
  if (activeCalc === "monthly-parking-cost-calculator") return <MonthlyParkingCalculatorBatch16 lang={lang} />;
  if (activeCalc === "monthly-toll-fee-calculator") return <TollFeeCalculatorBatch16 lang={lang} />;
  if (activeCalc === "ride-hailing-vs-own-car-cost-calculator") return <RideHailingVsOwnCarCalculatorBatch16 lang={lang} />;
  if (activeCalc === "anniversary-countdown") return <AnniversaryCountdown lang={lang} />;
  if (activeCalc === "event-countdown") return <EventCountdown lang={lang} />;
  if (activeCalc === "exact-age-calculator") return <ExactAgeCalculator lang={lang} />;
  if (activeCalc === "retirement-countdown") return <RetirementCountdown lang={lang} />;
  if (activeCalc === "sunrise-sunset-calculator") return <SunriseSunsetCalculator lang={lang} />;
  if (activeCalc === "thai-lunar-phase") return <ThaiLunarPhase lang={lang} />;
  if (activeCalc === "font-size-reading-distance") return <FontSizeReadingDistance lang={lang} />;
  if (activeCalc === "remaining-annual-leave") return <RemainingAnnualLeave lang={lang} />;
  if (activeCalc === "shift-work-staffing") return <ShiftWorkStaffing lang={lang} />;
  if (activeCalc === "social-media-image-size") return <SocialMediaImageSize lang={lang} />;
  if (activeCalc === "customs-broker-fee") return <CustomsBrokerFeeCalculator lang={lang} />;
  if (activeCalc === "hs-code-import-tax") return <HsCodeImportTaxCalculator lang={lang} />;
  if (activeCalc === "import-customs-duty") return <ImportCustomsDutyCalculator lang={lang} />;
  if (activeCalc === "solar-battery-sizing") return <SolarBatterySizing lang={lang} />;
  if (activeCalc === "solar-inverter-sizing") return <SolarInverterSizing lang={lang} />;
  if (activeCalc === "tou-electricity-cost") return <TouElectricityCost lang={lang} />;
  if (activeCalc === "cost-of-living-comparison") return <CostOfLivingComparison lang={lang} />;
  if (activeCalc === "qaly-calculator") return <QalyCalculator lang={lang} />;
  if (activeCalc === "metcalfe-network-value") return <MetcalfeNetworkValue lang={lang} />;
  if (activeCalc === "online-course-roi") return <OnlineCourseRoi lang={lang} />;
  if (activeCalc === "viral-coefficient") return <ViralCoefficient lang={lang} />;
  if (activeCalc === "automation-roi") return <AutomationROI lang={lang} />;
  if (activeCalc === "brooks-law-team-size") return <BrooksLawTeamSize lang={lang} />;
  if (activeCalc === "noise-level-db") return <NoiseLevelDb lang={lang} />;
  if (activeCalc === "sound-insulation") return <SoundInsulation lang={lang} />;
  if (activeCalc === "flow-state-frequency") return <FlowStateFrequency lang={lang} />;
  if (activeCalc === "banana-farming-calculator") return <BananaFarmingCalculatorBatch7 lang={lang} />;
  if (activeCalc === "broiler-chicken-farm-calculator") return <BroilerChickenFarmCalculatorBatch7 lang={lang} />;
  if (activeCalc === "cassava-farming-calculator") return <CassavaFarmingCalculatorBatch7 lang={lang} />;
  if (activeCalc === "coconut-farming-calculator") return <CoconutFarmingCalculatorBatch7 lang={lang} />;
  if (activeCalc === "corn-farming-calculator") return <CornFarmingCalculatorBatch7 lang={lang} />;
  if (activeCalc === "mango-farming-calculator") return <MangoFarmingCalculatorBatch7 lang={lang} />;
  if (activeCalc === "oil-palm-farming-calculator") return <OilPalmFarmingCalculatorBatch7 lang={lang} />;
  if (activeCalc === "rubber-tree-farming-calculator") return <RubberTreeFarmingCalculatorBatch7 lang={lang} />;
  if (activeCalc === "sugarcane-farming-calculator") return <SugarcaneFarmingCalculatorBatch7 lang={lang} />;
  if (activeCalc === "white-shrimp-farm-calculator") return <WhiteShrimpFarmCalculatorBatch7 lang={lang} />;
  if (activeCalc === "agri-chemical-mix-ratio") return <AgriChemicalMixRatioBatch8 lang={lang} />;
  if (activeCalc === "beef-cattle-farm-profit-cost") return <BeefCattleFarmProfitCostBatch8 lang={lang} />;
  if (activeCalc === "drip-irrigation-cost") return <DripIrrigationCostBatch8 lang={lang} />;
  if (activeCalc === "farm-area-from-gps") return <FarmAreaFromGpsBatch8 lang={lang} />;
  if (activeCalc === "farm-break-even-yield") return <FarmBreakEvenYieldBatch8 lang={lang} />;
  if (activeCalc === "farm-labor-cost-per-rai") return <FarmLaborCostPerRaiBatch8 lang={lang} />;
  if (activeCalc === "layer-chicken-farm-profit-cost") return <LayerChickenFarmProfitCostBatch8 lang={lang} />;
  if (activeCalc === "pig-farm-profit-cost") return <PigFarmProfitCostBatch8 lang={lang} />;
  if (activeCalc === "seeds-per-rai-calculator") return <SeedsPerRaiCalculatorBatch8 lang={lang} />;
  if (activeCalc === "tractor-rent-vs-buy") return <TractorRentVsBuyBatch8 lang={lang} />;
  if (activeCalc === "farm-land-rent-roi") return <FarmLandRentRoiBatch9 lang={lang} />;
  if (activeCalc === "food-carbon-footprint") return <FoodCarbonFootprintBatch9 lang={lang} />;
  if (activeCalc === "fresh-to-dry-weight") return <FreshToDryWeightBatch9 lang={lang} />;
  if (activeCalc === "germination-rate") return <GerminationRateBatch9 lang={lang} />;
  if (activeCalc === "harvest-time") return <HarvestTimeBatch9 lang={lang} />;
  if (activeCalc === "mill-storage-electricity") return <MillStorageElectricityBatch9 lang={lang} />;
  if (activeCalc === "product-water-footprint") return <ProductWaterFootprintBatch9 lang={lang} />;
  if (activeCalc === "recycled-waste-impact") return <RecycledWasteImpactBatch9 lang={lang} />;
  if (activeCalc === "travel-carbon-footprint") return <TravelCarbonFootprintBatch9 lang={lang} />;
  if (activeCalc === "water-saving-impact") return <WaterSavingImpactBatch9 lang={lang} />;

  return (
    <div className="text-center p-12 text-gray-500">
      {lang === "TH" ? "กรุณาเลือกเครื่องมือคำนวณจากเมนูด้านซ้าย" : "Please select a calculator from the menu"}
    </div>
  );
}
