import * as Icons from "lucide-react";

export type Lang = "TH" | "EN";

export type Calculator = {
  id: string;
  slug: string;
  name: string;
  desc: string;
  category: string;
  icon: any;
};

export const getCalcs = (lang: Lang): Calculator[] => [
  {
    id: "e-waste-water-footprint",
    slug: "e-waste-water-footprint",
    name: lang === "TH" ? "คำนวณปริมาณน้ำในขยะอิเล็กทรอนิกส์" : "E-waste Water Footprint Calculator",
    desc: lang === "TH" ? "ประเมินปริมาณน้ำซ่อนเร้น (Water Footprint) ที่ถูกใช้ในกระบวนการผลิตอุปกรณ์อิเล็กทรอนิกส์ต่างๆ" : "Estimate the hidden water (Water Footprint) used in manufacturing various electronic devices.",
    category: "Environment",
    icon: Icons.Droplet
  },
  {
    id: "ev-charger-installation-cost",
    slug: "ev-charger-installation-cost",
    name: lang === "TH" ? "คำนวณค่าใช้จ่ายติดตั้งสถานีชาร์จ EV" : "EV Charger Installation Cost Calculator",
    desc: lang === "TH" ? "ประเมินค่าใช้จ่ายในการติดตั้งเครื่องชาร์จรถยนต์ไฟฟ้า (EV Charger) ที่บ้าน รวมถึงการขอเปลี่ยนมิเตอร์" : "Estimate the total cost of installing a home EV charger, including meter upgrades and labor.",
    category: "Environment",
    icon: Icons.PlugZap
  },
  {
    id: "ev-charging-cost",
    slug: "ev-charging-cost",
    name: lang === "TH" ? "คำนวณต้นทุนการชาร์จรถ EV" : "EV Charging Cost per 100km Calculator",
    desc: lang === "TH" ? "คำนวณค่าไฟฟ้าในการชาร์จรถยนต์ไฟฟ้า (EV) และประเมินค่าใช้จ่ายในการเดินทางต่อ 100 กิโลเมตร" : "Calculate the electricity cost of charging an EV and estimate the travel cost per 100 kilometers.",
    category: "Environment",
    icon: Icons.Car
  },
  {
    id: "green-building-score",
    slug: "green-building-score",
    name: lang === "TH" ? "คำนวณคะแนนอาคารสีเขียว (Green Building Score)" : "Green Building Score Calculator",
    desc: lang === "TH" ? "จำลองการประเมินคะแนนอาคารสีเขียวเบื้องต้น (อ้างอิงตามเกณฑ์ LEED) เพื่อดูระดับการรับรองของอาคารคุณ" : "Simulate a basic Green Building score (based on LEED criteria) to see your potential certification level.",
    category: "Environment",
    icon: Icons.Building2
  },
  {
    id: "led-savings",
    slug: "led-savings",
    name: lang === "TH" ? "คำนวณพลังงานที่ประหยัดได้จากเปลี่ยน LED" : "LED Savings Calculator",
    desc: lang === "TH" ? "คำนวณค่าไฟฟ้าและพลังงานที่คุณสามารถประหยัดได้จากการเปลี่ยนหลอดไฟธรรมดาเป็นหลอดไฟ LED" : "Calculate the electricity cost and energy savings from switching to LED bulbs.",
    category: "Environment",
    icon: Icons.Lightbulb
  },
  {
    id: "livestock-methane-emissions",
    slug: "livestock-methane-emissions",
    name: lang === "TH" ? "คำนวณปริมาณมีเทนจากฟาร์มปศุสัตว์" : "Livestock Methane Emissions Calculator",
    desc: lang === "TH" ? "ประเมินปริมาณก๊าซมีเทน (Methane) ที่ปล่อยออกมาจากการทำฟาร์มปศุสัตว์ต่อปี" : "Estimate the annual methane (CH₄) emissions generated by livestock farming.",
    category: "Environment",
    icon: Icons.Tractor
  },
  {
    id: "personal-ecological-footprint",
    slug: "personal-ecological-footprint",
    name: lang === "TH" ? "คำนวณ Ecological Footprint ส่วนตัว" : "Personal Ecological Footprint Calculator",
    desc: lang === "TH" ? "ประเมินรอยเท้านิเวศของคุณ เพื่อดูว่าไลฟ์สไตล์ปัจจุบันใช้ทรัพยากรธรรมชาติไปมากน้อยเพียงใด" : "Estimate your ecological footprint to see how much of the Earth's resources your lifestyle consumes.",
    category: "Environment",
    icon: Icons.Globe
  },
  {
    id: "renewable-vs-grid-electricity",
    slug: "renewable-vs-grid-electricity",
    name: lang === "TH" ? "เปรียบเทียบค่าไฟพลังงานทดแทน vs ไฟฟ้าปกติ" : "Renewable vs Grid Electricity Calculator",
    desc: lang === "TH" ? "เปรียบเทียบค่าใช้จ่ายรายเดือนระหว่างการใช้ไฟฟ้าจากการไฟฟ้าปกติ กับการผสมผสานพลังงานทดแทน" : "Compare monthly electricity costs between standard grid power and a mix of renewable energy.",
    category: "Environment",
    icon: Icons.Zap
  },
  {
    id: "solar-payback-period",
    slug: "solar-payback-period",
    name: lang === "TH" ? "คำนวณระยะเวลาคืนทุนแผงโซลาร์" : "Solar Payback Period Calculator",
    desc: lang === "TH" ? "คำนวณระยะเวลาคืนทุนของการติดตั้งแผงโซลาร์เซลล์ ประเมินการผลิตไฟและจุดคุ้มทุนเบื้องต้น" : "Estimate the payback period, annual energy generation, and savings for a solar panel installation.",
    category: "Environment",
    icon: Icons.Sun
  },
  {
    id: "tree-co2-offset",
    slug: "tree-co2-offset",
    name: lang === "TH" ? "คำนวณปริมาณ CO₂ ที่ต้นไม้ดูดซับ" : "Tree CO₂ Offset Calculator",
    desc: lang === "TH" ? "คำนวณและประเมินปริมาณก๊าซคาร์บอนไดออกไซด์ (CO₂) ที่ต้นไม้สามารถดูดซับได้ต่อปี" : "Calculate and estimate the amount of carbon dioxide (CO₂) absorbed by trees per year.",
    category: "Environment",
    icon: Icons.TreeDeciduous
  },
  {
    id: "app-dev-cost",
    slug: "app-dev-cost",
    name: lang === "TH" ? "เครื่องมือประเมินค่าใช้จ่ายพัฒนาแอปพลิเคชัน" : "App Development Cost Calculator",
    desc: lang === "TH" ? "ประเมินค่าใช้จ่ายในการพัฒนาแอป (iOS, Android, Web) ตามขนาดของฟีเจอร์และเรทนักพัฒนา" : "Estimate app development costs (iOS, Android, Web) based on feature size and developer rates.",
    category: "Technology",
    icon: Icons.Calculator
  },
  {
    id: "app-store-revenue",
    slug: "app-store-revenue",
    name: lang === "TH" ? "เครื่องมือคำนวณรายได้ App Store / Google Play" : "App Store Revenue Calculator",
    desc: lang === "TH" ? "คำนวณรายได้สุทธิและหักค่าคอมมิชชั่นของ Apple App Store และ Google Play Store (15% vs 30%)" : "Calculate net revenue and commissions for Apple App Store and Google Play Store (15% vs 30%).",
    category: "Technology",
    icon: Icons.Calculator
  },
  {
    id: "cdn-cost-calculator",
    slug: "cdn-cost-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณ CDN Cost" : "CDN Cost Calculator",
    desc: lang === "TH" ? "ประเมินค่าใช้จ่าย Content Delivery Network (CDN) รายเดือนตามปริมาณแบนด์วิดท์และ Requests" : "Estimate monthly Content Delivery Network (CDN) costs based on bandwidth and requests.",
    category: "Technology",
    icon: Icons.Calculator
  },
  {
    id: "cloud-storage-cost",
    slug: "cloud-storage-cost",
    name: lang === "TH" ? "เครื่องมือคำนวณค่าบริการ Cloud Storage" : "Cloud Storage Cost Calculator",
    desc: lang === "TH" ? "ประเมินค่าใช้จ่ายพื้นที่จัดเก็บข้อมูลบนคลาวด์มาตรฐาน (เทียบเท่า AWS S3, GCS) รวมถึงค่าแบนด์วิดท์และ Requests" : "Estimate standard cloud storage costs (comparable to AWS S3, GCS) including bandwidth and requests.",
    category: "Technology",
    icon: Icons.Calculator
  },
  {
    id: "database-cost",
    slug: "database-cost",
    name: lang === "TH" ? "เครื่องมือคำนวณ Database Cost (Managed DB)" : "Database Cost Calculator (Managed DB)",
    desc: lang === "TH" ? "ประมาณการค่าใช้จ่ายบริการฐานข้อมูลบนคลาวด์ (เช่น RDS) โดยคิดจาก Instance, Storage และ Data Transfer" : "Estimate cloud managed database costs (like RDS) based on Instance, Storage, and Data Transfer.",
    category: "Technology",
    icon: Icons.Calculator
  },
  {
    id: "facebook-ads-roi-cpa",
    slug: "facebook-ads-roi-cpa",
    name: lang === "TH" ? "เครื่องมือคำนวณ ROI โฆษณา Facebook Ads" : "Facebook Ads ROI & CPA Calculator",
    desc: lang === "TH" ? "คำนวณผลตอบแทนการลงทุน (ROI), ROAS, CPA, และจุดคุ้มทุนสำหรับแคมเปญ Facebook Ads" : "Calculate Return on Investment (ROI), ROAS, CPA, and break-even point for Facebook Ads campaigns.",
    category: "Technology",
    icon: Icons.Calculator
  },
  {
    id: "google-ads-roi-roas",
    slug: "google-ads-roi-roas",
    name: lang === "TH" ? "เครื่องมือคำนวณ ROI โฆษณา Google Ads" : "Google Ads ROI & ROAS Calculator",
    desc: lang === "TH" ? "คำนวณผลตอบแทนการลงทุน (ROI), ROAS, CPC, และเปรียบเทียบกำไรจากแคมเปญ Google Ads (Search/Display/Shopping)" : "Calculate Return on Investment (ROI), ROAS, CPC, and profitability for Google Ads campaigns.",
    category: "Technology",
    icon: Icons.Calculator
  },
  {
    id: "ltv-to-cac-ratio",
    slug: "ltv-to-cac-ratio",
    name: lang === "TH" ? "เครื่องมือคำนวณ LTV:CAC Ratio" : "LTV to CAC Ratio Calculator",
    desc: lang === "TH" ? "คำนวณมูลค่าตลอดอายุการใช้งานของลูกค้า (LTV) เทียบกับต้นทุนในการหาลูกค้าใหม่ (CAC) เพื่อวัดสุขภาพของธุรกิจระยะยาว" : "Calculate Customer Lifetime Value (LTV) to Customer Acquisition Cost (CAC) ratio to measure long-term business health.",
    category: "Technology",
    icon: Icons.Calculator
  },
  {
    id: "sms-email-marketing-cost",
    slug: "sms-email-marketing-cost",
    name: lang === "TH" ? "ค่าใช้จ่าย SMS/Email Marketing" : "SMS & Email Marketing Cost",
    desc: lang === "TH" ? "คำนวณและเปรียบเทียบต้นทุนการส่งแคมเปญการตลาดผ่าน SMS และ Email พร้อมประเมินค่าใช้จ่ายต่อผู้รับ (Cost per User)" : "Calculate and compare the cost of marketing campaigns via SMS and Email, including Cost per User.",
    category: "Technology",
    icon: Icons.Calculator
  },
  {
    id: "vps-dedicated-cost",
    slug: "vps-dedicated-cost",
    name: lang === "TH" ? "เครื่องมือเปรียบเทียบค่าใช้จ่าย VPS / Dedicated Server" : "VPS vs Dedicated Server Cost Calculator",
    desc: lang === "TH" ? "คำนวณและเปรียบเทียบค่าใช้จ่ายรายเดือนและรายปีของการเช่า Server ไม่ว่าจะเป็น VPS หรือ Dedicated พร้อมค่า Management" : "Calculate and compare monthly and yearly costs of renting VPS or Dedicated servers, including management fees.",
    category: "Technology",
    icon: Icons.Calculator
  },
  {
    id: "cro-revenue-impact-calculator",
    slug: "cro-revenue-impact-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณรายได้จาก CRO (Conversion Rate)" : "CRO Revenue Impact Calculator",
    desc: lang === "TH" ? "วิเคราะห์การเติบโตของรายได้ (Revenue Uplift) จากการปรับปรุงอัตราการแปลง (Conversion Rate)" : "Analyze the potential revenue uplift from optimizing your Conversion Rate (CRO).",
    category: "Technology",
    icon: Icons.TrendingUp
  },
  {
    id: "domain-hosting-cost-calculator",
    slug: "domain-hosting-cost-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณค่าใช้จ่าย Domain & Hosting" : "Domain & Hosting Cost Calculator",
    desc: lang === "TH" ? "คำนวณต้นทุนการทำเว็บไซต์ต่อปี ทั้งค่าจดโดเมน ค่าบริการเว็บโฮสติ้ง และส่วนเสริมต่างๆ" : "Calculate the annual cost of running a website, including domain registration, hosting, and addons.",
    category: "Technology",
    icon: Icons.Server
  },
  {
    id: "email-deliverability-score-calculator",
    slug: "email-deliverability-score-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณ Email Deliverability Score" : "Email Deliverability Score Calculator",
    desc: lang === "TH" ? "ประเมินคุณภาพและโอกาสที่อีเมลของคุณจะถูกส่งเข้า Inbox จากค่า Bounce Rate และการตั้งค่า DMARC" : "Assess your email inbox placement score based on bounce rates, spam complaints, and authentication (DMARC/SPF/DKIM).",
    category: "Technology",
    icon: Icons.MailCheck
  },
  {
    id: "email-revenue-calculator",
    slug: "email-revenue-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณรายได้จาก Email Marketing" : "Email Revenue Calculator",
    desc: lang === "TH" ? "คำนวณผลตอบแทนและรายได้จากแคมเปญอีเมล จาก Open Rate และ Conversion Rate" : "Calculate ROI and revenue from email campaigns based on Open Rate and Conversion Rate.",
    category: "Technology",
    icon: Icons.Mail
  },
  {
    id: "pwa-vs-native-app-cost-calculator",
    slug: "pwa-vs-native-app-cost-calculator",
    name: lang === "TH" ? "เครื่องมือเปรียบเทียบค่าใช้จ่าย PWA vs Native App" : "PWA vs Native App Cost Calculator",
    desc: lang === "TH" ? "เปรียบเทียบต้นทุนการพัฒนาและดูแลรักษาระหว่าง Progressive Web App และ Native App (iOS/Android)" : "Compare development and maintenance costs between Progressive Web Apps (PWA) and Native Apps.",
    category: "Technology",
    icon: Icons.Smartphone
  },
  {
    id: "saas-stack-total-cost-calculator",
    slug: "saas-stack-total-cost-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณค่าใช้จ่าย SaaS Stack" : "SaaS Stack Total Cost Calculator",
    desc: lang === "TH" ? "จัดการและประเมินค่าใช้จ่ายรวมของซอฟต์แวร์ SaaS (Software as a Service) ที่องค์กรใช้งาน" : "Manage and calculate the total cost of all your SaaS subscriptions to optimize software spend.",
    category: "Technology",
    icon: Icons.Layers
  },
  {
    id: "seo-value-calculator",
    slug: "seo-value-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณ SEO Value" : "SEO Value Calculator",
    desc: lang === "TH" ? "คำนวณมูลค่าของทราฟฟิกออร์แกนิก (SEO Value) จาก Search Volume และ CPC" : "Calculate the organic traffic value (SEO Value) based on Search Volume and CPC.",
    category: "Technology",
    icon: Icons.Search
  },
  {
    id: "sme-cybersecurity-cost-calculator",
    slug: "sme-cybersecurity-cost-calculator",
    name: lang === "TH" ? "เครื่องมือประเมินค่าใช้จ่าย Cybersecurity สำหรับ SME" : "SME Cybersecurity Cost Calculator",
    desc: lang === "TH" ? "ประเมินต้นทุนพื้นฐานในการรักษาความปลอดภัยไซเบอร์รายปี สำหรับองค์กรธุรกิจและ SME" : "Estimate the baseline annual cybersecurity costs for small and medium-sized businesses.",
    category: "Technology",
    icon: Icons.ShieldAlert
  },
  {
    id: "ssl-certificate-cost-calculator",
    slug: "ssl-certificate-cost-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณค่าใช้จ่าย SSL Certificate" : "SSL Certificate Cost Calculator",
    desc: lang === "TH" ? "ประเมินค่าใช้จ่ายในการจดทะเบียนและต่ออายุ SSL Certificate ประเภทต่างๆ (DV, OV, EV)" : "Estimate the cost of purchasing and renewing different types of SSL Certificates.",
    category: "Technology",
    icon: Icons.ShieldCheck
  },
  {
    id: "technical-debt-cost-calculator",
    slug: "technical-debt-cost-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณมูลค่า Technical Debt" : "Technical Debt Cost Calculator",
    desc: lang === "TH" ? "ประเมินต้นทุนที่สูญเสียไปจากการรับมือกับโค้ดที่ไม่มีคุณภาพและหนี้ทางเทคนิค (Technical Debt)" : "Evaluate the financial cost of technical debt and time lost dealing with bad code.",
    category: "Technology",
    icon: Icons.Code
  },
  {
    id: "ac-electricity-cost",
    slug: "ac-electricity-cost",
    name: lang === "TH" ? "ค่าไฟแอร์" : "AC Electricity Cost",
    desc: lang === "TH" ? "คำนวณค่าไฟแอร์รายเดือน จากขนาด BTU ค่า SEER และชั่วโมงการใช้งาน" : "Calculate monthly AC electricity cost based on BTU, SEER, and usage hours.",
    category: "Utility",
    icon: Icons.Zap
  },
  {
    id: "built-in-kitchen-cost",
    slug: "built-in-kitchen-cost",
    name: lang === "TH" ? "ค่าใช้จ่ายทำ Kitchen Set Built-in" : "Built-in Kitchen Cost",
    desc: lang === "TH" ? "ประเมินราคางานบิ้วอินชุดครัว ตามความยาวและวัสดุเคาน์เตอร์" : "Estimate cost of built-in kitchen set based on length and materials.",
    category: "Family",
    icon: Icons.Utensils
  },
  {
    id: "condo-maintenance-fee-total",
    slug: "condo-maintenance-fee-total",
    name: lang === "TH" ? "ค่าส่วนกลางคอนโด" : "Condo Maintenance Fee Total",
    desc: lang === "TH" ? "คำนวณค่าส่วนกลางคอนโดรายปี พร้อมค่าที่จอดรถและค่าใช้จ่ายอื่นๆ" : "Calculate total yearly condo maintenance fee including parking and other fees.",
    category: "Family",
    icon: Icons.Building
  },
  {
    id: "condo-purchase-cost",
    slug: "condo-purchase-cost",
    name: lang === "TH" ? "ค่าใช้จ่ายซื้อคอนโด" : "Condo Purchase Cost",
    desc: lang === "TH" ? "คำนวณค่าใช้จ่ายวันโอนคอนโด ค่ากองทุนส่วนกลาง ค่าจดจำนอง และอื่นๆ" : "Calculate condo transfer day costs, sinking fund, mortgage fee, etc.",
    category: "Family",
    icon: Icons.Building
  },
  {
    id: "condo-rent-vs-buy-to-let-roi",
    slug: "condo-rent-vs-buy-to-let-roi",
    name: lang === "TH" ? "เทียบกำไรถ้าซื้อปล่อยเช่า (ROI)" : "Condo Buy to Let ROI",
    desc: lang === "TH" ? "ประเมินความคุ้มค่าและคำนวณผลตอบแทน (ROI) จากการซื้อคอนโดเพื่อปล่อยเช่า" : "Evaluate profitability and calculate ROI for buying a condo to rent out.",
    category: "Family",
    icon: Icons.TrendingUp
  },
  {
    id: "full-house-furniture-cost",
    slug: "full-house-furniture-cost",
    name: lang === "TH" ? "ค่าใช้จ่ายเปลี่ยนเฟอร์นิเจอร์ทั้งบ้าน" : "Full House Furniture Cost",
    desc: lang === "TH" ? "ประเมินงบประมาณซื้อเฟอร์นิเจอร์และเครื่องใช้ไฟฟ้าสำหรับตกแต่งบ้านใหม่" : "Estimate budget for furnishing a whole house with furniture and appliances.",
    category: "Family",
    icon: Icons.Sofa
  },
  {
    id: "moving-house-cost",
    slug: "moving-house-cost",
    name: lang === "TH" ? "ค่าใช้จ่ายย้ายบ้าน" : "Moving House Cost",
    desc: lang === "TH" ? "ประเมินงบประมาณค่าย้ายบ้าน ค่ารถบรรทุก ค่าเด็กยกของ และค่ากล่อง" : "Estimate budget for moving house, truck, movers, and packing materials.",
    category: "Family",
    icon: Icons.Truck
  },
  {
    id: "new-house-purchase-cost",
    slug: "new-house-purchase-cost",
    name: lang === "TH" ? "ค่าใช้จ่ายซื้อบ้านมือหนึ่ง" : "New House Purchase Cost",
    desc: lang === "TH" ? "คำนวณค่าใช้จ่ายทั้งหมดในการซื้อบ้านมือหนึ่ง เช่น ค่าจดจำนอง ค่าโอน ค่ามิเตอร์" : "Calculate total costs of buying a new house including mortgage fee, transfer fee, and utility deposits.",
    category: "Family",
    icon: Icons.Home
  },
  {
    id: "property-tax-calculator",
    slug: "property-tax-calculator",
    name: lang === "TH" ? "ค่าภาษีที่ดินและสิ่งปลูกสร้าง" : "Property Tax Calculator",
    desc: lang === "TH" ? "คำนวณภาษีที่ดินและสิ่งปลูกสร้าง สำหรับบ้านหลังแรก บ้านหลังที่สอง และที่ดินเปล่า" : "Calculate property and land tax for first home, second home, and vacant land.",
    category: "Family",
    icon: Icons.Building
  },
  {
    id: "rental-yield-calculator",
    slug: "rental-yield-calculator",
    name: lang === "TH" ? "คำนวณ Rental Yield" : "Rental Yield Calculator",
    desc: lang === "TH" ? "หาอัตราผลตอบแทนการปล่อยเช่า Gross Yield และ Net Yield เพื่อการลงทุน" : "Calculate Gross and Net Rental Yield for property investments.",
    category: "Family",
    icon: Icons.Percent
  },
  {
    id: "ac-btu-size-calculator",
    slug: "ac-btu-size-calculator",
    name: lang === "TH" ? "คำนวณขนาดแอร์ (BTU)" : "AC BTU Size Calculator",
    desc: lang === "TH" ? "คำนวณขนาดเครื่องปรับอากาศ (BTU) ที่เหมาะสมกับขนาดห้องและสภาพแสงแดด เพื่อความเย็นที่พอดีและประหยัดไฟ" : "Calculate the appropriate Air Conditioner BTU size based on room dimensions and sunlight exposure.",
    category: "Utility",
    icon: Icons.Snowflake
  },
  {
    id: "appliance-electricity-cost",
    slug: "appliance-electricity-cost",
    name: lang === "TH" ? "คำนวณค่าไฟเครื่องใช้ไฟฟ้าแต่ละชนิด" : "Appliance Electricity Cost Calculator",
    desc: lang === "TH" ? "เครื่องมือคำนวณค่าไฟสำหรับเครื่องใช้ไฟฟ้าแต่ละชนิด ประเมินค่าไฟรายเดือนและรายปี" : "Calculate electricity cost for specific appliances to estimate monthly and yearly expenses.",
    category: "Utility",
    icon: Icons.Zap
  },
  {
    id: "garden-maintenance-cost",
    slug: "garden-maintenance-cost",
    name: lang === "TH" ? "คำนวณค่าดูแลสวน" : "Garden Maintenance Cost Calculator",
    desc: lang === "TH" ? "ประเมินค่าใช้จ่ายในการดูแลสวนรายเดือน เช่น ค่าจ้างคนสวน ค่าปุ๋ย ค่าน้ำ เพื่อการจัดสรรงบประมาณที่เหมาะสม" : "Estimate monthly garden maintenance costs including gardener fees, fertilizers, and water usage.",
    category: "Family",
    icon: Icons.TreeDeciduous
  },
  {
    id: "home-internet-cost",
    slug: "home-internet-cost",
    name: lang === "TH" ? "เปรียบเทียบค่าอินเทอร์เน็ตบ้าน" : "Home Internet Cost Comparison",
    desc: lang === "TH" ? "เปรียบเทียบค่าใช้จ่ายอินเทอร์เน็ตบ้าน 2 แพ็กเกจ เพื่อหาตัวเลือกที่คุ้มค่าที่สุดตลอดอายุสัญญา" : "Compare 2 home internet plans to find the most cost-effective option over the contract period.",
    category: "Family",
    icon: Icons.Wifi
  },
  {
    id: "home-security-cost",
    slug: "home-security-cost",
    name: lang === "TH" ? "คำนวณค่าใช้จ่ายรักษาความปลอดภัยบ้าน" : "Home Security Cost Calculator",
    desc: lang === "TH" ? "ประเมินค่าใช้จ่ายเบื้องต้นในการติดตั้งระบบรักษาความปลอดภัย เช่น กล้องวงจรปิด สัญญาณกันขโมย และค่าใช้จ่ายรายเดือน" : "Estimate upfront and ongoing costs for home security systems including CCTV, alarms, and monitoring.",
    category: "Family",
    icon: Icons.Shield
  },
  {
    id: "home-solar-installation-cost",
    slug: "home-solar-installation-cost",
    name: lang === "TH" ? "คำนวณค่าติดตั้งและจุดคุ้มทุนโซลาร์รูฟท็อป" : "Home Solar Installation Cost Calculator",
    desc: lang === "TH" ? "ประเมินค่าใช้จ่ายเบื้องต้นในการติดตั้งแผงโซลาร์เซลล์บนหลังคาบ้าน คำนวณค่าไฟที่ประหยัดได้และระยะเวลาคืนทุน" : "Estimate home solar panel installation costs, monthly savings, and payback period.",
    category: "Construction",
    icon: Icons.Sun
  },
  {
    id: "house-painting-cost",
    slug: "house-painting-cost",
    name: lang === "TH" ? "คำนวณค่าทาสีบ้านใหม่" : "House Painting Cost Calculator",
    desc: lang === "TH" ? "ประเมินงบประมาณค่าทาสีบ้าน คำนวณปริมาณสีที่ต้องใช้และค่าแรงช่างตามพื้นที่ตารางเมตร" : "Estimate house painting budget, calculate required paint volume and labor costs based on square meters.",
    category: "Construction",
    icon: Icons.PaintRoller
  },
  {
    id: "household-water-usage-cost",
    slug: "household-water-usage-cost",
    name: lang === "TH" ? "คำนวณค่าน้ำอุปโภคบริโภค" : "Household Water Usage Cost Calculator",
    desc: lang === "TH" ? "คำนวณปริมาณการใช้น้ำและประมาณการค่าน้ำประปารายเดือนของครอบครัว" : "Calculate water usage volume and estimate monthly water bill for your household.",
    category: "Utility",
    icon: Icons.Droplet
  },
  {
    id: "pool-maintenance-cost",
    slug: "pool-maintenance-cost",
    name: lang === "TH" ? "คำนวณค่าดูแลสระว่ายน้ำ" : "Pool Maintenance Cost Calculator",
    desc: lang === "TH" ? "ประเมินค่าใช้จ่ายในการดูแลรักษาสระว่ายน้ำรายเดือนและรายปี ทั้งค่าสารเคมี ไฟฟ้า น้ำ และบริการทำความสะอาด" : "Estimate monthly and yearly pool maintenance costs including chemicals, electricity, water, and cleaning services.",
    category: "Family",
    icon: Icons.Waves
  },
  {
    id: "roof-replacement-cost",
    slug: "roof-replacement-cost",
    name: lang === "TH" ? "คำนวณค่าเปลี่ยนหลังคาบ้าน" : "Roof Replacement Cost Calculator",
    desc: lang === "TH" ? "ประเมินงบประมาณในการรื้อถอนและเปลี่ยนหลังคาใหม่ ตามพื้นที่และประเภทของวัสดุหลังคา" : "Estimate the budget for roof replacement including demolition and new materials based on roof area.",
    category: "Construction",
    icon: Icons.Home
  },
  {
    id: "car-comparison",
    slug: "car-comparison",
    name: lang === "TH" ? "เปรียบเทียบรถยนต์ 2 คัน (ค่าใช้จ่าย)" : "Car Comparison Calculator",
    desc: lang === "TH" ? "เปรียบเทียบค่าใช้จ่ายรายปีและการผ่อนชำระของรถยนต์ 2 คัน เพื่อประกอบการตัดสินใจ" : "Compare annual costs and loan payments of 2 cars to make a better decision.",
    category: "Finance",
    icon: Icons.ArrowRightLeft
  },
  {
    id: "car-depreciation",
    slug: "car-depreciation",
    name: lang === "TH" ? "คำนวณค่าเสื่อมราคารถ" : "Car Depreciation Calculator",
    desc: lang === "TH" ? "คำนวณและประเมินมูลค่ารถยนต์ที่ลดลงตามกาลเวลา (Depreciation) พร้อมตารางแสดงมูลค่ารายปี" : "Estimate the declining value of a car over time with a yearly depreciation table.",
    category: "Finance",
    icon: Icons.TrendingDown
  },
  {
    id: "car-insurance",
    slug: "car-insurance",
    name: lang === "TH" ? "คำนวณค่าประกันรถยนต์" : "Car Insurance Calculator",
    desc: lang === "TH" ? "ประเมินค่าประกันภัยรถยนต์รายปี รวมพ.ร.บ. และตัวเลือกเสริมต่างๆ" : "Estimate annual car insurance premiums including compulsory insurance and add-ons.",
    category: "Finance",
    icon: Icons.Shield
  },
  {
    id: "car-maintenance",
    slug: "car-maintenance",
    name: lang === "TH" ? "คำนวณค่าบำรุงรักษารถยนต์" : "Car Maintenance Cost Calculator",
    desc: lang === "TH" ? "ประมาณการค่าใช้จ่ายในการซ่อมบำรุงรถยนต์รายปี ตามรอบระยะทาง เช่น น้ำมันเครื่อง ยาง แบตเตอรี่" : "Estimate annual maintenance costs including oil, tires, and battery replacements based on mileage.",
    category: "Finance",
    icon: Icons.Wrench
  },
  {
    id: "car-tco",
    slug: "car-tco",
    name: lang === "TH" ? "เครื่องคำนวณต้นทุนความเป็นเจ้าของรถ TCO" : "Car Total Cost of Ownership (TCO) Calculator",
    desc: lang === "TH" ? "คำนวณต้นทุนทั้งหมดในการเป็นเจ้าของรถยนต์ ทั้งค่าผ่อน ค่าน้ำมัน ค่าบำรุงรักษา และค่าเสื่อมราคา" : "Calculate the total cost of owning a car including loan, fuel, maintenance, and depreciation.",
    category: "Finance",
    icon: Icons.CarFront
  },
  {
    id: "ev-cost-per-km",
    slug: "ev-cost-per-km",
    name: lang === "TH" ? "ค่าใช้จ่ายรถ EV ต่อกม." : "EV Cost per KM Calculator",
    desc: lang === "TH" ? "เปรียบเทียบค่าใช้จ่ายพลังงานต่อกิโลเมตร ระหว่างรถยนต์ไฟฟ้า (EV) และรถน้ำมันสันดาป (ICE)" : "Compare energy cost per kilometer between Electric Vehicles (EV) and Internal Combustion Engine (ICE) cars.",
    category: "Finance",
    icon: Icons.Zap
  },
  {
    id: "ev-ice-breakeven",
    slug: "ev-ice-breakeven",
    name: lang === "TH" ? "คำนวณจุดคุ้มทุนรถ EV" : "EV vs ICE Break-even",
    desc: lang === "TH" ? "เปรียบเทียบว่าต้องใช้รถ EV กี่ปี ถึงจะคุ้มส่วนต่างราคาเมื่อเทียบกับรถน้ำมัน" : "Calculate how many years it takes for an EV's fuel savings to offset its higher purchase price.",
    category: "Finance",
    icon: Icons.Scale
  },
  {
    id: "motorcycle-loan",
    slug: "motorcycle-loan",
    name: lang === "TH" ? "คำนวณค่าผ่อนรถมอเตอร์ไซค์" : "Motorcycle Loan Calculator",
    desc: lang === "TH" ? "คำนวณค่างวดรถมอเตอร์ไซค์ ดอกเบี้ยคงที่ต่อเดือน/ต่อปี พร้อมตารางการผ่อนชำระ" : "Calculate motorcycle loan monthly payments with flat interest rates (monthly/yearly).",
    category: "Finance",
    icon: Icons.Bike
  },
  {
    id: "rider-roi",
    slug: "rider-roi",
    name: lang === "TH" ? "คำนวณรายได้จุดคุ้มทุนไรเดอร์" : "Rider ROI & Income Calculator",
    desc: lang === "TH" ? "คำนวณรายได้สุทธิและระยะเวลาคืนทุน (ROI) สำหรับอาชีพขับรถส่งอาหาร (Grab, Lineman, Foodpanda)" : "Calculate net income and ROI payback period for food delivery riders.",
    category: "Finance",
    icon: Icons.Bike
  },
  {
    id: "truck-cost",
    slug: "truck-cost",
    name: lang === "TH" ? "คำนวณต้นทุนรถบรรทุกขนส่ง" : "Truck Operating Cost",
    desc: lang === "TH" ? "คำนวณต้นทุนการวิ่งรถบรรทุกต่อเที่ยวและต่อกิโลเมตร รวมถึงค่าน้ำมันและค่าจ้างคนขับ" : "Calculate truck operating cost per trip and per kilometer, including fuel and driver wages.",
    category: "Finance",
    icon: Icons.Truck
  },
  {
    id: "annual-commute-cost-calculator",
    slug: "annual-commute-cost-calculator",
    name: lang === "TH" ? "เครื่องคำนวณระยะทางและค่าใช้จ่ายไป-กลับทำงานต่อปี" : "Annual Commute Cost Calculator",
    desc: lang === "TH" ? "คำนวณค่าใช้จ่ายและระยะทางรวมที่คุณใช้ในการเดินทางไปทำงานตลอดทั้งปี" : "Calculate the total distance and cost of your annual commute.",
    category: "Travel",
    icon: Icons.MapPin
  },
  {
    id: "car-pool-savings-calculator",
    slug: "car-pool-savings-calculator",
    name: lang === "TH" ? "เครื่องคิดเลขค่าใช้จ่าย Car Pool" : "Car Pool Savings Calculator",
    desc: lang === "TH" ? "คำนวณค่าใช้จ่ายและเงินที่ประหยัดได้จากการนั่งรถตู้คาร์พูลหรือเดินทางไปทำงานด้วยกัน" : "Calculate costs and savings from carpooling.",
    category: "Travel",
    icon: Icons.Users
  },
  {
    id: "monthly-parking-cost-calculator",
    slug: "monthly-parking-cost-calculator",
    name: lang === "TH" ? "เครื่องคิดเลขค่าใช้จ่ายที่จอดรถรายเดือน" : "Monthly Parking Cost Calculator",
    desc: lang === "TH" ? "คำนวณและเปรียบเทียบค่าที่จอดรถแบบรายวันกับรายเดือน แบบไหนคุ้มค่ากว่ากัน" : "Compare daily vs monthly parking costs to find the best deal.",
    category: "Travel",
    icon: Icons.Car
  },
  {
    id: "monthly-toll-fee-calculator",
    slug: "monthly-toll-fee-calculator",
    name: lang === "TH" ? "เครื่องคิดเลขค่าทางด่วน/ค่าผ่านทางต่อเดือน" : "Monthly Toll Fee Calculator",
    desc: lang === "TH" ? "คำนวณค่าใช้จ่ายทางด่วน ค่าผ่านทางมอเตอร์เวย์ ต่อเดือนและต่อปี เพื่อการวางแผนเติมเงิน EasyPass/M-Flow" : "Calculate your monthly and annual toll fees for better budget planning.",
    category: "Travel",
    icon: Icons.Navigation
  },
  {
    id: "ride-hailing-vs-own-car-cost-calculator",
    slug: "ride-hailing-vs-own-car-cost-calculator",
    name: lang === "TH" ? "เปรียบเทียบค่าใช้จ่าย เรียกรถ vs รถส่วนตัว" : "Ride Hailing vs Own Car Cost Calculator",
    desc: lang === "TH" ? "คำนวณและเปรียบเทียบว่าการใช้แอปเรียกรถ (Grab/Uber) หรือการซื้อรถยนต์ส่วนตัว แบบไหนคุ้มค่ากว่ากัน" : "Compare the true costs of using ride-hailing services versus owning a car.",
    category: "Travel",
    icon: Icons.CarFront
  },
  {
    id: "break-even-time",
    slug: "break-even-time-calculator",
    name: lang === "TH" ? "ระยะเวลาคืนทุน" : "Break-Even Time",
    desc: lang === "TH" ? "คำนวณระยะเวลา (เดือน) ที่ธุรกิจจะคืนทุนจากกระแสเงินสด" : "Calculate months to payback initial investment",
    category: "Finance",
    icon: Icons.Clock
  },
  {
    id: "capacity-utilization-rate",
    slug: "capacity-utilization-rate-calculator",
    name: lang === "TH" ? "อัตราการใช้กำลังการผลิต" : "Capacity Utilization Rate",
    desc: lang === "TH" ? "คำนวณประสิทธิภาพการใช้ทรัพยากรเทียบกับขีดจำกัดสูงสุด" : "Calculate output relative to potential maximum capacity",
    category: "Business",
    icon: Icons.Activity
  },
  {
    id: "cash-flow-projection",
    slug: "12-month-cash-flow-projection",
    name: lang === "TH" ? "ประมาณการกระแสเงินสด 12 เดือน" : "12-Month Cash Flow Projection",
    desc: lang === "TH" ? "วางแผนและคาดการณ์กระแสเงินสดรับจ่ายรายเดือน" : "Forecast monthly cash inflows and outflows",
    category: "Finance",
    icon: Icons.LineChart
  },
  {
    id: "cost-per-unit",
    slug: "manufacturing-cost-per-unit-calculator",
    name: lang === "TH" ? "ต้นทุนต่อหน่วย (ผลิต)" : "Cost per Unit",
    desc: lang === "TH" ? "คำนวณต้นทุนรวมต่อการผลิตสินค้า 1 ชิ้น" : "Calculate total manufacturing cost per unit",
    category: "Business",
    icon: Icons.Factory
  },
  {
    id: "double-declining-depreciation",
    slug: "double-declining-depreciation-calculator",
    name: lang === "TH" ? "ค่าเสื่อมราคาแบบยอดลดลงทวีคูณ" : "Double Declining Balance Depreciation",
    desc: lang === "TH" ? "คำนวณตารางค่าเสื่อมราคาสินทรัพย์แบบเร่งรัด" : "Calculate accelerated depreciation schedule",
    category: "Finance",
    icon: Icons.TrendingDown
  },
  {
    id: "working-capital",
    slug: "working-capital-calculator",
    name: lang === "TH" ? "เงินทุนหมุนเวียนสุทธิ" : "Working Capital",
    desc: lang === "TH" ? "คำนวณเงินทุนหมุนเวียนและอัตราส่วนสภาพคล่อง" : "Calculate net working capital and current ratio",
    category: "Finance",
    icon: Icons.Briefcase
  },
  {
    id: "wholesale-vs-retail-margin",
    slug: "wholesale-retail-margin-calculator",
    name: lang === "TH" ? "คำนวณราคาส่งและราคาปลีก" : "Wholesale vs Retail Margin",
    desc: lang === "TH" ? "คำนวณโครงสร้างราคาขายและอัตรากำไรสำหรับผู้ผลิตและร้านค้า" : "Calculate wholesale and retail prices based on margin",
    category: "Business",
    icon: Icons.Tags
  },
  {
    id: "retail-space-rent-roi",
    slug: "retail-space-rent-roi-calculator",
    name: lang === "TH" ? "ความคุ้มค่าค่าเช่าพื้นที่" : "Retail Space Rent ROI",
    desc: lang === "TH" ? "ประเมินจุดคุ้มทุนและกำไรจากการเช่าหน้าร้าน" : "Evaluate break-even sales and ROI for renting retail space",
    category: "Business",
    icon: Icons.Store
  },
  {
    id: "simplified-p-and-l",
    slug: "simplified-profit-and-loss-calculator",
    name: lang === "TH" ? "งบกำไรขาดทุนอย่างง่าย" : "Simplified P&L",
    desc: lang === "TH" ? "คำนวณงบกำไรขาดทุนและอัตรากำไรสุทธิ" : "Calculate simplified profit and loss statement",
    category: "Finance",
    icon: Icons.FileText
  },
  {
    id: "freelance-vs-fulltime-cost",
    slug: "freelance-vs-fulltime-cost-calculator",
    name: lang === "TH" ? "เปรียบเทียบฟรีแลนซ์และพนักงาน" : "Freelance vs Full-time Cost",
    desc: lang === "TH" ? "คำนวณและเปรียบเทียบต้นทุนแฝงในการจ้างงาน" : "Compare true costs of hiring freelance vs full-time",
    category: "Business",
    icon: Icons.UserCheck
  },
  {
    id: "company-registration-cost",
    slug: "company-registration-cost-calculator",
    name: lang === "TH" ? "คำนวณค่าธรรมเนียมจดทะเบียนบริษัท" : "Company Registration Cost Calculator",
    desc: lang === "TH" ? "คำนวณค่าธรรมเนียมรัฐและอากรแสตมป์เบื้องต้นในการจดทะเบียนตั้งบริษัท" : "Calculate government fees and stamp duty for company registration",
    category: "Business",
    icon: Icons.Building2
  },
  {
    id: "corporate-tax",
    slug: "corporate-tax-calculator",
    name: lang === "TH" ? "คำนวณภาษีเงินได้นิติบุคคล" : "Corporate Tax Calculator",
    desc: lang === "TH" ? "คำนวณภาษีเงินได้นิติบุคคลสำหรับ SME และบริษัททั่วไป" : "Calculate corporate income tax for SME and general companies",
    category: "Finance",
    icon: Icons.Calculator
  },
  {
    id: "credit-card-mdr-fee",
    slug: "credit-card-mdr-fee-calculator",
    name: lang === "TH" ? "คำนวณค่าธรรมเนียมรูดบัตร (MDR)" : "Credit Card MDR Fee Calculator",
    desc: lang === "TH" ? "คำนวณผลกระทบของค่าธรรมเนียมรูดบัตรเครดิตที่มีต่อกำไรของร้านค้า" : "Calculate the impact of Merchant Discount Rate (MDR) on store profit",
    category: "Finance",
    icon: Icons.CreditCard
  },
  {
    id: "de-ratio",
    slug: "de-ratio-calculator",
    name: lang === "TH" ? "คำนวณอัตราส่วนหนี้สินต่อทุน (D/E)" : "Debt-to-Equity Ratio Calculator",
    desc: lang === "TH" ? "คำนวณอัตราส่วนหนี้สินต่อทุน (D/E Ratio) เพื่อประเมินความเสี่ยงทางการเงิน" : "Calculate Debt-to-Equity Ratio to assess financial risk",
    category: "Finance",
    icon: Icons.Scale
  },
  {
    id: "legal-reserve",
    slug: "legal-reserve-calculator",
    name: lang === "TH" ? "คำนวณทุนสำรองตามกฎหมาย" : "Legal Reserve Calculator",
    desc: lang === "TH" ? "คำนวณเงินสำรองตามกฎหมายที่บริษัทต้องจัดสรรเมื่อมีกำไร" : "Calculate the legal reserve required by law when a company makes a profit",
    category: "Finance",
    icon: Icons.PiggyBank
  },
  {
    id: "markup-imported-materials",
    slug: "markup-imported-materials-calculator",
    name: lang === "TH" ? "คำนวณต้นทุนและราคาขายสินค้านำเข้า" : "Imported Material Markup Calculator",
    desc: lang === "TH" ? "คำนวณต้นทุนสินค้านำเข้ารวมภาษีและบวกกำไรเพื่อตั้งราคาขาย" : "Calculate total cost of imported goods including duty and add markup for selling price",
    category: "Business",
    icon: Icons.Package
  },
  {
    id: "pos-system-comparison",
    slug: "pos-system-comparison",
    name: lang === "TH" ? "เปรียบเทียบต้นทุนระบบ POS" : "POS System Comparison",
    desc: lang === "TH" ? "เปรียบเทียบต้นทุนรายปีของระบบ POS แบบซื้อขาด vs แบบเช่า/หัก GP" : "Compare annual cost of POS systems (Upfront vs Subscription/GP)",
    category: "Business",
    icon: Icons.MonitorSmartphone
  },
  {
    id: "quick-current-ratio",
    slug: "quick-current-ratio-calculator",
    name: lang === "TH" ? "คำนวณอัตราส่วนสภาพคล่อง" : "Quick & Current Ratio Calculator",
    desc: lang === "TH" ? "คำนวณ Current Ratio และ Quick Ratio เพื่อประเมินสภาพคล่องระยะสั้น" : "Calculate Current and Quick Ratios to assess short-term liquidity",
    category: "Finance",
    icon: Icons.Activity
  },
  {
    id: "roe-roa-roic",
    slug: "roe-roa-roic-calculator",
    name: lang === "TH" ? "คำนวณ ROE / ROA / ROIC" : "ROE / ROA / ROIC Calculator",
    desc: lang === "TH" ? "คำนวณอัตราผลตอบแทนจากสินทรัพย์ ผู้ถือหุ้น และเงินทุน" : "Calculate Return on Equity, Return on Assets, and Return on Invested Capital",
    category: "Finance",
    icon: Icons.TrendingUp
  },
  {
    id: "sales-commission-structure",
    slug: "sales-commission-structure",
    name: lang === "TH" ? "คำนวณค่าคอมมิชชั่นพนักงานขาย" : "Sales Commission Structure Calculator",
    desc: lang === "TH" ? "คำนวณค่าคอมมิชชั่นแบบ Flat Rate และแบบขั้นบันได (Tiered)" : "Calculate flat rate and tiered sales commission structure",
    category: "Business",
    icon: Icons.Target
  },
  {
    id: "dio",
    slug: "days-inventory-outstanding-calculator",
    name: lang === "TH" ? "คำนวณระยะเวลาขายสินค้าเฉลี่ย (DIO)" : "DIO Calculator",
    desc: lang === "TH" ? "คำนวณ Days Inventory Outstanding (DIO) ระยะเวลาที่สินค้าค้างในสต็อกก่อนขายออก" : "Calculate Days Inventory Outstanding to track how long inventory stays in stock.",
    category: "Finance",
    icon: Icons.Warehouse
  },
  {
    id: "dso",
    slug: "days-sales-outstanding-calculator",
    name: lang === "TH" ? "คำนวณระยะเวลาเก็บหนี้ (DSO)" : "DSO Calculator",
    desc: lang === "TH" ? "คำนวณ Days Sales Outstanding (DSO) หรือระยะเวลาเก็บหนี้เฉลี่ย เพื่อวิเคราะห์สภาพคล่องของธุรกิจ" : "Calculate Days Sales Outstanding to analyze your business liquidity and collection efficiency.",
    category: "Finance",
    icon: Icons.CalendarClock
  },
  {
    id: "employee-bonus",
    slug: "employee-bonus-calculator",
    name: lang === "TH" ? "คำนวณโบนัสพนักงาน (อิงผลงาน)" : "Employee Bonus Calculation",
    desc: lang === "TH" ? "คำนวณโบนัสสิ้นปีโดยใช้ระบบตัวคูณตามผลประกอบการบริษัทและผลงานส่วนบุคคล (KPI)" : "Calculate year-end bonus using performance multipliers for company and individual KPIs.",
    category: "Business",
    icon: Icons.Gift
  },
  {
    id: "expense-ratio",
    slug: "expense-ratio-calculator",
    name: lang === "TH" ? "คำนวณอัตราส่วนค่าใช้จ่าย (Expense Ratio)" : "Expense Ratio Calculator",
    desc: lang === "TH" ? "คำนวณสัดส่วนค่าใช้จ่ายดำเนินงานต่อรายได้รวม (OER) เพื่อวิเคราะห์ประสิทธิภาพการคุมต้นทุน" : "Calculate the Operating Expense Ratio to analyze cost efficiency against total revenue.",
    category: "Finance",
    icon: Icons.PieChart
  },
  {
    id: "gmv-vs-net-revenue",
    slug: "gmv-vs-net-revenue-calculator",
    name: lang === "TH" ? "คำนวณยอดขายแพลตฟอร์ม (GMV vs Net)" : "GMV vs Net Revenue Calculator",
    desc: lang === "TH" ? "แปลงตัวเลขยอดขายรวม (GMV) ให้เป็นรายได้สุทธิ (Net Revenue) หลังหักค่าธรรมเนียมและส่วนลด" : "Convert Gross Merchandise Value (GMV) to true Net Revenue by deducting platform fees.",
    category: "Business",
    icon: Icons.ShoppingCart
  },
  {
    id: "headcount-to-sales",
    slug: "optimal-headcount-sales-calculator",
    name: lang === "TH" ? "คำนวณจำนวนพนักงานขายที่เหมาะสม" : "Optimal Headcount to Sales",
    desc: lang === "TH" ? "คำนวณว่าต้องจ้างพนักงานขายเพิ่มอีกกี่คน เพื่อให้บรรลุเป้าหมายยอดขายใหม่ที่ตั้งไว้" : "Calculate how many sales reps you need to hire to hit your target revenue.",
    category: "Business",
    icon: Icons.Users
  },
  {
    id: "inventory-costing",
    slug: "inventory-costing-fifo-avco",
    name: lang === "TH" ? "คำนวณต้นทุนสินค้า FIFO vs ถัวเฉลี่ย" : "Inventory Costing (FIFO vs AVCO)",
    desc: lang === "TH" ? "เปรียบเทียบการตีราคาต้นทุนสินค้าคงคลังแบบเข้าก่อนออกก่อน (FIFO) กับแบบต้นทุนถัวเฉลี่ย (AVCO)" : "Compare Cost of Goods Sold and Ending Inventory using FIFO and Average Cost (AVCO) methods.",
    category: "Finance",
    icon: Icons.Layers
  },
  {
    id: "landed-cost",
    slug: "landed-cost-calculator",
    name: lang === "TH" ? "คำนวณต้นทุนสินค้านำเข้า" : "Landed Cost Calculator",
    desc: lang === "TH" ? "คำนวณต้นทุนสินค้านำเข้ารวมค่าขนส่ง ภาษี และค่าธรรมเนียม เพื่อหาราคาต้นทุนต่อชิ้นที่แท้จริง" : "Calculate the true cost of imported goods including shipping, taxes, and fees.",
    category: "Finance",
    icon: Icons.Ship
  },
  {
    id: "office-vs-wfh",
    slug: "office-vs-wfh-calculator",
    name: lang === "TH" ? "เปรียบเทียบต้นทุน ออฟฟิศ vs WFH" : "Office vs WFH Cost Saving",
    desc: lang === "TH" ? "คำนวณเงินที่องค์กรประหยัดได้จากการให้พนักงาน Work From Home เทียบกับการเช่าออฟฟิศ" : "Calculate the money saved by transitioning from a traditional office to a Work From Home model.",
    category: "Business",
    icon: Icons.Building
  },
  {
    id: "packaging-cost",
    slug: "packaging-cost-calculator",
    name: lang === "TH" ? "คำนวณต้นทุนบรรจุภัณฑ์ต่อชิ้น" : "Packaging Cost per Unit",
    desc: lang === "TH" ? "คำนวณต้นทุนบรรจุภัณฑ์ทั้งหมดที่ใช้ต่อสินค้า 1 ชิ้น รวมถึงกล่อง ฉลาก และค่าแรงแพ็ค" : "Calculate the total packaging cost used per 1 item including box, labels, and labor.",
    category: "Business",
    icon: Icons.Package
  },
  {
    id: "advertising-budget-allocation",
    slug: "advertising-budget-allocation",
    name: lang === "TH" ? "คำนวณสัดส่วนงบโฆษณา (Ad Budget Allocation)" : "Advertising Budget Allocation",
    desc: lang === "TH" ? "คำนวณและจัดสรรงบประมาณโฆษณาเพื่อสร้างยอดขายตามเป้าหมาย (ROAS)" : "Calculate and allocate advertising budget to achieve sales target (ROAS)",
    category: "Business",
    icon: Icons.Megaphone
  },
  {
    id: "cac-payback-period",
    slug: "cac-payback-period-calculator",
    name: lang === "TH" ? "คำนวณระยะเวลาคืนทุนของลูกค้า (CAC Payback)" : "CAC Payback Period Calculator",
    desc: lang === "TH" ? "คำนวณระยะเวลาที่ใช้ในการคืนทุนค่าใช้จ่ายในการได้ลูกค้าใหม่ (CAC) สำหรับธุรกิจ Subscription หรือ SaaS" : "Calculate the months required to recover Customer Acquisition Cost for subscription businesses",
    category: "Business",
    icon: Icons.Repeat
  },
  {
    id: "ebitda-calculator",
    slug: "ebitda-calculator",
    name: lang === "TH" ? "คำนวณ EBITDA" : "EBITDA Calculator",
    desc: lang === "TH" ? "คำนวณกำไรก่อนหักดอกเบี้ย ภาษี ค่าเสื่อมราคา และค่าตัดจำหน่าย เพื่อประเมินผลการดำเนินงาน" : "Calculate Earnings Before Interest, Taxes, Depreciation, and Amortization",
    category: "Finance",
    icon: Icons.BarChart3
  },
  {
    id: "employee-ot-calculation",
    slug: "employee-ot-calculator",
    name: lang === "TH" ? "คำนวณค่าล่วงเวลา (OT)" : "Employee OT Calculator",
    desc: lang === "TH" ? "คำนวณค่าล่วงเวลาและค่าทำงานในวันหยุดตามกฎหมายแรงงานไทย" : "Calculate overtime pay based on Thai labor laws",
    category: "Business",
    icon: Icons.Clock
  },
  {
    id: "employer-social-security",
    slug: "employer-social-security-calculator",
    name: lang === "TH" ? "คำนวณเงินสมทบประกันสังคม (นายจ้าง)" : "Employer Social Security Cost Calculator",
    desc: lang === "TH" ? "คำนวณภาระต้นทุนเงินสมทบประกันสังคมและกองทุนเงินทดแทนในมุมมองของนายจ้าง" : "Calculate employer contributions to Social Security and Workmen's Compensation Fund",
    category: "Business",
    icon: Icons.ShieldPlus
  },
  {
    id: "fx-forward-rate-risk",
    slug: "fx-forward-rate-calculator",
    name: lang === "TH" ? "คำนวณอัตราแลกเปลี่ยนล่วงหน้า (FX Forward)" : "FX Forward Rate Calculator",
    desc: lang === "TH" ? "คำนวณและประเมินความเสี่ยงอัตราแลกเปลี่ยนด้วยสัญญา Forward" : "Calculate and assess foreign exchange risk with Forward contracts",
    category: "Finance",
    icon: Icons.LineChart
  },
  {
    id: "international-shipping-cost",
    slug: "international-shipping-cost-calculator",
    name: lang === "TH" ? "คำนวณต้นทุนการนำเข้า/ส่งออก (EXW/FOB/CIF)" : "International Shipping Cost Calculator (EXW/FOB/CIF)",
    desc: lang === "TH" ? "คำนวณและเปรียบเทียบต้นทุนการขนส่งสินค้าระหว่างประเทศตามเงื่อนไข Incoterms (EXW, FOB, CIF)" : "Calculate and compare international shipping costs based on Incoterms (EXW, FOB, CIF)",
    category: "Business",
    icon: Icons.Ship
  },
  {
    id: "minimum-wage-province",
    slug: "minimum-wage-thailand-calculator",
    name: lang === "TH" ? "คำนวณและเปรียบเทียบค่าแรงขั้นต่ำรายจังหวัด" : "Minimum Wage by Province Calculator",
    desc: lang === "TH" ? "คำนวณฐานเงินเดือนและเปรียบเทียบค่าแรงขั้นต่ำของแต่ละจังหวัดในประเทศไทย" : "Calculate and compare minimum wages across provinces in Thailand",
    category: "Business",
    icon: Icons.MapPin
  },
  {
    id: "severance-pay-calculation",
    slug: "severance-pay-calculator",
    name: lang === "TH" ? "คำนวณเงินชดเชยเลิกจ้าง" : "Severance Pay Calculator",
    desc: lang === "TH" ? "คำนวณเงินชดเชยเมื่อถูกเลิกจ้างตามอายุงานและกฎหมายแรงงานไทย" : "Calculate severance pay based on tenure and Thai labor laws",
    category: "Business",
    icon: Icons.Briefcase
  },
  {
    id: "warehouse-rent-vs-buy",
    slug: "warehouse-rent-vs-buy-calculator",
    name: lang === "TH" ? "คำนวณเช่า vs ซื้อคลังสินค้า" : "Warehouse Rent vs Buy Calculator",
    desc: lang === "TH" ? "เปรียบเทียบความคุ้มค่าทางการเงินระหว่างการเช่าคลังสินค้ากับการลงทุนสร้าง/ซื้อเองในระยะยาว" : "Compare financial viability between renting a warehouse and building/buying one for long-term",
    category: "Business",
    icon: Icons.Warehouse
  },
  {
    id: "acceptable-cpc",
    slug: "acceptable-cpc-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณ Acceptable CPC (ต้นทุนต่อคลิกที่ยอมรับได้)" : "Acceptable CPC Calculator",
    desc: lang === "TH" ? "คำนวณหาค่า CPC สูงสุดที่คุณสามารถจ่ายได้โดยไม่ขาดทุน จาก Conversion Rate และกำไรต่อออเดอร์" : "Calculate the maximum CPC you can afford based on your conversion rate and profit per order.",
    category: "Business",
    icon: Icons.MousePointerClick
  },
  {
    id: "cagr",
    slug: "cagr-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณอัตราการเติบโต (CAGR)" : "CAGR Calculator",
    desc: lang === "TH" ? "คำนวณอัตราการเติบโตเฉลี่ยต่อปีแบบทบต้น (Compound Annual Growth Rate) เพื่อประเมินผลตอบแทนหรือธุรกิจระยะยาว" : "Calculate the Compound Annual Growth Rate (CAGR) to measure smooth investment return or business growth over multiple years.",
    category: "Finance",
    icon: Icons.TrendingUp
  },
  {
    id: "factory-electricity",
    slug: "factory-electricity-calculator",
    name: lang === "TH" ? "เครื่องมือเปรียบเทียบค่าไฟ TOU (ธุรกิจ/โรงงาน)" : "Factory Electricity TOU Calculator",
    desc: lang === "TH" ? "เปรียบเทียบค่าไฟฟ้าสำหรับธุรกิจและโรงงาน ระหว่างอัตราปกติ (Flat Rate) และอัตราตามช่วงเวลา (TOU) เพื่อวางแผนลดต้นทุน" : "Compare business electricity costs between standard flat rates and Time of Use (TOU) rates to optimize overhead expenses.",
    category: "Business",
    icon: Icons.Zap
  },
  {
    id: "franchise-cost",
    slug: "franchise-cost-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณงบลงทุนเปิดแฟรนไชส์ (Total Franchise Cost)" : "Franchise Cost Calculator",
    desc: lang === "TH" ? "คำนวณเงินลงทุนรวมทั้งหมดในการซื้อและเปิดร้านแฟรนไชส์ (ค่าธรรมเนียม, ค่าก่อสร้าง, อุปกรณ์ และเงินทุนหมุนเวียนสำรอง)" : "Calculate the total initial investment required to open a franchise business including fees, build-out, and working capital.",
    category: "Business",
    icon: Icons.Store
  },
  {
    id: "gross-margin-sku",
    slug: "gross-margin-sku-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณกำไรขั้นต้นต่อสินค้า (Gross Margin per SKU)" : "Gross Margin per SKU Calculator",
    desc: lang === "TH" ? "คำนวณกำไรขั้นต้นและอัตรากำไร (Gross Margin %) ของสินค้าแต่ละรายการ เพื่อวิเคราะห์ความคุ้มค่าก่อนตั้งราคาขาย" : "Calculate the Gross Margin percentage and gross profit per SKU to analyze product profitability before pricing.",
    category: "Finance",
    icon: Icons.Package
  },
  {
    id: "nps",
    slug: "nps-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณ Net Promoter Score (NPS)" : "NPS Calculator",
    desc: lang === "TH" ? "คำนวณคะแนนความพึงพอใจและวัดความภักดีของลูกค้าที่มีต่อแบรนด์จากผลสำรวจ (NPS)" : "Calculate your Net Promoter Score (NPS) based on customer survey results to gauge brand loyalty and customer satisfaction.",
    category: "Business",
    icon: Icons.Smile
  },
  {
    id: "real-estate-broker-fee",
    slug: "real-estate-broker-fee-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณค่านายหน้าอสังหาฯ" : "Real Estate Broker Fee Calculator",
    desc: lang === "TH" ? "คำนวณค่านายหน้า (คอมมิชชั่น) อสังหาริมทรัพย์ พร้อมคำนวณภาษีมูลค่าเพิ่ม (VAT) และภาษีหัก ณ ที่จ่าย (WHT)" : "Calculate real estate agent commission fees including VAT and Withholding Tax.",
    category: "Business",
    icon: Icons.Home
  },
  {
    id: "return-rate-impact",
    slug: "return-rate-impact-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณต้นทุนการคืนสินค้า (Return Rate Impact)" : "Cost of Returns Calculator",
    desc: lang === "TH" ? "คำนวณผลกระทบและมูลค่าความเสียหายที่เกิดจากอัตราการคืนสินค้า (Return/COD ตีกลับ) ที่มีต่อกำไรสุทธิของคุณ" : "Calculate the financial impact and hidden costs of your product return rate on overall business profitability.",
    category: "Finance",
    icon: Icons.RotateCcw
  },
  {
    id: "roas",
    slug: "roas-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณ ROAS (ผลตอบแทนจากโฆษณา)" : "ROAS Calculator",
    desc: lang === "TH" ? "คำนวณ Return on Ad Spend ประเมินว่าค่าแอดที่จ่ายไปสร้างยอดขายกลับมาได้กี่เท่า พร้อมหาจุดคุ้มทุน (Break-even ROAS)" : "Calculate the Return on Ad Spend (ROAS) to evaluate the effectiveness of your advertising campaigns and find break-even point.",
    category: "Finance",
    icon: Icons.Target
  },
  {
    id: "saas-mrr-arr",
    slug: "saas-mrr-arr-calculator",
    name: lang === "TH" ? "เครื่องมือคำนวณ MRR และ ARR (SaaS/Subscription)" : "SaaS MRR & ARR Calculator",
    desc: lang === "TH" ? "คำนวณรายได้ประจำรายเดือน (MRR) และรายได้ประจำรายปี (ARR) ของธุรกิจรูปแบบสมัครสมาชิก" : "Calculate Monthly Recurring Revenue (MRR) and Annual Recurring Revenue (ARR) for Subscription and SaaS businesses.",
    category: "Business",
    icon: Icons.Repeat
  },
  {
    id: "break-even-by-channel",
    slug: "break-even-by-channel",
    name: lang === "TH" ? "จุดคุ้มทุนแยกช่องทาง" : "Break-even by Channel",
    desc: lang === "TH" ? "เปรียบเทียบจุดคุ้มทุนระหว่างการขายหน้าร้าน (Retail) และออนไลน์ (Online)" : "Compare break-even points between retail and online sales channels.",
    category: "Business",
    icon: Icons.Store
  },
  {
    id: "carbon-credit-cost",
    slug: "carbon-credit-cost-calculator",
    name: lang === "TH" ? "คำนวณต้นทุนคาร์บอนเครดิต" : "Carbon Credit Cost Calculator",
    desc: lang === "TH" ? "คำนวณต้นทุนการซื้อหรือชดเชยคาร์บอนเครดิตสำหรับธุรกิจ" : "Calculate the cost of purchasing or offsetting carbon credits for business.",
    category: "Business",
    icon: Icons.Leaf
  },
  {
    id: "event-cost-per-attendee",
    slug: "event-cost-per-attendee",
    name: lang === "TH" ? "คำนวณต้นทุนงานอีเวนต์ต่อหัว" : "Event Cost per Attendee Calculator",
    desc: lang === "TH" ? "ประเมินต้นทุนรวมและต้นทุนต่อหัวในการจัดงานอีเวนต์" : "Estimate total event cost and cost per attendee.",
    category: "Business",
    icon: Icons.Users
  },
  {
    id: "iso-certification-cost",
    slug: "iso-certification-cost",
    name: lang === "TH" ? "คำนวณต้นทุนมาตรฐาน ISO" : "ISO Certification Cost",
    desc: lang === "TH" ? "ประเมินค่าใช้จ่ายในการขอรับรองและรักษาระบบมาตรฐาน ISO" : "Estimate the cost of obtaining and maintaining ISO certification.",
    category: "Business",
    icon: Icons.Award
  },
  {
    id: "npv-irr",
    slug: "npv-irr-calculator",
    name: lang === "TH" ? "คำนวณ NPV และ IRR" : "NPV & IRR Calculator",
    desc: lang === "TH" ? "ประเมินมูลค่าปัจจุบันสุทธิ (NPV) และอัตราผลตอบแทนภายใน (IRR) ของโครงการ" : "Calculate Net Present Value and Internal Rate of Return for projects.",
    category: "Finance",
    icon: Icons.TrendingUp
  },
  {
    id: "patent-cost",
    slug: "patent-cost-calculator",
    name: lang === "TH" ? "คำนวณค่าจดสิทธิบัตรและบำรุงรักษา" : "Patent Cost Calculator",
    desc: lang === "TH" ? "คำนวณค่าใช้จ่ายในการยื่นจดสิทธิบัตรและค่าบำรุงรักษารายปี" : "Calculate patent filing fees and annual maintenance costs.",
    category: "Business",
    icon: Icons.FileBadge
  },
  {
    id: "project-payback-period",
    slug: "project-payback-period-calculator",
    name: lang === "TH" ? "คำนวณระยะเวลาคืนทุน" : "Project Payback Period",
    desc: lang === "TH" ? "คำนวณระยะเวลาคืนทุนของโครงการลงทุน (Payback Period)" : "Calculate the payback period for a project investment.",
    category: "Finance",
    icon: Icons.Clock
  },
  {
    id: "royalty-income",
    slug: "royalty-income-calculator",
    name: lang === "TH" ? "คำนวณรายได้ค่าลิขสิทธิ์" : "Royalty Income Calculator",
    desc: lang === "TH" ? "คำนวณรายได้จากค่าลิขสิทธิ์และการหักภาษี ณ ที่จ่าย" : "Calculate royalty income and withholding tax deductions.",
    category: "Finance",
    icon: Icons.Coins
  },
  {
    id: "sensitivity-analysis",
    slug: "sensitivity-analysis-calculator",
    name: lang === "TH" ? "เครื่องมือวิเคราะห์ความอ่อนไหว" : "Sensitivity Analysis Calculator",
    desc: lang === "TH" ? "ประเมินผลกระทบของตัวแปรที่เปลี่ยนแปลงต่อผลกำไรของธุรกิจ" : "Analyze how changes in key variables impact business profit.",
    category: "Finance",
    icon: Icons.Activity
  },
  {
    id: "space-rental-deposit",
    slug: "space-rental-deposit-calculator",
    name: lang === "TH" ? "คำนวณเงินมัดจำเช่าพื้นที่" : "Space Rental Deposit",
    desc: lang === "TH" ? "คำนวณเงินมัดจำ ค่าเช่าล่วงหน้า และค่าใช้จ่ายวันทำสัญญาสำหรับพื้นที่ธุรกิจ" : "Calculate rental deposits, advance payments, and move-in costs.",
    category: "Business",
    icon: Icons.Key
  },
  {
    id: "banana-farming-calculator",
    slug: "banana-farming-calculator",
    name: lang === "TH" ? "คำนวณต้นทุน/กำไรปลูกกล้วย" : "Banana Farming Profit Calculator",
    desc: lang === "TH" ? "โปรแกรมคำนวณต้นทุน รายรับ และกำไรสุทธิจากการปลูกกล้วย (กล้วยน้ำว้า/กล้วยหอม)" : "Calculate costs, revenue, and net profit for banana farming.",
    category: "Agriculture",
    icon: Icons.Sprout
  },
  {
    id: "broiler-chicken-farm-calculator",
    slug: "broiler-chicken-farm-calculator",
    name: lang === "TH" ? "คำนวณต้นทุน/กำไรฟาร์มไก่เนื้อ" : "Broiler Chicken Farm Profit Calculator",
    desc: lang === "TH" ? "โปรแกรมประเมินรายรับ ต้นทุน และกำไรจากการเลี้ยงไก่เนื้อ (ต่อรุ่น/ต่อโรงเรือน)" : "Calculate costs, revenue, and net profit for a broiler chicken farm per batch.",
    category: "Agriculture",
    icon: Icons.Bird
  },
  {
    id: "cassava-farming-calculator",
    slug: "cassava-farming-calculator",
    name: lang === "TH" ? "คำนวณต้นทุน/กำไรปลูกมันสำปะหลัง" : "Cassava Farming Profit Calculator",
    desc: lang === "TH" ? "เครื่องมือคำนวณต้นทุน รายรับ และกำไรสุทธิจากการปลูกมันสำปะหลังต่อไร่" : "Calculate costs, revenue, and net profit for cassava farming per rai.",
    category: "Agriculture",
    icon: Icons.Sprout
  },
  {
    id: "coconut-farming-calculator",
    slug: "coconut-farming-calculator",
    name: lang === "TH" ? "คำนวณต้นทุน/กำไรปลูกมะพร้าว" : "Coconut Farming Profit Calculator",
    desc: lang === "TH" ? "โปรแกรมคำนวณรายได้ ต้นทุน และกำไรสุทธิจากสวนมะพร้าว (มะพร้าวน้ำหอม/มะพร้าวแกง)" : "Calculate costs, revenue, and net profit for coconut farming per year.",
    category: "Agriculture",
    icon: Icons.Trees
  },
  {
    id: "corn-farming-calculator",
    slug: "corn-farming-calculator",
    name: lang === "TH" ? "คำนวณต้นทุนและกำไรปลูกข้าวโพด" : "Corn Farming Profit Calculator",
    desc: lang === "TH" ? "โปรแกรมคำนวณต้นทุน รายได้ และกำไรสุทธิจากการปลูกข้าวโพด ประเมินความคุ้มค่าในการลงทุน" : "Calculate costs, revenue, and net profit for corn farming.",
    category: "Agriculture",
    icon: Icons.Tractor
  },
  {
    id: "mango-farming-calculator",
    slug: "mango-farming-calculator",
    name: lang === "TH" ? "คำนวณต้นทุน/กำไรปลูกมะม่วง" : "Mango Farming Profit Calculator",
    desc: lang === "TH" ? "โปรแกรมคำนวณรายได้ ต้นทุน และกำไรสุทธิจากสวนมะม่วงเพื่อการค้า" : "Calculate annual costs, revenue, and net profit for a commercial mango orchard.",
    category: "Agriculture",
    icon: Icons.Trees
  },
  {
    id: "oil-palm-farming-calculator",
    slug: "oil-palm-farming-calculator",
    name: lang === "TH" ? "คำนวณต้นทุน/กำไรปลูกปาล์มน้ำมัน" : "Oil Palm Farming Profit Calculator",
    desc: lang === "TH" ? "เครื่องมือคำนวณต้นทุน รายได้ และกำไรสุทธิจากสวนปาล์มน้ำมันต่อปี" : "Calculate annual costs, revenue, and net profit for oil palm farming.",
    category: "Agriculture",
    icon: Icons.Trees
  },
  {
    id: "rubber-tree-farming-calculator",
    slug: "rubber-tree-farming-calculator",
    name: lang === "TH" ? "คำนวณต้นทุน/กำไรปลูกยางพารา" : "Rubber Tree Farming Profit Calculator",
    desc: lang === "TH" ? "เครื่องมือประเมินรายรับ ต้นทุน และกำไรสุทธิจากสวนยางพาราต่อปี" : "Calculate costs, revenue, and net profit for rubber tree farming per year.",
    category: "Agriculture",
    icon: Icons.Trees
  },
  {
    id: "sugarcane-farming-calculator",
    slug: "sugarcane-farming-calculator",
    name: lang === "TH" ? "คำนวณต้นทุน/กำไรปลูกอ้อย" : "Sugarcane Farming Profit Calculator",
    desc: lang === "TH" ? "เครื่องมือประเมินรายรับ ต้นทุน และกำไรสุทธิจากการปลูกอ้อยโรงงาน" : "Calculate costs, revenue, and net profit for sugarcane farming.",
    category: "Agriculture",
    icon: Icons.Tractor
  },
  {
    id: "white-shrimp-farm-calculator",
    slug: "white-shrimp-farm-calculator",
    name: lang === "TH" ? "คำนวณต้นทุน/กำไรฟาร์มกุ้งขาว" : "White Shrimp Farm Profit Calculator",
    desc: lang === "TH" ? "โปรแกรมคำนวณต้นทุน รายได้ และกำไรจากการเลี้ยงกุ้งขาวแวนนาไม (ต่อบ่อ/ต่อรอบ)" : "Calculate costs, revenue, and net profit for white shrimp farming per pond/crop.",
    category: "Agriculture",
    icon: Icons.Fish
  },
  {
    id: "agri-chemical-mix-ratio",
    slug: "agri-chemical-mix-ratio",
    name: lang === "TH" ? "คำนวณสารเคมีเกษตรต่อถัง" : "Agri-Chemical Mix Ratio",
    desc: lang === "TH" ? "คำนวณอัตราส่วนการผสมสารเคมีเกษตร ปุ๋ย และฮอร์โมนต่อน้ำ 1 ถัง" : "Calculate the precise mixing ratio of agricultural chemicals per spray tank.",
    category: "Agriculture",
    icon: Icons.Beaker
  },
  {
    id: "beef-cattle-farm-profit-cost",
    slug: "beef-cattle-farm-profit-cost",
    name: lang === "TH" ? "ต้นทุน/กำไรฟาร์มโคเนื้อ" : "Beef Cattle Farm Profit/Cost",
    desc: lang === "TH" ? "โปรแกรมคำนวณต้นทุนค่าอาหารและประเมินกำไรสำหรับการเลี้ยงโคเนื้อ/โคขุน" : "Calculate costs and profit margin for beef cattle and fattening farms.",
    category: "Agriculture",
    icon: Icons.Activity
  },
  {
    id: "drip-irrigation-cost",
    slug: "drip-irrigation-cost",
    name: lang === "TH" ? "ระบบน้ำหยด - ออกแบบและค่าใช้จ่าย" : "Drip Irrigation Cost",
    desc: lang === "TH" ? "คำนวณความยาวเทปน้ำหยด จำนวนม้วน และประเมินต้นทุนระบบน้ำหยดต่อไร่" : "Estimate materials and costs for installing a drip irrigation system.",
    category: "Agriculture",
    icon: Icons.Waves
  },
  {
    id: "farm-area-from-gps",
    slug: "farm-area-from-gps",
    name: lang === "TH" ? "คำนวณพื้นที่เกษตรจาก GPS Coordinates" : "Farm Area from GPS",
    desc: lang === "TH" ? "แปลงพิกัดละติจูด/ลองจิจูดจากมุมแปลงเป็นขนาดพื้นที่ (ไร่-งาน-ตารางวา)" : "Calculate farm area in Rai and Sqm by inputting GPS coordinates of the field.",
    category: "Agriculture",
    icon: Icons.Map
  },
  {
    id: "farm-break-even-yield",
    slug: "farm-break-even-yield",
    name: lang === "TH" ? "ปริมาณผลผลิตที่ต้องขายเพื่อคืนทุน" : "Farm Break-even Yield",
    desc: lang === "TH" ? "คำนวณปริมาณผลผลิตขั้นต่ำต่อไร่ที่ต้องทำให้ได้เพื่อไม่ให้ขาดทุน" : "Calculate the minimum crop yield required per Rai to break even.",
    category: "Agriculture",
    icon: Icons.Target
  },
  {
    id: "farm-labor-cost-per-rai",
    slug: "farm-labor-cost-per-rai",
    name: lang === "TH" ? "คำนวณค่าจ้างแรงงานเกษตรต่อไร่" : "Farm Labor Cost per Rai",
    desc: lang === "TH" ? "คำนวณต้นทุนค่าแรงเฉลี่ยต่อไร่ และวัดประสิทธิภาพการทำงานของคนงาน (ไร่/คน/วัน)" : "Calculate exact labor cost per Rai and analyze workers' efficiency.",
    category: "Agriculture",
    icon: Icons.Users
  },
  {
    id: "layer-chicken-farm-profit-cost",
    slug: "layer-chicken-farm-profit-cost",
    name: lang === "TH" ? "ต้นทุน/กำไรฟาร์มไก่ไข่" : "Layer Chicken Farm Profit/Cost",
    desc: lang === "TH" ? "คำนวณต้นทุน รายได้ และกำไรสำหรับการทำฟาร์มไก่ไข่เบื้องต้น" : "Calculate costs, revenues, and profit for layer chicken farming.",
    category: "Agriculture",
    icon: Icons.Egg
  },
  {
    id: "pig-farm-profit-cost",
    slug: "pig-farm-profit-cost",
    name: lang === "TH" ? "ต้นทุน/กำไรฟาร์มหมู" : "Pig Farm Profit/Cost",
    desc: lang === "TH" ? "โปรแกรมคำนวณต้นทุน กำไร และประเมินจุดคุ้มทุนสำหรับการเลี้ยงหมูขุน" : "Calculate and estimate profit, costs, and ROI for a commercial pig farm.",
    category: "Agriculture",
    icon: Icons.Activity
  },
  {
    id: "seeds-per-rai-calculator",
    slug: "seeds-per-rai-calculator",
    name: lang === "TH" ? "คำนวณปริมาณเมล็ดพันธุ์ต่อไร่" : "Seeds per Rai Calculator",
    desc: lang === "TH" ? "คำนวณจำนวนต้นต่อไร่และปริมาณเมล็ดพันธุ์ที่ต้องใช้ตามระยะปลูก" : "Calculate the exact amount of seeds needed per Rai based on planting spacing.",
    category: "Agriculture",
    icon: Icons.Sprout
  },
  {
    id: "tractor-rent-vs-buy",
    slug: "tractor-rent-vs-buy",
    name: lang === "TH" ? "ต้นทุนรถไถเช่า vs ซื้อ" : "Tractor Rent vs Buy",
    desc: lang === "TH" ? "เปรียบเทียบต้นทุนและหาจุดคุ้มทุน เลือกระหว่างการซื้อรถไถเองหรือจ้างเหมา" : "Compare costs and find the break-even point between buying a tractor and renting one.",
    category: "Agriculture",
    icon: Icons.Tractor
  },
  {
    id: "farm-land-rent-roi",
    slug: "farm-land-rent-roi",
    name: lang === "TH" ? "คำนวณค่าเช่าที่ดินเกษตร เทียบกำไร" : "Farm Land Rent ROI Calculator",
    desc: lang === "TH" ? "ประเมินความคุ้มค่าของการเช่าที่ดินเพื่อการเกษตร โดยเปรียบเทียบค่าเช่ากับรายได้สุทธิ" : "Evaluate the profitability of renting agricultural land by comparing rent costs with net income.",
    category: "Agriculture",
    icon: Icons.Tractor
  },
  {
    id: "food-carbon-footprint",
    slug: "food-carbon-footprint",
    name: lang === "TH" ? "คำนวณ Carbon Footprint อาหาร" : "Food Carbon Footprint",
    desc: lang === "TH" ? "เปรียบเทียบการปล่อยคาร์บอนระหว่างการบริโภคเนื้อสัตว์และพืชผัก เพื่อทางเลือกที่รักษ์โลก" : "Compare carbon emissions between meat and plant-based foods for eco-friendly choices.",
    category: "Environment",
    icon: Icons.Utensils
  },
  {
    id: "fresh-to-dry-weight",
    slug: "fresh-to-dry-weight",
    name: lang === "TH" ? "คำนวณน้ำหนักผลผลิตสดเป็นแห้ง" : "Fresh to Dry Weight Converter",
    desc: lang === "TH" ? "คำนวณน้ำหนักผลผลิตทางการเกษตรหลังการอบแห้งหรือตากแห้ง โดยอิงจากความชื้น" : "Calculate agricultural product weight after drying based on moisture content.",
    category: "Agriculture",
    icon: Icons.Scale
  },
  {
    id: "germination-rate",
    slug: "germination-rate",
    name: lang === "TH" ? "คำนวณอัตราการงอกของเมล็ดพันธุ์" : "Germination Rate Calculator",
    desc: lang === "TH" ? "คำนวณเปอร์เซ็นต์อัตราการงอกของเมล็ดพันธุ์ เพื่อประเมินคุณภาพเมล็ดก่อนปลูกจริง" : "Calculate the germination rate percentage of seeds to assess seed quality before planting.",
    category: "Agriculture",
    icon: Icons.Sprout
  },
  {
    id: "harvest-time",
    slug: "harvest-time",
    name: lang === "TH" ? "คำนวณระยะเวลาเก็บเกี่ยว" : "Harvest Time from Planting",
    desc: lang === "TH" ? "คำนวณวันเก็บเกี่ยวผลผลิตจากวันปลูกและอายุของพืช เพื่อวางแผนการเก็บเกี่ยว" : "Calculate expected harvest date based on planting date and days to maturity.",
    category: "Agriculture",
    icon: Icons.Calendar
  },
  {
    id: "mill-storage-electricity",
    slug: "mill-storage-electricity",
    name: lang === "TH" ? "คำนวณการใช้ไฟฟ้าโรงสี/โรงเก็บ" : "Mill/Storage Electricity Cost",
    desc: lang === "TH" ? "คำนวณค่าไฟฟ้าของมอเตอร์ เครื่องจักร และระบบระบายอากาศในโรงสีหรือไซโล" : "Calculate electricity costs for motors, machinery, and ventilation in mills or silos.",
    category: "Agriculture",
    icon: Icons.Zap
  },
  {
    id: "product-water-footprint",
    slug: "product-water-footprint",
    name: lang === "TH" ? "คำนวณ Water Footprint สินค้า" : "Product Water Footprint",
    desc: lang === "TH" ? "เปรียบเทียบปริมาณน้ำที่ใช้ในการผลิตสินค้าอุปโภคบริโภคต่างๆ เพื่อสร้างความตระหนักรู้" : "Compare the hidden water used to produce various consumer goods to raise awareness.",
    category: "Environment",
    icon: Icons.Droplets
  },
  {
    id: "recycled-waste-impact",
    slug: "recycled-waste-impact",
    name: lang === "TH" ? "ปริมาณขยะรีไซเคิลที่ลดได้ต่อปี" : "Recycled Waste Impact",
    desc: lang === "TH" ? "คำนวณการลดการปล่อยก๊าซเรือนกระจกจากการคัดแยกและรีไซเคิลขยะประเภทต่างๆ" : "Calculate greenhouse gas emission reductions from sorting and recycling various types of waste.",
    category: "Environment",
    icon: Icons.Recycle
  },
  {
    id: "travel-carbon-footprint",
    slug: "travel-carbon-footprint",
    name: lang === "TH" ? "คำนวณ Carbon Footprint การเดินทาง" : "Travel Carbon Footprint",
    desc: lang === "TH" ? "ประเมินปริมาณการปล่อยก๊าซคาร์บอนไดออกไซด์จากการเดินทางด้วยยานพาหนะประเภทต่างๆ" : "Estimate CO2 emissions from traveling using various modes of transportation.",
    category: "Environment",
    icon: Icons.Car
  },
  {
    id: "water-saving-impact",
    slug: "water-saving-impact",
    name: lang === "TH" ? "ค่าน้ำที่ประหยัดได้จากการเปลี่ยนพฤติกรรม" : "Water Saving Impact",
    desc: lang === "TH" ? "คำนวณปริมาณน้ำและเงินที่ประหยัดได้จากการลดเวลาอาบน้ำหรือปิดน้ำขณะแปรงฟัน" : "Calculate water and money saved by reducing shower time or turning off the tap while brushing.",
    category: "Environment",
    icon: Icons.Droplets
  }
];

export const categories = [
  "Finance",
  "Health",
  "Math",
  "Conversion",
  "Technology",
  "Construction",
  "Family",
  "Utility",
  "Agriculture",
  "Environment",
  "Business",
  "Misc"
];
