import { Heart, Zap, Utensils, Baby, BookOpen, Sparkles, Star, Home, Coins, Plane, Car, Receipt, Calculator, Hash, Briefcase, Clock, Lightbulb } from "lucide-react";
import { Lang } from "../components/dictionary";

export const getCalcs = (lang: Lang) => {
    return [

    // Health & Diet (Pink)
    { id: "bmi", slug: "คำนวณ-bmi", name: lang==="TH"?"คำนวณ BMI":"BMI Calculator", desc: lang==="TH"?"ดัชนีมวลกาย":"Body Mass Index", category: "Health", icon: Heart },
    { id: "sleep", slug: "คำนวณ-sleep", name: lang==="TH"?"การนอนหลับ":"Sleep Cycle", desc: lang==="TH"?"คำนวณเวลานอน":"Sleep Time Calculator", category: "Health", icon: Heart },
    { id: "tdee", slug: "คำนวณ-tdee", name: lang==="TH"?"คำนวณ TDEE":"TDEE Calculator", desc: lang==="TH"?"พลังงานที่ใช้ต่อวัน":"Daily Energy", category: "Health", icon: Zap },
    { id: "water-intake", slug: "คำนวณ-water-intake", name: lang==="TH"?"ปริมาณน้ำดื่ม":"Water Intake", desc: lang==="TH"?"ดื่มน้ำวันละกี่ลิตร":"Daily Water", category: "Health", icon: Heart },
    { id: "food-random", slug: "คำนวณ-food-random", name: lang==="TH"?"สุ่มเมนูอาหาร":"Food Randomizer", desc: lang==="TH"?"สุ่มตามแคลอรี่":"By Calorie Limit", category: "Health", icon: Utensils },
    { id: "exercise-calories", slug: "คำนวณ-exercise-calories", name: lang==="TH"?"แคลอรี่ออกกำลังกาย":"Exercise Calories", desc: lang==="TH"?"เผาผลาญจากการออกกำลัง":"Calories Burned", category: "Health", icon: Zap },
    { id: "protein-daily", slug: "คำนวณ-protein-daily", name: lang==="TH"?"โปรตีนที่ควรได้รับ":"Daily Protein", desc: lang==="TH"?"ตามเป้าหมาย/น้ำหนัก":"Protein Needs", category: "Health", icon: Utensils },
    { id: "body-fat", slug: "คำนวณ-body-fat", name: lang==="TH"?"เปอร์เซ็นต์ไขมัน":"Body Fat %", desc: lang==="TH"?"US Navy Method":"Body Fat %", category: "Health", icon: Heart },
    { id: "whr", slug: "คำนวณ-whr", name: lang==="TH"?"เอวต่อสะโพก":"WHR", desc: lang==="TH"?"ประเมินความเสี่ยงโรค":"Waist-Hip Ratio", category: "Health", icon: Heart },
    { id: "heart-rate-zone", slug: "คำนวณ-heart-rate-zone", name: lang==="TH"?"โซนหัวใจ":"Heart Rate Zones", desc: lang==="TH"?"อัตราการเต้นเป้าหมาย":"Target HR Zones", category: "Health", icon: Heart },
    { id: "macro", slug: "คำนวณ-macro", name: lang==="TH"?"สัดส่วนสารอาหาร":"Macro Split", desc: lang==="TH"?"คาร์บ/โปรตีน/ไขมัน":"Carb/Protein/Fat", category: "Health", icon: Utensils },
    { id: "blood-sugar", slug: "คำนวณ-blood-sugar", name: lang==="TH"?"ค่าน้ำตาลในเลือด":"Blood Sugar", desc: lang==="TH"?"แปลงหน่วย mg ↔ mmol":"mg/dL ↔ mmol/L", category: "Health", icon: Heart },
    { id: "ibw", slug: "คำนวณ-ibw", name: lang==="TH"?"น้ำหนักอุดมคติ":"Ideal Body Weight", desc: lang==="TH"?"IBW (Devine, etc.)":"IBW Formulas", category: "Health", icon: Heart },
    { id: "steps-converter", slug: "คำนวณ-steps-converter", name: lang==="TH"?"แปลงก้าวเดิน":"Steps Converter", desc: lang==="TH"?"ก้าว ↔ ระยะทาง ↔ แคล":"Steps to Distance", category: "Health", icon: Heart },
    { id: "1rm", slug: "คำนวณ-1rm", name: lang==="TH"?"คำนวณ 1RM":"1RM Calculator", desc: lang==="TH"?"น้ำหนักยกสูงสุด":"One Rep Max", category: "Health", icon: Zap },
    { id: "pace", slug: "คำนวณ-pace", name: lang==="TH"?"Pace วิ่ง":"Pace Calculator", desc: lang==="TH"?"คำนวณความเร็ววิ่ง":"Running Pace", category: "Health", icon: Zap },
    
    // Sports (Orange)
    { id: "vo2-max", slug: "คำนวณ-vo2-max", name: lang==="TH"?"คำนวณ VO2 Max":"VO2 Max", desc: lang==="TH"?"ประเมินความฟิต":"Cardio Fitness", category: "Sports", icon: Zap },
    { id: "swim-pace", slug: "คำนวณ-swim-pace", name: lang==="TH"?"Pace ว่ายน้ำ":"Swim Pace", desc: lang==="TH"?"ความเร็ว 100m":"100m Pace", category: "Sports", icon: Zap },
    { id: "cycling-power", slug: "คำนวณ-cycling-power", name: lang==="TH"?"โซนปั่นจักรยาน":"Cycling Power Zones", desc: lang==="TH"?"FTP Zones":"Power Zones", category: "Sports", icon: Zap },
    { id: "race-predictor", slug: "คำนวณ-race-predictor", name: lang==="TH"?"ทำนายเวลาวิ่งแข่ง":"Race Predictor", desc: lang==="TH"?"มาราธอน ฮาล์ฟ":"Marathon/Half", category: "Sports", icon: Zap },
    { id: "lifting-pyramid", slug: "คำนวณ-lifting-pyramid", name: lang==="TH"?"ตาราง Squat/Deadlift":"Squat/Deadlift Pyramid", desc: lang==="TH"?"น้ำหนักเซ็ตพีระมิด":"Pyramid Sets", category: "Sports", icon: Zap },
    { id: "rowing-split", slug: "คำนวณ-rowing-split", name: lang==="TH"?"Rowing Split Time":"Rowing Split Time", desc: lang==="TH"?"ความเร็วพายเรือ":"Erg/Rowing Split", category: "Sports", icon: Zap },
    { id: "carb-endurance", slug: "คำนวณ-carb-endurance", name: lang==="TH"?"คาร์บโหลด (Endurance)":"Carb Loading", desc: lang==="TH"?"พลังงานก่อนแข่ง":"Carbs for Race", category: "Sports", icon: Utensils },
    
    // Additional Health
    { id: "fiber-intake", slug: "คำนวณ-fiber-intake", name: lang==="TH"?"คำนวณ Fiber ต่อวัน":"Fiber Intake", desc: lang==="TH"?"ใยอาหารที่ควรได้รับ":"Daily Fiber", category: "Health", icon: Utensils },
    { id: "vitamin-d", slug: "คำนวณ-vitamin-d", name: lang==="TH"?"รับ Vitamin D จากแสงแดด":"Vitamin D from Sun", desc: lang==="TH"?"เวลาตากแดด":"Sun Exposure", category: "Health", icon: Zap },
    { id: "bmi-kids", slug: "คำนวณ-bmi-kids", name: lang==="TH"?"BMI เด็กตาม Percentile":"Kids BMI Percentile", desc: lang==="TH"?"เด็กโตตามเกณฑ์ไหม":"Child Growth", category: "Health", icon: Baby },

    // Family (Pink)
    { id: "child-height", slug: "คำนวณ-child-height", name: lang==="TH"?"ส่วนสูงลูก":"Child Height", desc: lang==="TH"?"ทำนายส่วนสูง":"Height Predictor", category: "Family", icon: Baby },
    { id: "pregnancy-due", slug: "คำนวณ-pregnancy-due", name: lang==="TH"?"กำหนดคลอด":"Due Date", desc: lang==="TH"?"ทำนายกำหนดคลอด":"Pregnancy Due Date", category: "Family", icon: Baby },
    { id: "ovulation", slug: "คำนวณ-ovulation", name: lang==="TH"?"วันตกไข่":"Ovulation", desc: lang==="TH"?"คำนวณวันไข่ตก":"Fertility Window", category: "Family", icon: Heart },
    { id: "blood-type", slug: "คำนวณ-blood-type", name: lang==="TH"?"ทำนายกรุ๊ปเลือด":"Blood Type", desc: lang==="TH"?"กรุ๊ปเลือดลูก":"Child Blood Predictor", category: "Family", icon: Heart },
    { id: "zodiac", slug: "คำนวณ-zodiac", name: lang==="TH"?"ราศีเกิด":"Zodiac", desc: lang==="TH"?"คำนวณราศี":"Star Sign", category: "Family", icon: BookOpen },
    { id: "horoscope", slug: "คำนวณ-horoscope", name: lang==="TH"?"ดูดวงและโชคชะตา":"Horoscope", desc: lang==="TH"?"ทำนายพื้นดวง":"Fortune Teller", category: "Fortune", icon: BookOpen },
    { id: "tarot", slug: "คำนวณ-tarot", name: lang==="TH"?"ดูดวงไพ่ยิปซี":"Tarot Reading", desc: lang==="TH"?"อดีต ปัจจุบัน อนาคต":"3-Card Spread", category: "Fortune", icon: Sparkles },
    { id: "lenormand", slug: "คำนวณ-lenormand", name: lang==="TH"?"ไพ่เลอนอร์มองด์":"Lenormand", desc: lang==="TH"?"แม่นยำ ตรงไปตรงมา":"3-Card Spread", category: "Fortune", icon: Sparkles },
    { id: "oracle", slug: "คำนวณ-oracle", name: lang==="TH"?"ไพ่ออราเคิล":"Oracle Cards", desc: lang==="TH"?"คำแนะนำ เยียวยาใจ":"Daily Draw", category: "Fortune", icon: Heart },
    { id: "playing-card", slug: "คำนวณ-playing-card", name: lang==="TH"?"ดูดวงไพ่ป๊อก":"Playing Cards", desc: lang==="TH"?"การงาน เงิน ความรัก":"Cartomancy", category: "Fortune", icon: Star },
    { id: "kipper", slug: "คำนวณ-kipper", name: lang==="TH"?"ไพ่คิปเปอร์":"Kipper Cards", desc: lang==="TH"?"เจาะลึกความสัมพันธ์":"Social & People", category: "Fortune", icon: BookOpen },
    { id: "pet-age", slug: "คำนวณ-pet-age", name: lang==="TH"?"อายุสัตว์เลี้ยง":"Pet Age", desc: lang==="TH"?"เทียบอายุคน":"Human Years", category: "Family", icon: BookOpen },
    { id: "fetal-weight", slug: "คำนวณ-fetal-weight", name: lang==="TH"?"น้ำหนักทารกในครรภ์":"Fetal Weight", desc: lang==="TH"?"ตามอายุครรภ์ (สัปดาห์)":"WHO Fetal Dev", category: "Family", icon: Baby },
    { id: "child-cost", slug: "คำนวณ-child-cost", name: lang==="TH"?"ค่าเลี้ยงลูก":"Child Raising Cost", desc: lang==="TH"?"ประมาณการต่อปี":"Yearly Cost", category: "Family", icon: Coins },
    { id: "child-milestone", slug: "คำนวณ-child-milestone", name: lang==="TH"?"พัฒนาการเด็ก":"Child Milestones", desc: lang==="TH"?"ตามช่วงอายุเดือน":"Development Check", category: "Family", icon: Baby },
    { id: "wedding-budget", slug: "คำนวณ-wedding-budget", name: lang==="TH"?"ค่าใช้จ่ายแต่งงาน":"Wedding Budget", desc: lang==="TH"?"แจกแจงงบแต่งงาน":"Wedding Costs", category: "Family", icon: Heart },
    { id: "newborn-cost", slug: "คำนวณ-newborn-cost", name: lang==="TH"?"ค่าใช้จ่ายทารกแรกเกิด":"Newborn Cost", desc: lang==="TH"?"ปีแรกต้องเตรียมเงินเท่าไหร่":"First Year Cost", category: "Family", icon: Baby },
    { id: "pet-cost", slug: "คำนวณ-pet-cost", name: lang==="TH"?"ค่าใช้จ่ายสัตว์เลี้ยง/ปี":"Pet Cost", desc: lang==="TH"?"หมา/แมว":"Dog & Cat", category: "Family", icon: Heart },
    { id: "food-expiration", slug: "คำนวณ-food-expiration", name: lang==="TH"?"วันหมดอายุอาหาร/นม":"Food/Milk Expiration", desc: lang==="TH"?"ตู้เย็น/ช่องฟรีซเก็บได้กี่วัน":"Fridge Storage Time", category: "Family", icon: Home },
    { id: "rent-vs-buy", slug: "คำนวณ-rent-vs-buy", name: lang==="TH"?"เช่า vs ซื้อบ้าน":"Rent vs Buy Home", desc: lang==="TH"?"เปรียบเทียบความคุ้มค่า":"Financial Comparison", category: "Family", icon: Home },

    // Travel (Cyan)
    { id: "time-zone", slug: "คำนวณ-time-zone", name: lang==="TH"?"แปลงเวลาโลก":"Time Zone", desc: lang==="TH"?"เทียบเวลาประเทศต่างๆ":"Global Time", category: "Travel", icon: BookOpen },
    { id: "travel-budget", slug: "คำนวณ-travel-budget", name: lang==="TH"?"งบท่องเที่ยว":"Travel Budget", desc: lang==="TH"?"คำนวณค่าใช้จ่ายทริป":"Trip Expenses", category: "Travel", icon: Coins },
    { id: "flight-time", slug: "คำนวณ-flight-time", name: lang==="TH"?"เวลาบิน":"Flight Time", desc: lang==="TH"?"เวลาเดินทางเครื่องบิน":"Plane Travel Time", category: "Travel", icon: Plane },
    { id: "packing-list", slug: "คำนวณ-packing-list", name: lang==="TH"?"จัดกระเป๋าเดินทาง":"Packing List", desc: lang==="TH"?"เช็กลิสต์จัดกระเป๋า":"Luggage Checklist", category: "Travel", icon: BookOpen },
    { id: "road-trip", slug: "คำนวณ-road-trip", name: lang==="TH"?"ค่าน้ำมัน Road Trip":"Road Trip", desc: lang==="TH"?"ค่าแก๊ส/ทางด่วน":"Fuel & Tolls", category: "Travel", icon: Car },
    { id: "baggage-weight", slug: "คำนวณ-baggage-weight", name: lang==="TH"?"เช็คน้ำหนักกระเป๋า":"Baggage Weight", desc: lang==="TH"?"เทียบลิมิตสายการบิน":"Baggage Fee Checker", category: "Travel", icon: Plane },
    { id: "jet-lag", slug: "คำนวณ-jet-lag", name: lang==="TH"?"Jet Lag":"Jet Lag", desc: lang==="TH"?"เวลาปรับตัวข้ามโซน":"Timezone Recovery", category: "Travel", icon: Plane },
    { id: "roaming-cost", slug: "คำนวณ-roaming-cost", name: lang==="TH"?"ค่า Roaming":"Roaming Cost", desc: lang==="TH"?"ประเมินค่าเน็ตตปท.":"Data Roaming", category: "Travel", icon: Coins },

    // Finance (Green/Gold)
    { id: "discount", slug: "คำนวณ-discount", name: lang==="TH"?"ส่วนลด":"Discount", desc: lang==="TH"?"เปอร์เซ็นต์ส่วนลด":"Discount Percentage", category: "Finance", icon: Coins },
    { id: "car-loan", slug: "คำนวณค่างวดรถมือสอง", name: lang==="TH"?"ผ่อนรถยนต์":"Car Loan", desc: lang==="TH"?"ค่างวดรถ":"Auto Loan Calculator", category: "Finance", icon: Car },
    { id: "mortgage", slug: "คำนวณ-ผ่อนบ้าน-2569", name: lang==="TH"?"เงินกู้/บ้าน":"Mortgage", desc: lang==="TH"?"ยอดผ่อนรายเดือน":"Loan Calculator", category: "Finance", icon: Coins },
    { id: "gold-price", slug: "คำนวณ-gold-price", name: lang==="TH"?"ราคาทองคำวันนี้":"Gold Price", desc: lang==="TH"?"เช็คราคา กราฟ คำนวณ":"Live Price & Calc", category: "Gold", icon: Coins },
    { id: "compound-interest", slug: "คำนวณ-compound-interest", name: lang==="TH"?"ดอกเบี้ยทบต้น":"Compound Interest", desc: lang==="TH"?"ผลตอบแทนลงทุน":"Investment Growth", category: "Finance", icon: Coins },
    { id: "bill-splitter", slug: "คำนวณ-bill-splitter", name: lang==="TH"?"หารค่าอาหาร":"Bill Splitter", desc: lang==="TH"?"แยกจ่าย + SC/VAT":"Split Bill + SC/VAT", category: "Finance", icon: Receipt },
    { id: "currency-converter", slug: "คำนวณ-currency-converter", name: lang==="TH"?"แปลงสกุลเงิน":"Currency Converter", desc: lang==="TH"?"เรทเงินสดล่าสุด":"Live Exchange Rates", category: "Finance", icon: Coins },
    { id: "savings-goal", slug: "คำนวณ-savings-goal", name: lang==="TH"?"เป้าหมายการออม":"Savings Goal", desc: lang==="TH"?"ต้องเก็บเดือนละเท่าไหร่":"Monthly Savings", category: "Finance", icon: Coins },
    { id: "inflation", slug: "คำนวณ-inflation", name: lang==="TH"?"เงินเฟ้อ":"Inflation", desc: lang==="TH"?"มูลค่าเงินในอนาคต":"Future Money Value", category: "Finance", icon: Coins },
    { id: "salary-hourly", slug: "คำนวณ-salary-hourly", name: lang==="TH"?"เงินเดือน ↔ รายชั่วโมง":"Salary to Hourly", desc: lang==="TH"?"ค่าแรงรายชั่วโมง":"Hourly Rate", category: "Finance", icon: Calculator },
    { id: "net-worth", slug: "คำนวณ-net-worth", name: lang==="TH"?"ความมั่งคั่งสุทธิ":"Net Worth", desc: lang==="TH"?"ทรัพย์สินหักหนี้สิน":"Assets - Liabilities", category: "Finance", icon: Coins },
    { id: "debt-payoff", slug: "คำนวณ-debt-payoff", name: lang==="TH"?"วางแผนปลดหนี้":"Debt Payoff", desc: lang==="TH"?"จ่ายโปะแบบไหนดี":"Snowball/Avalanche", category: "Finance", icon: Coins },
    { id: "retirement", slug: "คำนวณ-retirement", name: lang==="TH"?"เกษียณอายุ":"Retirement", desc: lang==="TH"?"ต้องมีเงินเท่าไหร่":"Needed for Retirement", category: "Finance", icon: Coins },
    { id: "stock-profit", slug: "คำนวณ-stock-profit", name: lang==="TH"?"กำไรหุ้น/คริปโต":"Stock Profit", desc: lang==="TH"?"จุดคุ้มทุน/กำไรสุทธิ":"Trading Profit", category: "Finance", icon: Coins },
    { id: "roi", slug: "คำนวณ-roi", name: lang==="TH"?"ผลตอบแทน ROI":"ROI", desc: lang==="TH"?"ความคุ้มค่าการลงทุน":"Return on Investment", category: "Finance", icon: Calculator },
    { id: "dca", slug: "คำนวณ-dca", name: lang==="TH"?"DCA หุ้น/กองทุน":"DCA Calculator", desc: lang==="TH"?"ลงทุนรายเดือนสม่ำเสมอ":"Dollar Cost Average", category: "Finance", icon: Coins },
    { id: "stock-fee", slug: "คำนวณ-stock-fee", name: lang==="TH"?"ค่าธรรมเนียมหุ้น":"Stock Trading Fee", desc: lang==="TH"?"คอมมิชชั่น + VAT":"Commission Fee", category: "Finance", icon: Receipt },
    { id: "net-salary", slug: "คำนวณ-เงินเดือนสุทธิ-2569", name: lang==="TH"?"เงินเดือนสุทธิ":"Net Salary", desc: lang==="TH"?"หักประกันสังคม/ภาษี":"Take-home Pay", category: "Finance", icon: Coins },
    { id: "expense-tracker", slug: "คำนวณ-expense-tracker", name: lang==="TH"?"จัดสรรเงิน 50/30/20":"Budget 50/30/20", desc: lang==="TH"?"แบ่งเงินออมและใช้จ่าย":"Rule Budgeting", category: "Finance", icon: Coins },

    // Business (Green/Gold)
    { id: "vat", slug: "คำนวณ-vat", name: lang==="TH"?"คำนวณ VAT":"VAT Calculator", desc: lang==="TH"?"ถอด/เพิ่ม VAT":"Value Added Tax", category: "Business", icon: Receipt },
    { id: "margin", slug: "คำนวณ-margin", name: lang==="TH"?"คำนวณราคาขาย":"Margin", desc: lang==="TH"?"ตั้งราคาจากต้นทุน":"Profit Margin", category: "Business", icon: Calculator },
    { id: "break-even", slug: "คำนวณ-break-even", name: lang==="TH"?"จุดคุ้มทุน":"Break-even", desc: lang==="TH"?"ต้องขายกี่ชิ้น":"Units to Break-even", category: "Business", icon: Calculator },
    { id: "markup", slug: "คำนวณ-markup", name: lang==="TH"?"ตั้งราคาจากต้นทุน":"Markup Pricing", desc: lang==="TH"?"ราคาขายแนะนำ":"Suggested Price", category: "Business", icon: Calculator },
    { id: "depreciation", slug: "คำนวณ-depreciation", name: lang==="TH"?"ค่าเสื่อมราคา":"Depreciation", desc: lang==="TH"?"ตัดจ่ายรายปี":"Straight-line", category: "Business", icon: Calculator },
    { id: "payroll", slug: "คำนวณ-payroll", name: lang==="TH"?"คำนวณเงินเดือนพนักงาน":"Payroll", desc: lang==="TH"?"หักประกันสังคม/ภาษี":"Net Salary", category: "Business", icon: Calculator },
    { id: "cogs", slug: "คำนวณ-cogs", name: lang==="TH"?"ต้นทุนขาย (COGS)":"COGS", desc: lang==="TH"?"ต้นทุนสินค้าที่ขาย":"Cost of Goods Sold", category: "Business", icon: Calculator },
    { id: "ltv", slug: "คำนวณ-ltv", name: lang==="TH"?"มูลค่าลูกค้าตลอดชีพ":"Customer LTV", desc: lang==="TH"?"Customer Lifetime Value":"Customer Lifetime Value", category: "Business", icon: Calculator },
    { id: "cac", slug: "คำนวณ-cac", name: lang==="TH"?"ต้นทุนได้ลูกค้าใหม่":"CAC", desc: lang==="TH"?"Customer Acquisition":"Acquisition Cost", category: "Business", icon: Coins },
    { id: "conversion-rate", slug: "คำนวณ-conversion-rate", name: lang==="TH"?"อัตราการเปลี่ยนเป็นยอดขาย":"Conversion Rate", desc: lang==="TH"?"% คนซื้อ":"Sales Conversion", category: "Business", icon: Calculator },
    { id: "inventory-turnover", slug: "คำนวณ-inventory-turnover", name: lang==="TH"?"รอบหมุนเวียนสินค้า":"Inventory Turnover", desc: lang==="TH"?"ขายของออกเร็วแค่ไหน":"Turnover Ratio", category: "Business", icon: Calculator },
    { id: "financial-ratio", slug: "คำนวณ-financial-ratio", name: lang==="TH"?"อัตราส่วนการเงิน":"Financial Ratios", desc: lang==="TH"?"วิเคราะห์สภาพธุรกิจ":"Business Health", category: "Business", icon: Calculator },
    { id: "marketplace-fee", slug: "คำนวณ-marketplace-fee", name: lang==="TH"?"ค่าธรรมเนียมขายของ":"Marketplace Fee", desc: lang==="TH"?"Shopee/Lazada/TikTok":"Platform Fees", category: "Business", icon: Receipt },
    { id: "safety-stock", slug: "คำนวณ-safety-stock", name: lang==="TH"?"จุดสั่งซื้อ/สต็อกสำรอง":"Safety Stock", desc: lang==="TH"?"Reorder Point":"Inventory Control", category: "Business", icon: Calculator },
    { id: "shipping-cost", slug: "คำนวณ-shipping-cost", name: lang==="TH"?"เปรียบเทียบค่าส่ง":"Shipping Cost", desc: lang==="TH"?"Kerry, J&T, Flash, ปณ.":"Courier Rates", category: "Business", icon: Car },
    { id: "return-rate", slug: "คำนวณ-return-rate", name: lang==="TH"?"ผลกระทบตีกลับ":"Return Rate Impact", desc: lang==="TH"?"กำไรที่หายจากของตีกลับ":"Lost Profit Return", category: "Business", icon: Receipt },
    { id: "eoq", slug: "คำนวณ-eoq", name: lang==="TH"?"จุดสั่งซื้อที่ประหยัดที่สุด (EOQ)":"EOQ Calculator", desc: lang==="TH"?"สต็อกของอย่างไรให้คุ้ม":"Optimal Order Qty", category: "Business", icon: Briefcase },
    { id: "churn-retention", slug: "คำนวณ-churn-retention", name: lang==="TH"?"Churn & Retention Rate":"Churn Rate", desc: lang==="TH"?"ลูกค้ายกเลิกกี่เปอร์เซ็นต์":"Lost Customers", category: "Business", icon: Briefcase },
    { id: "shrinkage", slug: "คำนวณ-shrinkage", name: lang==="TH"?"การสูญเสียสต็อก (Shrinkage)":"Inventory Shrinkage", desc: lang==="TH"?"ของหาย/พัง":"Lost Inventory", category: "Business", icon: Briefcase },
    { id: "import-markup", slug: "คำนวณ-import-markup", name: lang==="TH"?"ตั้งราคาสินค้านำเข้า":"Import Markup", desc: lang==="TH"?"คำนวณภาษี+ค่าส่ง":"Landed Cost", category: "Business", icon: Briefcase },
    { id: "freelance-rate", slug: "คำนวณ-freelance-rate", name: lang==="TH"?"เรทค่าตัวฟรีแลนซ์":"Freelance Hourly Rate", desc: lang==="TH"?"ทำงานรายชั่วโมง/วัน":"Hourly Rate", category: "Business", icon: Briefcase },

    // Utility & Education (Blue)
    { id: "gpa", slug: "คำนวณ-gpa", name: lang==="TH"?"จำลองเกรดเบื้องต้น":"GPA Simulator", desc: lang==="TH"?"จำลองเกรด (GPA)":"GPA Estimator", category: "Utility", icon: BookOpen },
    { id: "basen", slug: "คำนวณ-basen", name: lang==="TH"?"แปลงเลขฐาน":"Base Converter", desc: lang==="TH"?"ฐาน 2–36 ครบทุกฐาน":"Base 2–36, Step-by-Step", category: "Utility", icon: Calculator },
    { id: "btu", slug: "คำนวณ-btu", name: lang==="TH"?"คำนวณ BTU":"AC BTU", desc: lang==="TH"?"ขนาดแอร์บ้าน":"Air Conditioner BTU", category: "Utility", icon: Home },
    { id: "electric", slug: "คำนวณ-ค่าไฟ-2569", name: lang==="TH"?"ค่าไฟ":"Electricity", desc: lang==="TH"?"คำนวณค่าไฟฟ้า":"Electricity Bill", category: "Utility", icon: Zap },
    { id: "water-bill", slug: "คำนวณ-water-bill", name: lang==="TH"?"ค่าน้ำ":"Water Bill", desc: lang==="TH"?"ค่าน้ำประปา":"Water Usage Bill", category: "Utility", icon: Home },
    { id: "fuel-cost", slug: "คำนวณ-fuel-cost", name: lang==="TH"?"ค่าน้ำมันรถ":"Fuel Cost", desc: lang==="TH"?"คำนวณค่าน้ำมันเดินทาง":"Trip Fuel Estimate", category: "Utility", icon: Car },
    { id: "cooking-unit", slug: "คำนวณ-cooking-unit", name: lang==="TH"?"แปลงหน่วยทำอาหาร":"Cooking Units", desc: lang==="TH"?"ถ้วยตวง ↔ กรัม":"Cups to Grams", category: "Utility", icon: Utensils },
    { id: "tile-area", slug: "คำนวณ-tile-area", name: lang==="TH"?"กระเบื้องปูพื้น":"Tile Area", desc: lang==="TH"?"คำนวณเผื่อกันพลาด":"Floor Tile Estimate", category: "Utility", icon: Home },
    { id: "grade-converter", slug: "คำนวณ-grade-converter", name: lang==="TH"?"แปลงเกรดต่างประเทศ":"Grade Converter", desc: lang==="TH"?"TH ↔ US ↔ UK":"Intl Grade", category: "Utility", icon: BookOpen },
    { id: "target-gpa", slug: "คำนวณ-target-gpa", name: lang==="TH"?"เป้าหมาย GPA":"Target GPA", desc: lang==="TH"?"เกรดที่ต้องทำเพิ่ม":"Required GPA", category: "Utility", icon: BookOpen },
    { id: "percentile", slug: "คำนวณ-percentile", name: lang==="TH"?"Percentile/Z-Score":"Percentile Calculator", desc: lang==="TH"?"เทียบค่าเฉลี่ย":"Normal Distribution", category: "Utility", icon: Hash },
    { id: "reading-time", slug: "คำนวณ-reading-time", name: lang==="TH"?"เวลาอ่านหนังสือ":"Reading Time", desc: lang==="TH"?"คำนวณวันจบเล่ม":"Books Finishing Time", category: "Utility", icon: BookOpen },

    // Education (Blue)
    { id: "english-test", slug: "คำนวณ-english-test", name: lang==="TH"?"IELTS ↔ TOEFL ↔ CEFR":"IELTS/TOEFL", desc: lang==="TH"?"แปลงคะแนนภาษาอังกฤษ":"English Tests", category: "Education", icon: BookOpen },
    { id: "pomodoro", slug: "คำนวณ-pomodoro", name: lang==="TH"?"Pomodoro Timer":"Pomodoro Timer", desc: lang==="TH"?"นาฬิกาโฟกัสการทำงาน":"Focus Timer", category: "Education", icon: Clock },
    { id: "flashcard-timer", slug: "คำนวณ-flashcard-timer", name: lang==="TH"?"Flash Card Timer":"Flash Card Timer", desc: lang==="TH"?"จับเวลาตอบสั้นๆ":"Active Recall", category: "Education", icon: Clock },

    // Agriculture (Green)
    { id: "food-energy", slug: "คำนวณ-food-energy", name: lang==="TH"?"พลังงานอาหาร":"Food Energy", desc: lang==="TH"?"Joule ↔ kcal":"Joule ↔ kcal", category: "Agriculture", icon: Zap },
    { id: "fertilizer", slug: "คำนวณ-fertilizer", name: lang==="TH"?"ปุ๋ยต่อไร่":"Fertilizer", desc: lang==="TH"?"NPK ตามชนิดพืช":"Fertilizer per Rai", category: "Agriculture", icon: Home },
    { id: "irrigation", slug: "คำนวณ-irrigation", name: lang==="TH"?"น้ำชลประทาน":"Irrigation", desc: lang==="TH"?"ปริมาณน้ำต่อไร่":"Water per Rai", category: "Agriculture", icon: Home },
    { id: "durian", slug: "คำนวณ-durian", name: lang==="TH"?"คำนวณทำสวนทุเรียน":"Durian Farming", desc: lang==="TH"?"วันตัด/การปลูก":"Harvest & Plant", category: "Agriculture", icon: Home },
    { id: "yield", slug: "คำนวณ-yield", name: lang==="TH"?"ผลผลิตต่อไร่":"Crop Yield", desc: lang==="TH"?"กำไรเกษตรกร":"Yield per Rai", category: "Agriculture", icon: Coins },
    { id: "soil-ph", slug: "คำนวณ-soil-ph", name: lang==="TH"?"pH ดิน + ปูนแก้ดิน":"Soil pH & Lime", desc: lang==="TH"?"คำนวณปูนขาวปรับดิน":"Soil Amendment", category: "Agriculture", icon: Home },
    { id: "livestock-profit", slug: "คำนวณ-livestock-profit", name: lang==="TH"?"ต้นทุน/กำไร ปศุสัตว์":"Livestock Profit", desc: lang==="TH"?"กำไรการเลี้ยงสัตว์":"Farming Profit", category: "Agriculture", icon: Coins },
    { id: "spray-volume", slug: "คำนวณ-spray-volume", name: lang==="TH"?"น้ำยาฉีดพ่น":"Spray Volume", desc: lang==="TH"?"ผสมน้ำยาเคมีเกษตร":"Chemical Mixing", category: "Agriculture", icon: Zap },
    { id: "fishery-income", slug: "คำนวณ-fishery-income", name: lang==="TH"?"รายได้ประมง":"Fishery Income", desc: lang==="TH"?"กำไรบ่อปลา/กุ้ง":"Aquaculture Profit", category: "Agriculture", icon: Coins },
    { id: "yield-gap", slug: "คำนวณ-yield-gap", name: lang==="TH"?"Yield Gap":"Yield Gap", desc: lang==="TH"?"ศักยภาพผลผลิต":"Potential vs Actual", category: "Agriculture", icon: Calculator },

    // Construction (Amber)
    { id: "house-paint", slug: "คำนวณ-house-paint", name: lang==="TH"?"สีทาบ้าน":"House Paint", desc: lang==="TH"?"พื้นที่ผนัง → ลิตร":"Wall Area → Liters", category: "Construction", icon: Home },
    { id: "cement", slug: "คำนวณ-cement", name: lang==="TH"?"ปูนซีเมนต์":"Cement", desc: lang==="TH"?"ปริมาณปูนตามพื้นที่":"Cement Volume", category: "Construction", icon: Home },
    { id: "wallpaper", slug: "คำนวณ-wallpaper", name: lang==="TH"?"วอลเปเปอร์":"Wallpaper", desc: lang==="TH"?"ม้วนที่ต้องการ":"Rolls Needed", category: "Construction", icon: Home },
    { id: "roof-area", slug: "คำนวณ-roof-area", name: lang==="TH"?"พื้นที่หลังคา":"Roof Area", desc: lang==="TH"?"ทรงต่างๆ":"Roof Shapes", category: "Construction", icon: Home },
    { id: "water-tank", slug: "คำนวณ-water-tank", name: lang==="TH"?"ถังน้ำ":"Water Tank", desc: lang==="TH"?"ขนาดถังที่เหมาะสม":"Tank Size", category: "Construction", icon: Home },
    { id: "pool-vol", slug: "คำนวณ-pool-vol", name: lang==="TH"?"สระว่ายน้ำ":"Pool Volume", desc: lang==="TH"?"ปริมาตรน้ำ/คลอรีน":"Water Volume", category: "Construction", icon: Home },
    { id: "insulation", slug: "คำนวณ-insulation", name: lang==="TH"?"ฉนวนกันความร้อน":"Insulation", desc: lang==="TH"?"R-value ที่ต้องการ":"R-Value Needed", category: "Construction", icon: Home },
    { id: "reno-cost", slug: "คำนวณ-reno-cost", name: lang==="TH"?"ค่าใช้จ่ายรีโนเวท":"Renovation Cost", desc: lang==="TH"?"ประเมินงบก่อสร้าง":"Estimated Budget", category: "Construction", icon: Coins },
    { id: "solar-panel", slug: "คำนวณ-solar-panel", name: lang==="TH"?"โซลาร์เซลล์":"Solar Panel", desc: lang==="TH"?"จำนวนแผงที่ต้องการ":"Panels Needed", category: "Construction", icon: Zap },
    { id: "interior-cost", slug: "คำนวณ-interior-cost", name: lang==="TH"?"ค่าตกแต่งภายใน":"Interior Cost", desc: lang==="TH"?"ประเมินงบ Built-in":"Interior Budget", category: "Construction", icon: Home },
    { id: "ach-calc", slug: "คำนวณ-ach-calc", name: lang==="TH"?"ระบบระบายอากาศ ACH":"ACH Ventilation", desc: lang==="TH"?"Air Changes/Hour":"Air Changes per Hour", category: "Construction", icon: Zap },
    { id: "concrete-vol", slug: "คำนวณ-concrete-vol", name: lang==="TH"?"คอนกรีต m³":"Concrete Volume", desc: lang==="TH"?"คำนวณคิวปูน":"Cubic Meters", category: "Construction", icon: Home },
    { id: "rebar-weight", slug: "คำนวณ-rebar-weight", name: lang==="TH"?"เหล็กเสริม Rebar":"Rebar Weight", desc: lang==="TH"?"น้ำหนักเหล็กเส้น":"Rebar Weight", category: "Construction", icon: Hash },
    { id: "aac-blocks", slug: "คำนวณ-aac-blocks", name: lang==="TH"?"อิฐมวลเบา":"AAC Blocks", desc: lang==="TH"?"จำนวนก้อนอิฐมวลเบา":"Blocks Needed", category: "Construction", icon: Home },
    { id: "labor-cost-sqm", slug: "คำนวณ-labor-cost-sqm", name: lang==="TH"?"ค่าแรงงานต่อ ตร.ม.":"Labor Cost per sqm", desc: lang==="TH"?"ประเมินค่าแรงก่อสร้าง":"Construction Labor", category: "Construction", icon: Coins },
    { id: "plumbing-pipe", slug: "คำนวณ-plumbing-pipe", name: lang==="TH"?"ท่อประปา":"Plumbing Pipe", desc: lang==="TH"?"ความยาวและข้อต่อ":"Pipe & Fittings", category: "Construction", icon: Home },
    { id: "slope-grade", slug: "คำนวณ-slope-grade", name: lang==="TH"?"ความลาดชัน (Slope)":"Slope / Grade", desc: lang==="TH"?"เปอร์เซ็นต์ Slope":"Slope Percentage", category: "Construction", icon: Hash },

    // Environment (Emerald)
    { id: "carbon-footprint", slug: "คำนวณ-carbon-footprint", name: lang==="TH"?"Carbon Footprint ส่วนตัว":"Personal Carbon Footprint", desc: lang==="TH"?"ประเมินคาร์บอนรายปี":"Annual CO2", category: "Environment", icon: Sparkles },
    { id: "wind-energy", slug: "คำนวณ-wind-energy", name: lang==="TH"?"พลังงานลม":"Wind Energy", desc: lang==="TH"?"กำลังไฟฟ้าจากลม":"Wind Power", category: "Environment", icon: Zap },
    { id: "water-savings", slug: "คำนวณ-water-savings", name: lang==="TH"?"ประหยัดน้ำ":"Water Savings", desc: lang==="TH"?"ลดค่าน้ำจากก๊อก/ชักโครก":"Water Conservation", category: "Environment", icon: Home },
    { id: "plastic-footprint", slug: "คำนวณ-plastic-footprint", name: lang==="TH"?"Plastic Footprint":"Plastic Footprint", desc: lang==="TH"?"ขยะพลาสติกต่อปี":"Annual Plastic Waste", category: "Environment", icon: Sparkles },

    // Science (Indigo)
    { id: "quadratic-eq", slug: "คำนวณ-quadratic-eq", name: lang==="TH"?"สมการกำลังสอง":"Quadratic Equation", desc: lang==="TH"?"หาค่า x จากสมการ":"Solve for x", category: "Science", icon: Calculator },
    { id: "ph-poh", slug: "คำนวณ-ph-poh", name: lang==="TH"?"คำนวณ pH / pOH":"pH / pOH", desc: lang==="TH"?"ความเข้มข้นไฮโดรเจน":"Ion Concentration", category: "Science", icon: Hash },

    // Technology (Orange)
    { id: "bandwidth", slug: "คำนวณ-bandwidth", name: lang==="TH"?"คำนวณ Bandwidth":"Bandwidth", desc: lang==="TH"?"เวลาดาวน์โหลดไฟล์":"Download Time", category: "Technology", icon: Zap },
    { id: "server-cost", slug: "คำนวณ-server-cost", name: lang==="TH"?"คำนวณ Server Cost":"Server Cost", desc: lang==="TH"?"EC2/VM ต่อเดือน":"Monthly Cost", category: "Technology", icon: Calculator },
    { id: "image-size", slug: "คำนวณ-image-size", name: lang==="TH"?"ขนาดรูปภาพ":"Image Size", desc: lang==="TH"?"Resolution x bit depth":"Resolution Size", category: "Technology", icon: Hash },
    { id: "ip-subnet", slug: "คำนวณ-ip-subnet", name: lang==="TH"?"คำนวณ IP Subnet":"IP Subnet", desc: lang==="TH"?"CIDR/subnet mask":"CIDR Network", category: "Technology", icon: Hash },
    { id: "video-bitrate", slug: "คำนวณ-video-bitrate", name: lang==="TH"?"FPS/Bitrate วิดีโอ":"Video Bitrate", desc: lang==="TH"?"คุณภาพ VS ขนาดไฟล์":"Video Size", category: "Technology", icon: Hash },
    { id: "battery-life", slug: "คำนวณ-battery-life", name: lang==="TH"?"คำนวณ Battery Life":"Battery Life", desc: lang==="TH"?"mAh ÷ การใช้งาน":"mAh Usage", category: "Technology", icon: Zap },
    { id: "hash-rate", slug: "คำนวณ-hash-rate", name: lang==="TH"?"คำนวณ Hash Rate":"Hash Rate", desc: lang==="TH"?"เหมืองคริปโต":"Crypto Mining", category: "Technology", icon: Coins },
    { id: "raid-calc", slug: "คำนวณ-raid-calc", name: lang==="TH"?"คำนวณความจุ RAID":"RAID Storage", desc: lang==="TH"?"RAID 0, 1, 5, 6, 10":"RAID 0, 1, 5, 6, 10", category: "Technology", icon: Hash },
    { id: "ppi-calc", slug: "คำนวณ-ppi-calc", name: lang==="TH"?"ความหนาแน่นพิกเซล":"Pixel Density", desc: lang==="TH"?"PPI / DPI":"PPI / DPI", category: "Technology", icon: Hash },
    { id: "api-cost", slug: "คำนวณ-api-cost", name: lang==="TH"?"คำนวณค่าบริการ API":"API Cost", desc: lang==="TH"?"Token เป็นเงินบาท":"Token to THB", category: "Technology", icon: Calculator },
    { id: "ups-runtime", slug: "คำนวณ-ups-runtime", name: lang==="TH"?"ระยะเวลาสำรองไฟ UPS":"UPS Runtime", desc: lang==="TH"?"คำนวณเวลาแบตเตอรี่":"Battery Time", category: "Technology", icon: Zap },
    { id: "morse-code", slug: "คำนวณ-morse-code", name: lang==="TH"?"แปลงรหัสมอร์ส":"Morse Code", desc: lang==="TH"?"Text ↔ Morse":"Text ↔ Morse", category: "Technology", icon: BookOpen },
    { id: "ascii-converter", slug: "คำนวณ-ascii-converter", name: lang==="TH"?"แปลง ASCII/Unicode":"ASCII/Unicode", desc: lang==="TH"?"Text ↔ Binary/Hex":"Text ↔ Binary/Hex", category: "Technology", icon: Hash },
    { id: "cache-hit-rate", slug: "คำนวณ-cache-hit-rate", name: lang==="TH"?"คำนวณ Cache Hit Rate":"Cache Hit Rate", desc: lang==="TH"?"Hits vs Misses":"Hits vs Misses", category: "Technology", icon: Hash },

    // General (Purple)
    { id: "digital-unit", slug: "คำนวณ-digital-unit", name: lang==="TH"?"แปลงหน่วยดิจิทัล":"Digital Unit", desc: lang==="TH"?"MB ↔ GB ↔ TB":"MB ↔ GB ↔ TB", category: "General", icon: Hash },
    { id: "angle", slug: "คำนวณ-angle", name: lang==="TH"?"คำนวณมุมและองศา":"Angle Converter", desc: lang==="TH"?"° ↔ radian":"° ↔ radian", category: "General", icon: Hash },
    { id: "color", slug: "คำนวณ-color", name: lang==="TH"?"แปลงสีเฮกซ์/RGB":"Color Converter", desc: lang==="TH"?"HEX ↔ RGB ↔ HSL":"HEX ↔ RGB ↔ HSL", category: "General", icon: Hash },
    { id: "temperature", slug: "คำนวณ-temperature", name: lang==="TH"?"แปลงหน่วยอุณหภูมิ":"Temperature", desc: lang==="TH"?"°C ↔ °F ↔ K":"°C ↔ °F ↔ K", category: "General", icon: Hash },
    { id: "speed", slug: "คำนวณ-speed", name: lang==="TH"?"แปลงหน่วยความเร็ว":"Speed Converter", desc: lang==="TH"?"km/h ↔ mph ↔ knot":"km/h ↔ mph", category: "General", icon: Hash },
    { id: "area-unit", slug: "วิธีแปลงไร่เป็นตารางเมตร", name: lang==="TH"?"แปลงหน่วยพื้นที่":"Area Converter", desc: lang==="TH"?"ตร.ม. ↔ ไร่ ↔ acre":"sqm ↔ rai ↔ acre", category: "General", icon: Home },
    { id: "weight-unit", slug: "คำนวณ-weight-unit", name: lang==="TH"?"แปลงหน่วยน้ำหนัก":"Weight Converter", desc: lang==="TH"?"กก. ↔ ปอนด์ ↔ ออนซ์":"kg ↔ lb ↔ oz", category: "General", icon: Hash },
    { id: "roman", slug: "คำนวณ-roman", name: lang==="TH"?"ตัวแปลงเลขโรมัน":"Roman Numeral", desc: lang==="TH"?"Roman ↔ อารบิก":"Roman ↔ Arabic", category: "General", icon: BookOpen },
    { id: "area-shape", slug: "คำนวณ-area-shape", name: lang==="TH"?"คำนวณพื้นที่รูปทรง":"Shape Area", desc: lang==="TH"?"วงกลม สามเหลี่ยม":"Circle, Triangle", category: "General", icon: Hash },
    { id: "volume-shape", slug: "สูตรหาปริมาตรทรงกระบอก", name: lang==="TH"?"คำนวณปริมาตรภาชนะ":"Shape Volume", desc: lang==="TH"?"กล่อง กระบอก ทรงกลม":"Box, Cylinder", category: "General", icon: Hash },
    { id: "working-days", slug: "คำนวณ-working-days", name: lang==="TH"?"คำนวณวันทำงาน":"Working Days", desc: lang==="TH"?"หักวันหยุดนักขัตฤกษ์":"Minus Holidays", category: "General", icon: Calculator },
    { id: "word-counter", slug: "คำนวณ-word-counter", name: lang==="TH"?"นับจำนวนคำ":"Word Counter", desc: lang==="TH"?"นับคำ/ตัวอักษร":"Words & Chars", category: "General", icon: BookOpen },
    { id: "age", slug: "คำนวณ-age", name: lang==="TH"?"คำนวณอายุ":"Age Calculator", desc: lang==="TH"?"อายุละเอียด":"Exact Age", category: "General", icon: Calculator },
    { id: "pantone", slug: "คำนวณ-pantone", name: lang==="TH"?"แปลงสี Pantone":"Pantone Converter", desc: lang==="TH"?"HEX เป็น Pantone (Approx)":"Approx Pantone", category: "General", icon: Hash },
  ];

  
};
