const fs = require('fs');

const allTools = [
  "event-countdown",
  "retirement-countdown",
  "sunrise-sunset-calculator",
  "thai-lunar-phase",
  "thai-public-holidays",
  "working-days-calculator",
  "prorate-salary",
  "multi-rate-ot",
  "remaining-annual-leave",
  "shift-work-staffing",
  "social-media-image-size",
  "font-size-reading-distance",
  "print-cost-per-page",
  "flesch-kincaid-reading-level",
  "wpm-productivity",
  "volumetric-weight",
  "thai-post-ems-cost",
  "international-shipping-cost",
  "import-customs-duty",
  "hs-code-import-tax",
  "customs-broker-fee",
  "china-import-lead-time",
  "moq-vs-price",
  "container-weight-capacity",
  "cbm-calculator",
  "warehousing-cost",
  "safety-stock-calculator",
  "reorder-point-calculator",
  "tou-electricity-cost",
  "solar-battery-sizing",
  "solar-inverter-sizing",
  "on-grid-solar-payback",
  "net-metering-revenue",
  "carpool-savings",
  "bts-mrt-vs-car",
  "food-delivery-vs-cooking",
  "lifetime-healthcare-cost",
  "inflation-impact-savings",
  "cost-of-living-comparison",
  "qaly-calculator",
  "gnh-calculator",
  "work-life-balance-score",
  "digital-detox-time",
  "sleep-debt-calculator",
  "habit-streak-calculator",
  "parkinsons-law-calculator",
  "ten-thousand-hours",
  "compound-learning-roi",
  "online-course-roi",
  "metcalfe-network-value",
  "viral-coefficient",
  "dunbar-number",
  "meeting-cost-calculator",
  "meeting-roi",
  "email-response-time",
  "deep-work-calculator",
  "distraction-cost",
  "task-batching",
  "automation-roi",
  "brooks-law",
  "bus-factor",
  "agile-velocity",
  "code-coverage",
  "mttr",
  "mtbf",
  "sla-uptime",
  "rto-rpo",
  "disaster-recovery",
  "cumulative-noise",
  "sound-insulation",
  "lux-lighting",
  "ergonomic-score",
  "standing-desk-ratio",
  "blue-light-exposure",
  "circadian-rhythm",
  "cognitive-load",
  "decision-fatigue",
  "willpower-depletion",
  "flow-state",
  "skill-half-life",
  "learning-rate",
  "forgetting-curve",
  "spaced-repetition",
  "reading-comprehension",
  "note-taking",
  "creativity-score",
  "happiness-roi",
  "time-affluence",
  "relationship-investment",
  "gratitude-journal",
  "social-media-roi",
  "fomo-cost",
  "minimalism-score",
  "diet-environment",
  "behavioral-life",
  "hale-calculator",
  "legacy-score",
  "life-satisfaction"
];

const registry = fs.readFileSync('C:\\Users\\zazad\\.gemini\\antigravity\\scratch\\kamnuan-com\\lib\\toolsData.ts', 'utf8');

const missing = [];
for (const tool of allTools) {
  if (!registry.includes(`id: "${tool}"`) && !registry.includes(`id: '${tool}'`)) {
    // Try without dashes or partial matching
    const base = tool.replace(/-/g, '');
    if (!registry.replace(/-/g, '').includes(base)) {
      missing.push(tool);
    }
  }
}

console.log("Missing Tools Count:", missing.length);
console.log(missing.join(', '));
